/* =====================================================================
   GATE DA 2027 — Syllabus tree, PYQ mapping, study & practice sources
   ---------------------------------------------------------------------
   Topic fields:
     id   unique id
     n    name
     f    PYQ frequency in GATE DA 2024–2026 papers: H (almost every paper),
          M (asked in some papers), L (rare / support topic)
     h    estimated hours (concept + practice) for a zero-level student
     d    depth: how deep to study for GATE
     s    study sources (read / watch)
     p    practice sources: [source, how many questions]
     q    how PYQs ask this topic
     m    must-know facts (Claude adds these if your notes miss them)
     sub  [subtopic, [sub-subtopics]]
   PYQ frequencies are from a memory-based analysis of the 2024–2026
   papers. Verify them against the GATE Overflow "gate-da" tags as you
   solve the PYQs.
   ===================================================================== */

const SUBJECTS = [
/* ------------------------------------------------------------------ */
{
  id: "ps", name: "Probability & Statistics", short: "P&S", color: "#e8590c", marks: "16–22",
  why: "Most important maths subject. It also feeds ML (Naive Bayes, LDA, regression) and AI (Bayes nets), so learning it well pays off three times.",
  books: [
    ["Sheldon Ross — A First Course in Probability (10th ed)", "Main book for probability. Its chapters follow the GATE syllabus order."],
    ["Sheldon Ross — Introduction to Probability and Statistics for Engineers and Scientists", "Confidence intervals, z/t/chi-square tests, CLT. Close to GATE DA style."],
    ["Blitzstein & Hwang — Introduction to Probability (free PDF, Harvard Stat 110)", "Best intuition book. The Stat 110 YouTube lectures are good if you are weak in maths."],
    ["Montgomery & Runger — Applied Statistics and Probability for Engineers", "Extra hypothesis-testing numericals."],
    ["GATE PYQs: DA + CS (probability) + ST/MA (statistics)", "Large question bank. GATE ST questions on tests and CIs are very close to DA."]
  ],
  topics: [
    { id: "ps1", n: "Counting — Permutations & Combinations", f: "M", h: 8,
      d: "Solve counting questions within 3 minutes. Stars & bars, inclusion–exclusion and circular arrangements are enough. Skip advanced generating functions.",
      s: ["Ross FCP — Ch 1 Combinatorial Analysis", "Rosen Discrete Maths — Ch 6 Counting"],
      p: [["Ross FCP Ch 1 — Problems (odd numbered)", "25"], ["Rosen Ch 6 exercises (6.1–6.5)", "20"], ["GATE CS + DA PYQs — combinatorics tag", "all (~40)"]],
      q: "NAT questions: number of arrangements or selections, often used inside a probability question (favourable ÷ total).",
      m: ["nPr = n!/(n−r)!, nCr = n!/(r!(n−r)!)", "Identical objects: n!/(p!q!r!)", "Circular arrangements: (n−1)!  (necklace: (n−1)!/2)", "Stars & bars: n identical into r distinct boxes = C(n+r−1, r−1); with each ≥1: C(n−1, r−1)", "Inclusion–exclusion: |A∪B∪C| = ΣA − ΣA∩B + A∩B∩C", "Derangements D(n) = n! Σ(−1)^k/k!, D(3)=2, D(4)=9, D(5)=44"],
      sub: [
        ["Basic principles", ["Sum rule", "Product rule", "Complement counting"]],
        ["Permutations", ["Distinct objects", "With repetition", "Identical objects (multinomial)", "Circular permutations", "Restricted arrangements (together / not together)"]],
        ["Combinations", ["nCr and identities (Pascal)", "Selections with restrictions", "Stars & bars (identical into distinct)", "Binomial & multinomial theorem"]],
        ["Advanced counting", ["Inclusion–exclusion principle", "Derangements", "Pigeonhole principle (basic)"]]
      ] },
    { id: "ps2", n: "Probability Axioms, Sample Space & Events", f: "H", h: 6,
      d: "Know the difference between mutually exclusive and independent events. Solve standard problems on dice, cards, coins and balls in urns.",
      s: ["Ross FCP — Ch 2 Axioms of Probability", "Blitzstein — Ch 1"],
      p: [["Ross FCP Ch 2 — Problems", "20"], ["Blitzstein Ch 1 exercises", "10"], ["GATE DA/CS PYQs — probability basics", "all"]],
      q: "MCQ/MSQ statements such as 'if A and B are independent then …'. Also NAT questions with dice, cards or urns.",
      m: ["P(A∪B) = P(A)+P(B)−P(A∩B)", "Mutually exclusive: P(A∩B)=0. Independent: P(A∩B)=P(A)P(B)", "Mutually exclusive events with non-zero probabilities can NEVER be independent", "If A and B are independent then A and Bᶜ, Aᶜ and Bᶜ are also independent", "Pairwise independence does not imply mutual independence"],
      sub: [
        ["Basics", ["Random experiment & sample space", "Events, union, intersection, complement", "Equally likely outcomes"]],
        ["Axioms", ["Kolmogorov axioms", "Derived properties (complement, monotonicity)", "Addition rule for 2 and 3 events"]],
        ["Event relations", ["Mutually exclusive events", "Independent events", "Pairwise vs mutual independence", "Exhaustive events"]]
      ] },
    { id: "ps3", n: "Conditional, Joint & Marginal Probability, Bayes Theorem", f: "H", h: 8,
      d: "Very important. Draw a tree diagram for every problem and state the total-probability step before applying Bayes. Practise reading joint probability tables.",
      s: ["Ross FCP — Ch 3 Conditional Probability and Independence", "Blitzstein — Ch 2 (best explanation of Bayes)"],
      p: [["Ross FCP Ch 3 — Problems", "30"], ["Blitzstein Ch 2 exercises", "15"], ["GATE DA/CS/ST PYQs — conditional/Bayes", "all"]],
      q: "Every paper has a Bayes or total-probability NAT (disease test, defective machine, urn switching). Joint tables ask for a marginal or conditional value.",
      m: ["P(A|B) = P(A∩B)/P(B)", "Total probability: P(A) = Σ P(A|Bi) P(Bi)", "Bayes: P(Bi|A) = P(A|Bi)P(Bi) / Σ P(A|Bj)P(Bj)", "Marginal = sum of a row/column of the joint table", "Chain rule: P(ABC) = P(A)P(B|A)P(C|AB)"],
      sub: [
        ["Conditional probability", ["Definition & reduced sample space", "Multiplication rule / chain rule", "Tree diagrams"]],
        ["Joint & marginal", ["Joint probability tables", "Marginalization", "Conditional from joint"]],
        ["Total probability & Bayes", ["Law of total probability", "Bayes theorem", "Prior, likelihood, posterior terms", "Classic problems: medical test, urns, defective items"]]
      ] },
    { id: "ps4", n: "Random Variables, Expectation, Variance, Covariance & Correlation", f: "H", h: 9,
      d: "Use linearity of expectation, Var(aX+b) and Cov/Corr properties without thinking. Compute mean, median, mode and SD of a dataset by hand.",
      s: ["Ross FCP — Ch 4 (4.1–4.5) and Ch 7 (7.1–7.4)", "Blitzstein — Ch 3, 4, 7.3"],
      p: [["Ross FCP Ch 4 Problems (4.1–4.5 related)", "20"], ["Ross FCP Ch 7 Problems (expectation of sums, covariance)", "15"], ["GATE DA/ST PYQs — expectation / covariance", "all"]],
      q: "NAT: E[X] or Var(X) from a PMF, Var(2X−3Y) with a given covariance, and correlation coefficient from data. MSQ: properties of correlation.",
      m: ["E[aX+b] = aE[X]+b; Var(aX+b) = a²Var(X)", "Var(X) = E[X²] − (E[X])²", "Var(X±Y) = Var X + Var Y ± 2Cov(X,Y)", "Cov(X,Y) = E[XY] − E[X]E[Y]", "ρ = Cov/(σx σy), −1 ≤ ρ ≤ 1, unchanged by scaling (sign flips if the scale factor is negative)", "Independent ⇒ Cov = 0, but Cov = 0 does NOT imply independent", "LOTUS: E[g(X)] = Σ g(x)p(x)", "Median/mode of data; SD of a sample uses n−1"],
      sub: [
        ["Descriptive statistics", ["Mean, median, mode", "Variance & standard deviation (population vs sample)", "Quartiles, range (basic)"]],
        ["Random variables", ["Definition, discrete vs continuous", "PMF, PDF, CDF relations", "Functions of a RV"]],
        ["Expectation", ["Expected value", "LOTUS", "Linearity of expectation (indicator trick)", "Moments"]],
        ["Variance", ["Definition & shortcut formula", "Properties of variance", "Variance of sums"]],
        ["Covariance & correlation", ["Covariance properties", "Pearson correlation coefficient", "Correlation vs independence"]]
      ] },
    { id: "ps5", n: "Discrete Distributions (Uniform, Bernoulli, Binomial, Poisson, Geometric)", f: "H", h: 7,
      d: "Know the PMF, mean and variance of each distribution by heart. Recognise which distribution a word problem describes. Know Poisson as the limit of the binomial.",
      s: ["Ross FCP — Ch 4 (4.6–4.9)", "Blitzstein — Ch 3, 4"],
      p: [["Ross FCP Ch 4 Problems (binomial, Poisson, geometric)", "25"], ["GATE DA/ST/CS PYQs — distributions", "all"]],
      q: "NAT: P(X ≥ 2) for binomial or Poisson, and mean/variance given one of them. Memoryless property of the geometric distribution.",
      m: ["Bernoulli(p): mean p, var p(1−p)", "Binomial(n,p): C(n,k)p^k(1−p)^(n−k), mean np, var np(1−p)", "Poisson(λ): e^(−λ)λ^k/k!, mean = var = λ", "Geometric: P(X=k) = (1−p)^(k−1)p, mean 1/p, memoryless", "Discrete uniform on {1..n}: mean (n+1)/2, var (n²−1)/12", "Sum of independent Poissons is Poisson(λ1+λ2)"],
      sub: [
        ["PMF & CDF", ["PMF properties", "CDF of a discrete RV (step function)"]],
        ["Distributions", ["Discrete uniform", "Bernoulli", "Binomial", "Poisson (and binomial → Poisson limit)", "Geometric (memoryless)", "Hypergeometric (sampling without replacement, basic)"]],
        ["Properties", ["Mean & variance of each", "Sum of independent binomials / Poissons"]]
      ] },
    { id: "ps6", n: "Continuous Distributions (Uniform, Exponential, Normal, t, χ²)", f: "H", h: 10,
      d: "Integrate a PDF to get a probability or the CDF. Standardise to Z and use the Φ table. Know the definitions of t and χ² and their degrees of freedom. You do not need to derive their PDFs.",
      s: ["Ross FCP — Ch 5 Continuous Random Variables", "Ross IPS — Ch 5.4–5.8 (normal, exponential, χ², t)", "Blitzstein — Ch 5"],
      p: [["Ross FCP Ch 5 Problems", "25"], ["Ross IPS Ch 5 Problems (normal/χ²/t parts)", "15"], ["GATE DA/ST PYQs — continuous RVs", "all"]],
      q: "NAT: find the constant k so a PDF integrates to 1, P(a<X<b), median of a PDF, P(X>s+t | X>s) for exponential, and normal probability with a Φ value given.",
      m: ["PDF integrates to 1; P(a<X<b) = ∫f; CDF F'(x) = f(x)", "Uniform(a,b): mean (a+b)/2, var (b−a)²/12", "Exponential(λ): f = λe^(−λx), mean 1/λ, var 1/λ², memoryless", "Normal: Z = (X−μ)/σ; 68–95–99.7 rule", "aX+b of a normal is normal; sum of independent normals is normal", "χ²(k) = sum of k squared standard normals, mean k, var 2k", "t(n) = Z/√(χ²/n); heavier tails than the normal, → normal as n→∞", "Median m: F(m) = 0.5"],
      sub: [
        ["Continuous RV basics", ["PDF & its properties", "CDF, and PDF ↔ CDF", "Mean, variance, median via integration", "Percentiles"]],
        ["Distributions", ["Continuous uniform", "Exponential (memoryless)", "Normal & standard normal (Z-table)", "Student t-distribution", "Chi-squared distribution"]],
        ["Transformations", ["Linear transformation of normal", "CDF method for Y = g(X) (basic)"]]
      ] },
    { id: "ps7", n: "Joint Distributions, Conditional PDF, Conditional Expectation & Variance", f: "M", h: 8,
      d: "Given a joint PDF or PMF, find the marginal, the conditional and E[X|Y]. Know the law of total expectation. The law of total variance is asked less often but is in the syllabus.",
      s: ["Ross FCP — Ch 6 Jointly Distributed RVs (6.1–6.5)", "Ross FCP — Ch 7.5 Conditional Expectation", "Blitzstein — Ch 7, 9"],
      p: [["Ross FCP Ch 6 Problems", "15"], ["Ross FCP Ch 7 Problems (conditional expectation)", "10"], ["GATE DA PYQs — conditional expectation", "all"]],
      q: "NAT: E[X | Y=y] from a joint table or PDF, marginal PDF from a joint PDF, and independence checks.",
      m: ["f_X(x) = ∫ f(x,y) dy", "f(x|y) = f(x,y)/f_Y(y)", "Independent ⇔ f(x,y) = f_X(x) f_Y(y) for all x, y", "E[X] = E[E[X|Y]] (tower property)", "Var(X) = E[Var(X|Y)] + Var(E[X|Y])"],
      sub: [
        ["Joint distributions", ["Joint PMF/PDF", "Marginal distributions", "Independence of RVs"]],
        ["Conditional distributions", ["Conditional PMF", "Conditional PDF"]],
        ["Conditional expectation", ["E[X|Y] computation", "Law of total expectation", "Conditional variance & law of total variance"]]
      ] },
    { id: "ps8", n: "Sampling Distributions & Central Limit Theorem", f: "M", h: 5,
      d: "Know that the sample mean has mean μ and variance σ²/n and is approximately normal by the CLT. Apply the continuity correction only if the question needs it.",
      s: ["Ross IPS — Ch 6 Distributions of Sampling Statistics", "Ross FCP — Ch 8.3 CLT"],
      p: [["Ross IPS Ch 6 Problems", "15"], ["GATE ST/DA PYQs — CLT", "all"]],
      q: "Approximate P(X̄ > c) or P(ΣXi > c) using the CLT. Standard error calculations.",
      m: ["E[X̄] = μ, Var(X̄) = σ²/n, SE = σ/√n", "CLT: (X̄−μ)/(σ/√n) → N(0,1) for large n (any distribution with finite variance)", "(n−1)S²/σ² ~ χ²(n−1) for normal samples", "Law of Large Numbers: X̄ → μ"],
      sub: [
        ["Sampling", ["Population vs sample", "Statistic vs parameter", "Sample mean & sample variance"]],
        ["Limit theorems", ["Law of large numbers (idea)", "Central limit theorem", "Normal approximation to binomial"]],
        ["Sampling distributions", ["Distribution of X̄", "Distribution of S² (χ²)", "Standard error"]]
      ] },
    { id: "ps9", n: "Confidence Intervals", f: "M", h: 5,
      d: "Build a CI for a mean with σ known (z) or unknown (t), and for a proportion. Know how the CI width changes with n and with the confidence level.",
      s: ["Ross IPS — Ch 7 Parameter Estimation (7.3–7.5)", "Montgomery — Ch 8"],
      p: [["Ross IPS Ch 7 Problems (interval estimation)", "15"], ["GATE ST/DA PYQs — confidence interval", "all"]],
      q: "NAT: CI bounds or the sample size n needed for a given width. MCQ: correct interpretation of a CI.",
      m: ["σ known: X̄ ± z(α/2) σ/√n", "σ unknown: X̄ ± t(α/2, n−1) S/√n", "Proportion: p̂ ± z √(p̂(1−p̂)/n)", "z(0.025) = 1.96, z(0.05) = 1.645, z(0.005) = 2.576", "Width ∝ 1/√n; 4× the samples halves the width", "95% CI means 95% of such intervals contain μ (not 'μ lies inside with prob 0.95')"],
      sub: [
        ["Point estimation", ["Estimator, unbiasedness", "Sample mean & variance as estimators", "MLE idea (basic)"]],
        ["Interval estimation", ["CI for mean (σ known, z)", "CI for mean (σ unknown, t)", "CI for proportion", "Sample size determination", "Interpretation"]]
      ] },
    { id: "ps10", n: "Hypothesis Testing: z-test, t-test, χ²-test", f: "H", h: 9,
      d: "Follow the full procedure: hypotheses → test statistic → critical value or p-value → decision. Know Type I/II errors. Know the χ² test for goodness of fit and for independence (contingency tables).",
      s: ["Ross IPS — Ch 8 Hypothesis Testing", "Ross IPS — Ch 11 Goodness of Fit (χ²)", "Montgomery — Ch 9"],
      p: [["Ross IPS Ch 8 Problems", "20"], ["Ross IPS Ch 11 Problems (χ² GOF & independence)", "10"], ["GATE ST/DA PYQs — hypothesis testing", "all"]],
      q: "Compute a z or t statistic and decide reject / do not reject. χ² statistic from a contingency table. MSQ on p-values and errors.",
      m: ["Type I error = reject a true H0 (prob α). Type II = accept a false H0 (prob β). Power = 1−β", "z = (X̄−μ0)/(σ/√n); t = (X̄−μ0)/(S/√n), df = n−1", "Two-sample t, paired t (d = differences)", "χ² = Σ (O−E)²/E; GOF df = k−1−(#params estimated); independence df = (r−1)(c−1)", "Expected count in a contingency table = rowTotal × colTotal / N", "Reject H0 if p-value < α"],
      sub: [
        ["Framework", ["Null & alternative hypothesis", "One-tailed vs two-tailed", "Significance level, critical region", "p-value", "Type I & II errors, power"]],
        ["z-test", ["One-sample z-test", "z-test for proportions", "Two-sample z-test"]],
        ["t-test", ["One-sample t-test", "Two-sample (independent) t-test", "Paired t-test"]],
        ["Chi-squared test", ["Goodness of fit", "Test of independence (contingency tables)", "Test for variance (basic)"]]
      ] }
  ]
},
/* ------------------------------------------------------------------ */
{
  id: "la", name: "Linear Algebra", short: "LA", color: "#1c7ed6", marks: "10–14",
  why: "The base for ML (regression = projection, PCA = eigen/SVD). DA questions are conceptual (rank, eigen properties, projection matrices), not heavy calculation.",
  books: [
    ["Gilbert Strang — Introduction to Linear Algebra (5th ed)", "Main book. The GATE DA syllabus follows Strang closely (projection, SVD, four subspaces)."],
    ["MIT 18.06 lectures (Strang, YouTube/OCW)", "Watch alongside the book. Problem sets and exams with solutions are free on OCW."],
    ["3Blue1Brown — Essence of Linear Algebra (YouTube)", "For zero level. Watch first so you can picture each concept."],
    ["Strang — Linear Algebra and Learning from Data", "Optional. Connects SVD and PCA to ML."],
    ["GATE PYQs: DA + MA + CS/EE/EC (linear algebra)", "Eigenvalue, rank and system questions repeat across papers."]
  ],
  topics: [
    { id: "la1", n: "Matrices & Special Matrices (orthogonal, idempotent, projection, partition)", f: "H", h: 9,
      d: "Know the properties of every special matrix listed in the syllabus. These are the most common MSQ statements.",
      s: ["Strang ILA — Ch 2.4–2.5 (matrix ops, inverse), 2.7 (transpose, symmetric)", "Strang — 4.2 (projection matrices), 4.4 (orthogonal matrices)"],
      p: [["Strang Problem Sets 2.4, 2.5, 2.7", "20"], ["Strang 4.2 & 4.4 problems", "15"], ["GATE DA/MA PYQs — matrix properties", "all"]],
      q: "MSQ: which statements are true for an idempotent/orthogonal/projection matrix (eigenvalues, rank, determinant). Block-matrix inverse/determinant in NAT.",
      m: ["Orthogonal: QᵀQ = I, Q⁻¹ = Qᵀ, det = ±1, |λ| = 1, preserves lengths", "Idempotent: A² = A, eigenvalues ∈ {0,1}, rank = trace", "Projection: P = A(AᵀA)⁻¹Aᵀ, P² = P, Pᵀ = P; I−P is also a projection", "(AB)ᵀ = BᵀAᵀ, (AB)⁻¹ = B⁻¹A⁻¹", "Block: det[[A,B],[0,D]] = det A · det D", "Schur complement: det[[A,B],[C,D]] = det(A) det(D − CA⁻¹B)", "Nilpotent: all eigenvalues 0", "Symmetric real ⇒ real eigenvalues, orthogonal eigenvectors"],
      sub: [
        ["Matrix basics", ["Addition, multiplication, transpose", "Trace & its properties", "Inverse & its properties", "Symmetric & skew-symmetric"]],
        ["Special matrices", ["Orthogonal matrix", "Idempotent matrix", "Projection matrix", "Nilpotent & involutory (bonus)", "Triangular & diagonal"]],
        ["Partitioned matrices", ["Block multiplication", "Block inverse", "Block determinant & Schur complement"]]
      ] },
    { id: "la2", n: "Determinants", f: "M", h: 4,
      d: "Know the properties so you can find determinants without expanding. Practise 3×3 and 4×4 matrices with a pattern.",
      s: ["Strang ILA — Ch 5 Determinants (5.1–5.2)"],
      p: [["Strang Problem Sets 5.1, 5.2", "15"], ["GATE PYQs — determinant", "all"]],
      q: "Direct NAT (determinant of a patterned matrix) or det(kA), det(A⁻¹), det(AᵀA).",
      m: ["det(AB) = det A det B, det(Aᵀ) = det A, det(A⁻¹) = 1/det A", "det(kA) = kⁿ det A for n×n", "Row swap flips the sign; adding a multiple of a row keeps det the same", "det = product of eigenvalues = product of pivots", "Triangular: det = product of the diagonal"],
      sub: [
        ["Computation", ["Cofactor expansion", "Row reduction method", "Triangular matrices"]],
        ["Properties", ["Multiplicative property", "Effect of row operations", "det & invertibility"]]
      ] },
    { id: "la3", n: "Systems of Linear Equations, Gaussian Elimination & LU", f: "H", h: 8,
      d: "Use rank conditions to decide unique, infinite or no solution. Perform elimination and LU by hand for 3×3 matrices.",
      s: ["Strang ILA — Ch 2.1–2.3 (elimination), 2.6 (LU), Ch 3.3–3.4 (complete solution Ax=b)"],
      p: [["Strang Problem Sets 2.2, 2.3, 2.6", "20"], ["Strang 3.4 problems (complete solution)", "10"], ["GATE MA/CS/EE PYQs — systems of equations", "all"]],
      q: "For which value of k does the system have infinite/no solutions? Find the L or U entries. Dimension of the solution set.",
      m: ["Unique solution: rank(A) = rank([A|b]) = n", "Infinite: rank(A) = rank([A|b]) < n; free variables = n − rank", "No solution: rank(A) < rank([A|b])", "Homogeneous Ax=0 always has x=0; non-trivial iff det A = 0 (square)", "LU: L holds the multipliers (unit diagonal), U is the echelon form; needs no row swaps (else PA = LU)"],
      sub: [
        ["Elimination", ["Row echelon form", "Reduced row echelon form (RREF)", "Pivots & free variables"]],
        ["Solutions", ["Consistency via rank", "Unique / infinite / no solutions", "Homogeneous systems", "Complete solution = particular + nullspace"]],
        ["LU decomposition", ["Computing L and U", "Existence conditions, PA = LU", "Solving with LU"]]
      ] },
    { id: "la4", n: "Vector Spaces, Subspaces, Independence, Basis, Rank & Nullity", f: "H", h: 9,
      d: "Test whether a set is a subspace. Find a basis and the dimension of the column space and null space. Use the rank–nullity theorem.",
      s: ["Strang ILA — Ch 3 Vector Spaces and Subspaces (3.1–3.5)", "3Blue1Brown EoLA — Ep 2, 3, 7"],
      p: [["Strang Problem Sets 3.1, 3.2, 3.5", "25"], ["GATE DA/MA PYQs — rank, independence, subspace", "all"]],
      q: "MSQ: which sets are subspaces. Rank or nullity of a given matrix. Is a set of vectors independent? Dimension of a span.",
      m: ["Subspace test: contains 0, closed under + and scalar ×", "Rank–nullity: rank + nullity = number of columns", "rank(A) = rank(Aᵀ) = rank(AᵀA)", "rank(AB) ≤ min(rank A, rank B)", "Four subspaces: C(A), N(A) in Rⁿ; C(Aᵀ), N(Aᵀ); N(A) ⊥ row space", "More than n vectors in Rⁿ are always dependent"],
      sub: [
        ["Vector spaces", ["Axioms", "Examples (Rⁿ, polynomials, matrices)", "Subspaces & subspace test"]],
        ["Independence", ["Linear combinations & span", "Linear dependence/independence", "Basis & dimension"]],
        ["Rank & nullity", ["Column space, row space", "Null space & left null space", "Rank–nullity theorem", "Four fundamental subspaces"]]
      ] },
    { id: "la5", n: "Eigenvalues & Eigenvectors, Diagonalization", f: "H", h: 10,
      d: "The most tested LA topic. Get eigenvalues quickly using trace/det shortcuts and the properties of special matrices. Know the diagonalizability conditions and Cayley–Hamilton.",
      s: ["Strang ILA — Ch 6.1–6.2 (eigen, diagonalization), 6.4 (symmetric)", "3Blue1Brown EoLA — Ep 14"],
      p: [["Strang Problem Sets 6.1, 6.2, 6.4", "30"], ["GATE DA/MA/EE/EC/CS PYQs — eigenvalues", "all (big pool)"]],
      q: "NAT: largest eigenvalue, sum/product of eigenvalues, eigenvalues of A², A⁻¹ or A+kI. MSQ: diagonalizability, symmetric-matrix facts.",
      m: ["Σλ = trace, Πλ = det", "Eigenvalues of A^k: λ^k; A⁻¹: 1/λ; A+kI: λ+k; same eigenvectors", "Triangular: eigenvalues = diagonal entries", "Aᵀ has the same eigenvalues as A", "Distinct eigenvalues ⇒ diagonalizable", "Diagonalizable iff geometric multiplicity = algebraic multiplicity for every λ", "Cayley–Hamilton: A satisfies its own characteristic equation", "Similar matrices (B = P⁻¹AP) have the same eigenvalues, trace and det", "Rank-1 matrix uvᵀ: eigenvalues vᵀu and 0 (n−1 times)"],
      sub: [
        ["Computing eigen", ["Characteristic polynomial", "Eigenvectors & eigenspaces", "Shortcuts: trace, det, triangular"]],
        ["Properties", ["Eigen of powers, inverse, shift", "Eigen of special matrices", "Algebraic vs geometric multiplicity", "Cayley–Hamilton theorem"]],
        ["Diagonalization", ["A = SΛS⁻¹", "Conditions for diagonalizability", "Similar matrices", "Spectral theorem (symmetric: A = QΛQᵀ)"]]
      ] },
    { id: "la6", n: "Orthogonality, Projections & Least Squares", f: "M", h: 6,
      d: "Project a vector onto a line or a subspace. Solve least squares with the normal equations. This links directly to linear regression in ML.",
      s: ["Strang ILA — Ch 4.1–4.4 (orthogonality, projections, least squares, Gram–Schmidt)"],
      p: [["Strang Problem Sets 4.2, 4.3, 4.4", "20"], ["GATE DA PYQs — projection", "all"]],
      q: "NAT: projection of b onto a, entries of a projection matrix, least-squares solution.",
      m: ["Projection onto a line: p = (aᵀb / aᵀa) a", "Onto C(A): x̂ = (AᵀA)⁻¹Aᵀb, p = Ax̂", "Error e = b − p is ⊥ to C(A)", "Normal equations: AᵀA x̂ = Aᵀb", "Gram–Schmidt gives orthonormal Q; A = QR"],
      sub: [
        ["Orthogonality", ["Dot product & norms", "Orthogonal vectors & subspaces", "Orthonormal bases"]],
        ["Projections", ["Projection onto a line", "Projection onto a subspace", "Projection matrix properties"]],
        ["Least squares", ["Normal equations", "Fitting a line", "Gram–Schmidt & QR (basic)"]]
      ] },
    { id: "la7", n: "Quadratic Forms & Positive Definiteness", f: "M", h: 4,
      d: "Write xᵀAx for a quadratic expression. Test positive definiteness by eigenvalues, pivots or leading minors.",
      s: ["Strang ILA — Ch 6.5 Positive Definite Matrices"],
      p: [["Strang Problem Set 6.5", "15"], ["GATE MA/DA PYQs — quadratic forms", "all"]],
      q: "Classify a quadratic form (PD/PSD/indefinite). Find the matrix of a quadratic form. Min/max of xᵀAx on a unit vector = min/max eigenvalue.",
      m: ["xᵀAx with A symmetric: off-diagonal entry = half the coefficient of xᵢxⱼ", "PD ⇔ all λ > 0 ⇔ all pivots > 0 ⇔ all leading principal minors > 0", "AᵀA is always PSD; PD iff A has independent columns", "Rayleigh quotient: min λ ≤ xᵀAx/xᵀx ≤ max λ"],
      sub: [
        ["Quadratic forms", ["Matrix representation", "Canonical / diagonal form"]],
        ["Definiteness", ["PD, PSD, ND, indefinite", "Tests: eigenvalues, pivots, minors", "Rayleigh quotient"]]
      ] },
    { id: "la8", n: "Singular Value Decomposition (SVD)", f: "H", h: 6,
      d: "Compute singular values from AᵀA. Know the rank, norms and low-rank approximation. Understand how SVD connects to PCA.",
      s: ["Strang ILA — Ch 7 The SVD (7.1–7.3)", "MIT 18.06 Lecture 29 (SVD)"],
      p: [["Strang Problem Sets 7.1, 7.2", "15"], ["GATE DA PYQs — SVD", "all"]],
      q: "NAT: singular values of a small matrix, rank from Σ, the best rank-k approximation error.",
      m: ["A = UΣVᵀ; U, V orthogonal; Σ diagonal with σ ≥ 0", "σᵢ = √(eigenvalues of AᵀA)", "rank(A) = number of non-zero σ", "For symmetric PSD A, singular values = eigenvalues", "‖A‖₂ = σ₁; ‖A‖F² = Σσᵢ²", "Best rank-k approximation (Eckart–Young): keep the top k σ; error = σ(k+1) in the 2-norm"],
      sub: [
        ["SVD", ["Definition & shapes of U, Σ, V", "Computing via AᵀA and AAᵀ", "Geometric meaning"]],
        ["Applications", ["Rank & norms", "Low-rank approximation", "Pseudo-inverse (basic)", "Connection to PCA"]]
      ] }
  ]
},
/* ------------------------------------------------------------------ */
{
  id: "co", name: "Calculus & Optimization", short: "Calc", color: "#2f9e44", marks: "5–8",
  why: "Small syllabus with standard questions. Also needed for PDF integration (P&S) and gradient descent (ML).",
  books: [
    ["Thomas' Calculus (12th+ ed)", "Main book for limits, continuity, derivatives, extrema and Taylor series."],
    ["3Blue1Brown — Essence of Calculus (YouTube)", "For zero level. Watch before reading."],
    ["B.S. Grewal — Higher Engineering Mathematics", "Many practice numericals at GATE difficulty."],
    ["GATE PYQs: DA + CS/EE/EC/ME/IN (calculus)", "Very large pool of limit and maxima/minima questions."]
  ],
  topics: [
    { id: "co0", n: "Integration Basics (support topic for P&S)", f: "L", h: 5,
      d: "Not in the calculus syllabus, but you need it for PDFs and expectations. Standard integrals, integration by parts, and ∫xⁿe^(−x).",
      s: ["Thomas — Ch 5 Integrals, Ch 8.1–8.2 (integration by parts)", "Khan Academy — Integral calculus"],
      p: [["Thomas Ch 5 & 8.2 exercises (odd numbered)", "25"]],
      q: "Appears inside probability questions (normalising constant, E[X] of a PDF).",
      m: ["∫xⁿ dx = xⁿ⁺¹/(n+1)", "∫e^(ax) dx = e^(ax)/a", "By parts: ∫u dv = uv − ∫v du", "∫₀^∞ xⁿ e^(−x) dx = n! (Gamma function)", "∫₀^∞ λe^(−λx) dx = 1"],
      sub: [["Integration", ["Standard integrals", "Substitution", "By parts", "Definite integrals & area", "Gamma integral"]]] },
    { id: "co1", n: "Functions, Limits", f: "M", h: 5,
      d: "Solve standard limits, L'Hôpital, and limits at infinity quickly. Know one-sided limits.",
      s: ["Thomas — Ch 1 (functions), Ch 2 Limits and Continuity (2.1–2.6)", "3Blue1Brown EoC — Ep 7"],
      p: [["Thomas Ch 2 exercises (odd numbered)", "25"], ["GATE CS/EE/DA PYQs — limits", "all"]],
      q: "NAT: evaluate a limit (0/0, ∞/∞, 1^∞ forms).",
      m: ["lim sin x / x = 1 (x→0)", "lim (1+1/x)^x = e; (1+x)^(1/x) → e (x→0)", "1^∞ form: e^(lim (f−1)g)", "L'Hôpital only for 0/0 or ∞/∞", "lim (eˣ−1)/x = 1, lim ln(1+x)/x = 1"],
      sub: [
        ["Functions", ["Domain & range", "Composite & inverse functions", "Even/odd, monotonic functions"]],
        ["Limits", ["Left & right limits", "Standard limits", "L'Hôpital's rule", "Indeterminate forms", "Limits at infinity"]]
      ] },
    { id: "co2", n: "Continuity & Differentiability", f: "M", h: 5,
      d: "Check continuity and differentiability of piecewise and |x| functions. Know Rolle's theorem and the Mean Value Theorem.",
      s: ["Thomas — Ch 2.5 (continuity), Ch 3.1–3.2 (derivative), Ch 4.2 (MVT)"],
      p: [["Thomas Ch 2.5, 3.2, 4.2 exercises", "20"], ["GATE CS/EE/DA PYQs — continuity/differentiability", "all"]],
      q: "MCQ/MSQ: is f continuous or differentiable at x = a? Find the constants that make a piecewise function differentiable.",
      m: ["Differentiable ⇒ continuous (the converse is false, e.g. |x| at 0)", "Continuity: LHL = RHL = f(a)", "Differentiable: LHD = RHD", "Rolle: f(a) = f(b) ⇒ some c with f'(c) = 0", "MVT: f'(c) = (f(b) − f(a))/(b − a)", "IVT for continuous functions"],
      sub: [
        ["Continuity", ["Definition", "Types of discontinuity", "Intermediate value theorem"]],
        ["Differentiability", ["Derivative from first principles", "Left/right derivatives", "Piecewise & |x| functions"]],
        ["Mean value theorems", ["Rolle's theorem", "Lagrange MVT"]]
      ] },
    { id: "co3", n: "Differentiation (incl. ML derivatives, partial derivatives, gradient)", f: "M", h: 5,
      d: "Differentiate any function quickly with the chain rule. Learn the derivatives of sigmoid, softmax and log-loss, since ML questions use them.",
      s: ["Thomas — Ch 3 Derivatives, Ch 14.3 (partial derivatives), 14.5 (gradient)"],
      p: [["Thomas Ch 3 exercises (odd numbered)", "20"], ["Thomas Ch 14.3 exercises", "10"]],
      q: "Used inside optimization, gradient-descent and backpropagation questions.",
      m: ["Chain rule: (f∘g)' = f'(g)·g'", "σ(x) = 1/(1+e^(−x)); σ' = σ(1−σ)", "tanh' = 1 − tanh²", "d/dx ln x = 1/x; d/dx aˣ = aˣ ln a", "Gradient ∇f = vector of partial derivatives; points in the direction of steepest increase"],
      sub: [["Differentiation", ["Rules (product, quotient, chain)", "Standard derivatives", "Higher-order derivatives", "Implicit & log differentiation", "Partial derivatives & gradient", "Derivatives used in ML"]]] },
    { id: "co4", n: "Taylor Series", f: "M", h: 4,
      d: "Know the standard Maclaurin series. Find a particular coefficient. Use the series for approximation.",
      s: ["Thomas — Ch 10.8–10.9 Taylor and Maclaurin Series"],
      p: [["Thomas Ch 10.8–10.9 exercises", "15"], ["GATE PYQs — Taylor series", "all"]],
      q: "NAT: coefficient of xᵏ in an expansion, or an approximate value of f near a point.",
      m: ["f(x) = Σ f⁽ⁿ⁾(a)(x−a)ⁿ/n!", "eˣ = 1 + x + x²/2! + …", "sin x = x − x³/3! + …; cos x = 1 − x²/2! + …", "ln(1+x) = x − x²/2 + x³/3 − …", "1/(1−x) = 1 + x + x² + … (|x|<1)"],
      sub: [["Taylor series", ["Taylor polynomial", "Maclaurin series of standard functions", "Finding a coefficient", "Approximation & error (basic)"]]] },
    { id: "co5", n: "Maxima & Minima, Single-Variable Optimization", f: "H", h: 7,
      d: "Main calculus topic. Find critical points, apply the second-derivative test, and find global extrema on closed intervals. Know convexity.",
      s: ["Thomas — Ch 4.1–4.6 Applications of Derivatives", "Boyd & Vandenberghe — Convex Optimization Ch 3.1 (optional, convex functions)"],
      p: [["Thomas Ch 4.1, 4.3, 4.4, 4.6 exercises", "30"], ["GATE CS/EE/ME/DA PYQs — maxima/minima", "all (big pool)"]],
      q: "NAT: maximum value of f on [a,b], number of local extrema, word problems (max area, min cost).",
      m: ["Critical points: f'(x) = 0 or f' undefined", "f'' > 0 ⇒ local min; f'' < 0 ⇒ local max; f'' = 0 ⇒ check higher derivatives or the sign change of f'", "Global extrema on [a,b]: compare f at critical points AND endpoints", "Convex: f'' ≥ 0; a local min of a convex function is global", "Inflection point: f'' changes sign"],
      sub: [
        ["Extrema", ["Critical points", "First derivative test", "Second derivative test", "Global extrema on a closed interval"]],
        ["Shape", ["Increasing/decreasing", "Concavity & inflection", "Convex functions"]],
        ["Optimization", ["Word problems", "Constraints by substitution"]]
      ] },
    { id: "co6", n: "Gradient Descent (bonus, bridges to ML)", f: "L", h: 3,
      d: "Perform one or two gradient-descent updates by hand. Know the effect of the learning rate.",
      s: ["ISL — Ch 10.7 (fitting neural networks)", "Andrew Ng CS229 notes — gradient descent"],
      p: [["Make your own 1-D GD update examples", "10"], ["GATE DA PYQs — gradient descent", "all"]],
      q: "NAT: value of x after k gradient steps on f(x).",
      m: ["x ← x − η f'(x)", "η too large ⇒ divergence/oscillation; too small ⇒ slow", "Convex + suitable η ⇒ converges to the global min"],
      sub: [["Gradient descent", ["Update rule", "Learning rate effect", "Convergence on convex functions"]]] }
  ]
},
/* ------------------------------------------------------------------ */
{
  id: "pd", name: "Programming, DS & Algorithms (Python)", short: "PDSA", color: "#7048e8", marks: "14–20",
  why: "High-scoring. The questions are mostly Python code output and algorithm traces, and practice makes them very accurate.",
  books: [
    ["NPTEL — Programming, Data Structures and Algorithms using Python (Madhavan Mukund, CMI)", "Closest match to the GATE DA PDSA syllabus. Watch all weeks and do the assignments."],
    ["Allen Downey — Think Python (free)", "Python basics from zero."],
    ["CLRS — Introduction to Algorithms (3rd ed)", "Reference for sorting, hashing, BST, heaps, graphs, recurrences."],
    ["Narasimha Karumanchi — Data Structures and Algorithms Made Easy (in Python)", "Many practice problems per data structure."],
    ["GATE CS PYQs (DS + Algorithms) via GATE Overflow", "The biggest source. Most DA-style algorithm questions exist in CS PYQs."]
  ],
  topics: [
    { id: "pd1", n: "Python Programming (core language & output prediction)", f: "H", h: 16,
      d: "The most important PDSA topic. Predict the output of any 15–20 line snippet: mutability, aliasing, slicing, scope, default arguments, recursion and comprehensions. Run and modify every example yourself.",
      s: ["Think Python — Ch 1–12, 15–17", "NPTEL Mukund PDSA — Weeks 1–4", "Python official tutorial (docs.python.org) — sections 3–9"],
      p: [["Write & predict 5 tricky snippets daily (lists, dicts, strings, recursion)", "150"], ["NPTEL PDSA weekly programming assignments", "all"], ["GATE DA PYQs — Python code output", "all"]],
      q: "Most PDSA marks: 'What is the output of this Python code?' with recursion, list mutation, dict updates, string slicing, generators or classes.",
      m: ["Lists, dicts and sets are mutable; str, tuple and int are immutable", "b = a aliases a list; a[:] or list(a) makes a shallow copy", "Default argument def f(x, L=[]) is created once and shared between calls", "// is floor division (−7//2 = −4); % takes the sign of the divisor (−7%2 = 1)", "Slicing s[a:b:c], negative indices, s[::-1] reverses", "Scope: LEGB rule; global / nonlocal", "range(a,b,s) excludes b", "list.sort() returns None; sorted() returns a new list", "is checks identity, == checks equality", "Short-circuit and/or return one of the operands"],
      sub: [
        ["Basics", ["Data types & dynamic typing", "Operators & precedence (//, %, **)", "Input/output, f-strings", "Control flow (if, for, while, break, continue, else on loops)"]],
        ["Strings", ["Indexing & slicing", "String methods", "Immutability"]],
        ["Collections", ["Lists & list methods", "Aliasing vs copying", "Tuples & packing/unpacking", "Dictionaries", "Sets", "Comprehensions (list/dict/set)"]],
        ["Functions", ["Parameters, default & keyword args", "*args, **kwargs", "Scope: local, global, nonlocal", "Recursion", "Lambda, map, filter, zip, enumerate", "Generators & yield (basic)"]],
        ["OOP & misc", ["Classes, objects, __init__", "Instance vs class variables", "Inheritance (basic)", "Exceptions (try/except/finally)"]]
      ] },
    { id: "pd2", n: "Asymptotic Analysis, Recursion & Recurrences", f: "H", h: 7,
      d: "Find the complexity of loops (nested, logarithmic) and recursive functions. Solve recurrences with the master theorem and the recursion tree.",
      s: ["CLRS — Ch 3 (growth of functions), Ch 4.3–4.5 (recurrences, master theorem)", "NPTEL Mukund PDSA — Week 2"],
      p: [["CLRS Ch 3 & 4 exercises", "15"], ["GATE CS PYQs — time complexity & recurrences", "40"], ["GATE DA PYQs — complexity", "all"]],
      q: "Time complexity of a code snippet, the number of times a recursive function is called, or the value it returns.",
      m: ["Master theorem: T(n) = aT(n/b) + f(n); compare f(n) with n^(log_b a)", "T(n) = 2T(n/2) + n ⇒ n log n; T(n) = T(n/2) + 1 ⇒ log n; T(n) = 2T(n−1) + 1 ⇒ 2ⁿ", "Fibonacci recursion calls grow ~ φⁿ", "Loop i = i*2 runs log n times; nested i, j<i runs n²/2 times"],
      sub: [
        ["Asymptotics", ["Big-O, Ω, Θ", "Comparing growth rates", "Loop complexity"]],
        ["Recursion", ["Tracing recursive calls", "Recursion tree", "Counting calls"]],
        ["Recurrences", ["Substitution", "Recursion tree method", "Master theorem"]]
      ] },
    { id: "pd3", n: "Stacks & Queues", f: "M", h: 6,
      d: "Implement stacks and queues in Python. Trace push/pop sequences. Do infix→postfix conversion and postfix evaluation. Know circular queues and deques.",
      s: ["CLRS — Ch 10.1", "NPTEL Mukund PDSA — stacks/queues week", "Karumanchi — Stacks, Queues chapters"],
      p: [["Karumanchi Stacks & Queues problems", "25"], ["GATE CS PYQs — stack/queue", "30"]],
      q: "Output of a push/pop sequence, postfix evaluation, and queue implemented with two stacks.",
      m: ["Stack = LIFO (list.append/pop); Queue = FIFO (collections.deque)", "Postfix evaluation uses an operand stack", "Circular queue: full when (rear+1) % n == front", "A queue built from two stacks has amortized O(1) operations", "Number of valid stack permutations of n = Catalan(n)"],
      sub: [
        ["Stack", ["Stack ADT & implementation", "Infix → postfix/prefix", "Postfix evaluation", "Balanced parentheses", "Recursion uses the call stack"]],
        ["Queue", ["Queue ADT & implementation", "Circular queue", "Deque", "Priority queue (idea; heap-based)"]]
      ] },
    { id: "pd4", n: "Linked Lists", f: "M", h: 5,
      d: "Singly, doubly and circular lists: insert, delete, reverse, middle, cycle detection. Trace Python node-manipulation code.",
      s: ["CLRS — Ch 10.2", "Karumanchi — Linked Lists chapter"],
      p: [["Karumanchi Linked List problems", "20"], ["GATE CS PYQs — linked lists", "20"]],
      q: "What does this function do to the list? Complexity of operations.",
      m: ["Insert at head O(1); search O(n); delete a given node in a singly list needs the previous node", "Reverse: three pointers prev, curr, next", "Floyd's cycle detection (slow/fast pointers)", "Doubly linked list: O(1) delete when you have the node"],
      sub: [["Linked lists", ["Singly linked list operations", "Doubly linked list", "Circular list", "Reversal", "Middle & cycle detection (two pointers)"]]] },
    { id: "pd5", n: "Trees: Binary Trees, BST, Heaps", f: "H", h: 12,
      d: "Know tree properties and all traversals, including reconstructing a tree from two traversals. BST insert/delete, heap operations and build-heap. Trace tree recursion code.",
      s: ["CLRS — Ch 6 (heaps), Ch 12 (BST), Appendix B.5 (trees)", "NPTEL Mukund PDSA — trees, heaps weeks"],
      p: [["Karumanchi Trees + BST + Priority Queue problems", "40"], ["GATE CS PYQs — trees, BST, heaps", "60 (big pool)"], ["GATE DA PYQs — trees", "all"]],
      q: "Traversal orders, the BST after insertions, heap array after insert/delete, number of nodes/leaves for a height, and output of recursive tree code.",
      m: ["Binary tree of height h: max nodes 2^(h+1) − 1", "Full binary tree: leaves = internal + 1", "n nodes ⇒ n−1 edges", "Inorder of a BST is sorted", "Inorder + preorder (or postorder) uniquely determines a binary tree; pre + post does not (unless full)", "Heap: parent i, children 2i+1, 2i+2 (0-indexed)", "Build-heap O(n); insert/delete O(log n)", "Number of BSTs with n keys = Catalan(n) = C(2n,n)/(n+1)", "BST delete: replace with the inorder successor"],
      sub: [
        ["Tree basics", ["Terminology (height, depth, degree)", "Binary tree properties", "Full / complete / perfect trees", "Representation (linked, array)"]],
        ["Traversals", ["Preorder, inorder, postorder", "Level order (BFS)", "Tree reconstruction from traversals", "Expression trees"]],
        ["BST", ["Search, insert, delete", "Min/max, successor/predecessor", "Height & complexity", "Balanced BST / AVL idea"]],
        ["Heaps", ["Min/max heap property", "Insert & extract (sift-up/down)", "Build heap in O(n)", "Heapsort", "Python heapq"]]
      ] },
    { id: "pd6", n: "Hash Tables", f: "M", h: 5,
      d: "Know the collision resolution methods and trace insertions into a table. Know how the load factor affects expected probes.",
      s: ["CLRS — Ch 11.1–11.4", "NPTEL Mukund PDSA — hashing / dictionaries"],
      p: [["CLRS Ch 11 exercises", "10"], ["GATE CS PYQs — hashing", "25"]],
      q: "Final table after inserting keys with linear probing/chaining, number of probes, expected chain length.",
      m: ["Load factor α = n/m", "Chaining: expected search time O(1 + α)", "Linear probing: h(k,i) = (h(k)+i) mod m (primary clustering)", "Quadratic: h(k)+c1·i+c2·i²; double hashing: h1(k) + i·h2(k)", "Unsuccessful search, open addressing: ≤ 1/(1−α) probes", "Python dict = hash table"],
      sub: [["Hashing", ["Hash functions (division, multiplication)", "Chaining", "Open addressing: linear, quadratic, double hashing", "Load factor & performance", "Rehashing"]]] },
    { id: "pd7", n: "Searching: Linear & Binary Search", f: "M", h: 4,
      d: "Trace binary search exactly: mid computation, off-by-one errors, number of comparisons. Know variants such as first occurrence and lower bound.",
      s: ["CLRS — Ex 2.3-5 (binary search)", "NPTEL Mukund PDSA — Week 2"],
      p: [["Write binary search variants in Python", "10"], ["GATE CS/DA PYQs — searching", "all"]],
      q: "Number of comparisons, final values of low/high, and whether buggy binary search code terminates.",
      m: ["Binary search needs sorted input; O(log n); max comparisons ⌊log₂n⌋ + 1", "mid = (lo + hi) // 2", "Linear search: average (n+1)/2 comparisons for a successful search"],
      sub: [["Searching", ["Linear search", "Binary search (iterative & recursive)", "Variants: first/last occurrence, lower bound", "Comparisons count"]]] },
    { id: "pd8", n: "Basic Sorting: Selection, Bubble, Insertion", f: "H", h: 5,
      d: "Trace each pass. Count swaps and comparisons. Know best/worst cases, stability and in-place behaviour.",
      s: ["CLRS — Ch 2.1 (insertion sort), Problem 2-2 (bubble)", "NPTEL Mukund PDSA — Week 2/3"],
      p: [["Trace each sort on 5 arrays by hand", "15"], ["GATE CS/DA PYQs — sorting", "all"]],
      q: "Array after k passes, number of swaps/comparisons, and which sort is best for nearly sorted input.",
      m: ["Selection: always n(n−1)/2 comparisons, at most n−1 swaps, not stable", "Bubble: O(n) best with the early-exit flag; stable", "Insertion: O(n) best (sorted), swaps = number of inversions; stable, good for nearly sorted input", "All three are O(n²) worst case and in-place"],
      sub: [["Sorting", ["Selection sort", "Bubble sort (with flag)", "Insertion sort", "Stability & in-place", "Inversions"]]] },
    { id: "pd9", n: "Divide & Conquer: Merge Sort, Quick Sort", f: "H", h: 7,
      d: "Trace the merge procedure and partition (Lomuto/Hoare). Know recurrences for best and worst case, comparison counts, and the effect of pivot choice.",
      s: ["CLRS — Ch 2.3 (merge sort), Ch 7 (quicksort)", "NPTEL Mukund PDSA — Week 3"],
      p: [["CLRS Ch 7 exercises", "10"], ["GATE CS PYQs — merge sort / quicksort", "30"], ["GATE DA PYQs — D&C", "all"]],
      q: "Array after the first partition, worst-case input for quicksort, number of comparisons in a merge, recursion depth.",
      m: ["Merge sort: Θ(n log n) always, stable, O(n) extra space", "Merging lists of size m and n: at most m+n−1 comparisons", "Quicksort: avg O(n log n), worst O(n²) (sorted input with first/last pivot), in-place, not stable", "Worst-case recursion depth of quicksort is O(n)"],
      sub: [["Divide & conquer", ["Paradigm", "Merge sort & merge procedure", "Quicksort & partition schemes", "Pivot selection & worst case", "Recurrence analysis"]]] },
    { id: "pd10", n: "Graph Theory Basics", f: "M", h: 5,
      d: "Know definitions, the handshaking lemma, trees, bipartite graphs, representations and DAGs. Use counting formulas quickly.",
      s: ["Rosen — Discrete Maths Ch 10 Graphs (10.1–10.4), Ch 11.1 Trees", "NPTEL Mukund PDSA — graphs week"],
      p: [["Rosen Ch 10.1–10.4 exercises", "20"], ["GATE CS PYQs — graph theory", "20"]],
      q: "Number of edges/vertices given degrees, whether a graph is bipartite, number of components.",
      m: ["Σ degrees = 2|E| (handshaking)", "Tree: connected, n−1 edges, no cycles", "Complete graph Kₙ has n(n−1)/2 edges", "Bipartite ⇔ no odd cycle", "Adjacency matrix O(V²) space; list O(V+E)"],
      sub: [["Graph theory", ["Definitions (directed, undirected, weighted)", "Degree & handshaking lemma", "Paths, cycles, connectivity", "Trees & forests", "Bipartite & complete graphs", "Representations: adjacency matrix/list", "DAGs"]]] },
    { id: "pd11", n: "Graph Traversals: BFS, DFS, Topological Sort", f: "H", h: 7,
      d: "Trace BFS/DFS order with a given adjacency order. Know DFS edge classification, cycle detection, components and topological sort.",
      s: ["CLRS — Ch 22.1–22.5 (3rd ed) Elementary Graph Algorithms", "NPTEL Mukund PDSA — BFS/DFS weeks"],
      p: [["CLRS Ch 22 exercises", "10"], ["GATE CS PYQs — BFS/DFS/topological", "35"], ["GATE DA PYQs — traversals", "all"]],
      q: "Possible BFS/DFS orders (MSQ), number of topological orderings, DFS tree properties, and output of traversal code.",
      m: ["BFS uses a queue and gives shortest paths in unweighted graphs; O(V+E)", "DFS uses a stack/recursion; discovery/finish times", "Back edge in DFS ⇔ cycle (directed)", "Topological sort exists iff DAG; = decreasing finish times", "In an undirected DFS tree there are no cross edges"],
      sub: [["Traversals", ["BFS & BFS tree", "DFS, discovery/finish times", "Edge classification", "Connected components", "Cycle detection", "Topological sort (DFS & Kahn)"]]] },
    { id: "pd12", n: "Shortest Paths (Dijkstra, Bellman–Ford) & MST", f: "M", h: 7,
      d: "Trace Dijkstra's table step by step. Know why negative edges break Dijkstra, and Bellman–Ford basics. MST (Prim/Kruskal) is a bonus since 'basic graph algorithms' is broad.",
      s: ["CLRS — Ch 24.1, 24.3 (Bellman–Ford, Dijkstra), Ch 23 (MST)", "NPTEL Mukund PDSA — shortest paths week"],
      p: [["CLRS Ch 24 exercises", "8"], ["GATE CS PYQs — shortest path & MST", "30"]],
      q: "Order in which vertices are finalised, distance values after k iterations, and whether Dijkstra gives the correct answer here.",
      m: ["Dijkstra: O((V+E) log V) with a heap; fails with negative edges", "Bellman–Ford: V−1 relaxation rounds; detects negative cycles; O(VE)", "Relax: if d[u] + w < d[v] then d[v] = d[u] + w", "Unweighted graph ⇒ BFS", "MST has V−1 edges; Kruskal (sort edges + union-find), Prim (grow a tree)"],
      sub: [["Shortest paths", ["Relaxation", "Dijkstra's algorithm", "Bellman–Ford", "Floyd–Warshall (bonus)"]], ["MST (bonus)", ["Prim", "Kruskal", "Cut property"]]] }
  ]
},
/* ------------------------------------------------------------------ */
{
  id: "db", name: "DBMS & Data Warehousing", short: "DBMS", color: "#c2255c", marks: "8–12",
  why: "A scoring subject. The warehousing and preprocessing wording in the syllabus comes directly from Han & Kamber, which makes it easy to target.",
  books: [
    ["Silberschatz, Korth — Database System Concepts (6th/7th ed)", "Main book for relational model, SQL, ER, normalization and indexing."],
    ["Elmasri & Navathe — Fundamentals of Database Systems", "Best ER → relational mapping and normalization examples."],
    ["Han, Kamber & Pei — Data Mining: Concepts and Techniques (3rd ed)", "Ch 2–4 cover data types, preprocessing and warehousing. The DA syllabus wording matches this book."],
    ["GATE CS PYQs — DBMS (via GATE Overflow)", "30 years of SQL, RA, normalization and B+ tree questions."]
  ],
  topics: [
    { id: "db1", n: "ER Model & ER → Relational Mapping", f: "M", h: 5,
      d: "Know attribute and relationship types, cardinality and participation. Find the minimum number of tables when mapping.",
      s: ["Korth — Ch 6 (7th ed) / Ch 7 (6th ed) ER Model", "Navathe — Ch 3, Ch 9 (mapping)"],
      p: [["Navathe Ch 3 & 9 exercises", "10"], ["GATE CS PYQs — ER model", "15"]],
      q: "Minimum number of tables for an ER diagram. Which key does a relationship table have?",
      m: ["1:N relationship ⇒ add a foreign key on the N side (no new table)", "M:N ⇒ separate table with PK = both FKs", "1:1 with total participation ⇒ can merge", "Weak entity: key = owner key + partial key", "Multivalued attribute ⇒ separate table"],
      sub: [["ER model", ["Entities & attributes (simple, composite, multivalued, derived)", "Relationships, degree", "Cardinality & participation", "Weak entities", "Specialization/generalization", "ER → tables & minimum table count"]]] },
    { id: "db2", n: "Relational Model, Keys & Integrity Constraints", f: "M", h: 4,
      d: "Know all key types and how to count superkeys. Understand the effect of referential integrity actions such as ON DELETE CASCADE.",
      s: ["Korth — Ch 2 Intro to Relational Model, Ch 4.4 Integrity Constraints"],
      p: [["Korth Ch 2 exercises", "8"], ["GATE CS PYQs — keys / constraints", "15"]],
      q: "Number of superkeys, and which tuples are deleted by a cascade.",
      m: ["Superkey ⊇ candidate key (minimal); PK = chosen CK", "n attributes with one CK of size k ⇒ 2^(n−k) superkeys", "Entity integrity: PK not NULL", "Referential integrity: FK value must exist in the referenced PK (or be NULL)"],
      sub: [["Relational model", ["Relation, tuple, attribute, domain", "Super, candidate, primary, foreign keys", "Entity & referential integrity", "ON DELETE / UPDATE actions", "Domain & check constraints"]]] },
    { id: "db3", n: "Relational Algebra", f: "H", h: 6,
      d: "Evaluate any RA expression on small tables. Know output tuple counts for joins and division. Translate queries between RA and English.",
      s: ["Korth — Ch 2.6 (7th) / Ch 6.1 (6th) Relational Algebra", "Navathe — Ch 8"],
      p: [["Korth RA exercises", "10"], ["GATE CS PYQs — relational algebra", "25"], ["GATE DA PYQs — RA", "all"]],
      q: "What does this RA query return? Min/max number of tuples of a join.",
      m: ["σ select rows, π project columns (removes duplicates), ρ rename", "R × S has |R|·|S| tuples", "Natural join on a common attribute; with no common attribute it is a cross product", "Division R ÷ S: 'for all' queries", "Left outer join keeps all left tuples with NULLs", "|R ⋈ S| ranges from 0 to |R|·|S|"],
      sub: [["Relational algebra", ["Select, project, rename", "Union, difference, intersection", "Cartesian product", "Joins: theta, equi, natural, outer", "Division", "Query equivalence & tuple counts"]]] },
    { id: "db4", n: "Tuple Relational Calculus", f: "M", h: 3,
      d: "Read TRC expressions with ∃ and ∀ and map them to RA or SQL. Know safe expressions.",
      s: ["Korth — Ch 27 (7th, online) / Ch 6.2 (6th) Tuple Relational Calculus"],
      p: [["Korth TRC exercises", "6"], ["GATE CS PYQs — TRC", "10"]],
      q: "Which English query or RA expression is equivalent to this TRC expression?",
      m: ["{t | P(t)} form", "∀ can be rewritten as ¬∃¬", "Safe expressions produce finite results", "Safe TRC ≡ RA in expressive power"],
      sub: [["TRC", ["Syntax & free/bound variables", "Existential & universal quantifiers", "Safety", "Equivalence with RA/SQL"]]] },
    { id: "db5", n: "SQL", f: "H", h: 9,
      d: "Evaluate any query by hand on a small table. Cover GROUP BY/HAVING, nested and correlated subqueries, NULL semantics and aggregates.",
      s: ["Korth — Ch 3 Intro to SQL, Ch 4 Intermediate SQL", "SQLite/MySQL practice (run the queries yourself)"],
      p: [["Korth Ch 3 & 4 exercises", "20"], ["Write & run 50 queries on a sample DB", "50"], ["GATE CS PYQs — SQL", "30"], ["GATE DA PYQs — SQL", "all"]],
      q: "Output or row count of a SQL query with GROUP BY, HAVING, a subquery or a join.",
      m: ["Execution order: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY", "COUNT(*) counts NULL rows; COUNT(col) ignores NULLs; AVG ignores NULLs", "Comparison with NULL is UNKNOWN; WHERE keeps only TRUE", "NOT IN with a NULL in the subquery returns no rows", "UNION removes duplicates; UNION ALL keeps them", "> ALL (empty set) is TRUE; > ANY (empty set) is FALSE", "Correlated subqueries run once per outer row"],
      sub: [
        ["Basics", ["DDL (CREATE, ALTER, DROP)", "DML (INSERT, UPDATE, DELETE)", "SELECT-FROM-WHERE, DISTINCT", "ORDER BY, LIKE, BETWEEN"]],
        ["Aggregation", ["Aggregate functions", "GROUP BY", "HAVING", "NULLs in aggregates"]],
        ["Joins & sets", ["Inner/outer/natural joins in SQL", "UNION, INTERSECT, EXCEPT"]],
        ["Subqueries", ["IN / NOT IN", "EXISTS / NOT EXISTS", "ANY / ALL", "Correlated subqueries", "Views"]]
      ] },
    { id: "db6", n: "Functional Dependencies & Normalization", f: "H", h: 9,
      d: "Compute attribute closure, find all candidate keys, find the highest normal form, and check lossless join and dependency preservation. These must be exact and fast.",
      s: ["Korth — Ch 7 (7th) / Ch 8 (6th) Relational Database Design", "Navathe — Ch 14–15"],
      p: [["Korth normalization exercises", "15"], ["GATE CS PYQs — FD & normal forms", "40 (big pool)"], ["GATE DA PYQs — normalization", "all"]],
      q: "Number of candidate keys, highest normal form of R, whether a decomposition is lossless, minimal cover.",
      m: ["X⁺ closure: repeatedly add the RHS of FDs whose LHS ⊆ X", "Attributes never on any RHS must be in every key", "2NF: no partial dependency of a non-prime attribute on a key", "3NF: for X→A, X is a superkey or A is prime", "BCNF: every non-trivial X→A has X a superkey", "Lossless binary decomposition: R1∩R2 → R1 or R1∩R2 → R2", "3NF decomposition is always lossless and dependency-preserving; BCNF may lose dependencies"],
      sub: [
        ["Functional dependencies", ["FD definition", "Armstrong's axioms", "Attribute closure", "Candidate key finding", "Minimal / canonical cover", "FD equivalence"]],
        ["Normal forms", ["1NF", "2NF", "3NF", "BCNF", "Finding the highest NF"]],
        ["Decomposition", ["Lossless join test", "Dependency preservation", "3NF synthesis", "BCNF decomposition"]]
      ] },
    { id: "db7", n: "File Organization & Indexing (B / B+ trees)", f: "M", h: 7,
      d: "Calculate blocking factor, block accesses and index levels. Know B+ tree order and max/min keys, and trace insertion splits.",
      s: ["Korth — Ch 13 (7th) / Ch 10 (6th) Storage & File Structure; Ch 14 (7th) / Ch 11 (6th) Indexing"],
      p: [["Korth indexing exercises", "10"], ["GATE CS PYQs — indexing / B+ trees", "30"]],
      q: "Number of block accesses with or without an index, B+ tree order from block size, minimum/maximum height for n keys.",
      m: ["Blocking factor bfr = ⌊B / R⌋", "Primary index: sparse, on an ordered key field; clustering: ordered non-key; secondary: dense", "Multilevel index: fan-out fo = ⌊B / (key + pointer)⌋; levels = ⌈log_fo(#entries)⌉", "B+ tree internal order p: p·P + (p−1)·K ≤ B", "B+ tree: data only in leaves, leaves linked (good for range queries)"],
      sub: [
        ["File organization", ["Records & blocks, blocking factor", "Heap, sorted and hashed files", "Block access cost"]],
        ["Indexing", ["Primary, clustering, secondary indexes", "Dense vs sparse", "Multilevel indexes", "B-tree", "B+ tree: order, insertion, deletion (basic)", "Hash indexes"]]
      ] },
    { id: "db8", n: "Data Types & Data Transformation (Normalization, Discretization, Sampling, Compression)", f: "H", h: 6,
      d: "Know attribute types. Compute min-max, z-score and decimal scaling by hand. Do equal-width/equal-frequency binning and smoothing. Know sampling methods and data reduction.",
      s: ["Han, Kamber & Pei — Ch 2 (2.1–2.2 data types & statistics), Ch 3 Data Preprocessing (3.4 reduction, 3.5 transformation & discretization)"],
      p: [["Han Ch 2 exercises", "8"], ["Han Ch 3 exercises", "10"], ["GATE DA PYQs — preprocessing", "all"]],
      q: "NAT: the normalized value of x with min-max or z-score. Bin contents after smoothing. MCQ: attribute type (nominal/ordinal/interval/ratio).",
      m: ["Min-max: v' = (v−min)/(max−min)·(newMax−newMin) + newMin", "Z-score: v' = (v − mean)/σ", "Decimal scaling: v' = v/10^j, the smallest j with max|v'| < 1", "Equal-width bins: width = (max−min)/k; equal-frequency (depth) bins: same count per bin", "Smoothing by bin means / medians / boundaries", "Attribute types: nominal, binary (symmetric/asymmetric), ordinal, numeric: interval (no true zero) and ratio (true zero)", "Sampling: SRSWOR, SRSWR, cluster, stratified", "Reduction: PCA, wavelets, histograms, clustering, sampling; lossless vs lossy compression"],
      sub: [
        ["Data types", ["Nominal, binary, ordinal", "Interval & ratio", "Discrete vs continuous"]],
        ["Normalization", ["Min-max", "Z-score", "Decimal scaling"]],
        ["Discretization", ["Equal-width binning", "Equal-frequency binning", "Smoothing by means/medians/boundaries", "Histogram & entropy-based discretization", "Concept hierarchy generation"]],
        ["Sampling & compression", ["SRSWOR / SRSWR", "Stratified & cluster sampling", "Data compression (lossless vs lossy)", "Dimensionality & numerosity reduction"]]
      ] },
    { id: "db9", n: "Data Warehouse Modelling: Schemas, Cubes, Concept Hierarchies, Measures", f: "H", h: 6,
      d: "Know star, snowflake and fact constellation schemas, OLAP operations, cuboid counts and the distributive/algebraic/holistic measure classification.",
      s: ["Han, Kamber & Pei — Ch 4 Data Warehousing and OLAP (4.1–4.4), Ch 5.1 (cube computation basics)"],
      p: [["Han Ch 4 exercises", "10"], ["GATE DA PYQs — warehousing", "all"]],
      q: "Number of cuboids in a lattice. Which measure is holistic? Which OLAP operation does this describe? Star vs snowflake.",
      m: ["n dimensions with no hierarchy ⇒ 2ⁿ cuboids; with levels Lᵢ ⇒ Π(Lᵢ + 1)", "Apex cuboid = all (0-D); base cuboid = n-D", "Distributive: sum, count, min, max", "Algebraic: avg, standard deviation (computed from distributive ones)", "Holistic: median, mode, rank", "Star: a single denormalized table per dimension; snowflake: normalized dimension tables", "OLAP: roll-up (climb a hierarchy / reduce a dimension), drill-down, slice (one dimension fixed), dice (sub-cube), pivot", "OLTP vs OLAP differences"],
      sub: [
        ["Warehouse basics", ["OLTP vs OLAP", "Data warehouse vs operational DB", "ETL"]],
        ["Multidimensional model", ["Data cube & cuboids", "Fact & dimension tables", "Star schema", "Snowflake schema", "Fact constellation"]],
        ["Concept hierarchies", ["Schema hierarchies", "Set-grouping hierarchies"]],
        ["Measures & OLAP", ["Distributive, algebraic, holistic measures", "Roll-up, drill-down", "Slice, dice, pivot", "Cuboid counting"]]
      ] }
  ]
},
/* ------------------------------------------------------------------ */
{
  id: "ml", name: "Machine Learning", short: "ML", color: "#0c8599", marks: "16–22",
  why: "The heaviest subject with P&S. DA questions are numerical: compute a regression coefficient, run one k-means iteration, calculate an information gain or a Naive Bayes posterior.",
  books: [
    ["James, Witten, Hastie, Tibshirani — An Introduction to Statistical Learning (ISL/ISLP, free PDF)", "Main book. Its chapters match the syllabus terms: LOOCV, k-fold, ridge, LDA, bias-variance."],
    ["NPTEL — Introduction to Machine Learning (IIT Madras, Balaraman Ravindran)", "Weekly assignments are very close to GATE DA style."],
    ["Tom Mitchell — Machine Learning", "Ch 3 decision trees (ID3, entropy) and Ch 4 ANN/perceptron: the classic source of hand-computation questions."],
    ["Han, Kamber & Pei — Data Mining (3rd ed) Ch 8–10", "Naive Bayes, decision trees, k-means/k-medoids, hierarchical clustering (syllabus wording)."],
    ["Bishop — Pattern Recognition and Machine Learning", "Reference for Fisher LDA, SVM and NN maths (selected sections only)."]
  ],
  topics: [
    { id: "ml1", n: "ML Foundations & Evaluation Metrics", f: "M", h: 4,
      d: "Know the supervised vs unsupervised and regression vs classification setups, train/test split, loss functions, and the confusion-matrix metrics.",
      s: ["ISL — Ch 2 Statistical Learning (2.1–2.2)", "NPTEL IITM ML — Weeks 0–1"],
      p: [["ISL Ch 2 conceptual exercises", "7"], ["Compute metrics from 10 confusion matrices", "10"]],
      q: "Precision, recall or F1 from a confusion matrix. Identify the problem type.",
      m: ["Precision = TP/(TP+FP); Recall = TP/(TP+FN); F1 = 2PR/(P+R)", "Accuracy = (TP+TN)/total", "MSE = mean of squared errors", "Overfitting: low train error, high test error"],
      sub: [["Foundations", ["Supervised vs unsupervised", "Regression vs classification", "Training/validation/test sets", "Loss functions (MSE, 0-1, cross-entropy)", "Confusion matrix, precision, recall, F1, ROC (basic)"]]] },
    { id: "ml2", n: "Simple Linear Regression", f: "H", h: 5,
      d: "Compute β₀ and β₁ by hand from data. Know R², residuals, and the relation to correlation.",
      s: ["ISL — Ch 3.1 Simple Linear Regression"],
      p: [["ISL Ch 3 exercises (conceptual + applied)", "8"], ["Hand-compute regression on 10 small datasets", "10"], ["GATE DA PYQs — regression", "all"]],
      q: "NAT: slope, intercept or prediction for a small dataset. MSQ: properties of residuals.",
      m: ["β₁ = Sxy/Sxx = Σ(x−x̄)(y−ȳ)/Σ(x−x̄)²", "β₀ = ȳ − β₁x̄; the line passes through (x̄, ȳ)", "β₁ = r · sy/sx", "Residuals sum to 0", "R² = 1 − RSS/TSS = r² (simple regression)"],
      sub: [["Simple LR", ["Model & assumptions", "Least squares estimates", "Residuals & RSS", "R² and correlation", "Prediction"]]] },
    { id: "ml3", n: "Multiple Linear Regression", f: "H", h: 5,
      d: "Know the matrix form and normal equations, the hat (projection) matrix, and collinearity.",
      s: ["ISL — Ch 3.2–3.3", "Strang — Ch 4.3 (least squares, same maths)"],
      p: [["ISL Ch 3 exercises", "6"], ["GATE DA PYQs — multiple regression", "all"]],
      q: "Solve β = (XᵀX)⁻¹Xᵀy for a small X. Properties of the hat matrix. Effect of adding features on R².",
      m: ["β̂ = (XᵀX)⁻¹Xᵀy", "Hat matrix H = X(XᵀX)⁻¹Xᵀ is a projection: H² = H, trace = p (+1 with intercept)", "Adding features never decreases training R²", "Collinearity makes XᵀX near-singular"],
      sub: [["Multiple LR", ["Matrix formulation", "Normal equations", "Hat matrix", "Interpretation of coefficients", "Collinearity", "Polynomial / interaction terms (basic)"]]] },
    { id: "ml4", n: "Ridge Regression (and Lasso)", f: "M", h: 4,
      d: "Know the ridge objective and closed form, and the effect of λ on bias, variance and coefficients. Know how ridge differs from lasso.",
      s: ["ISL — Ch 6.2 Shrinkage Methods"],
      p: [["ISL Ch 6 exercises (ridge/lasso)", "6"], ["GATE DA PYQs — ridge", "all"]],
      q: "Ridge solution for a small case, the behaviour as λ→0 or ∞, MSQ on shrinkage.",
      m: ["Ridge: minimise RSS + λΣβⱼ²; β̂ = (XᵀX + λI)⁻¹Xᵀy", "λ = 0 ⇒ OLS; λ → ∞ ⇒ β → 0", "λ larger ⇒ bias increases, variance decreases", "Ridge never gives exact zeros; lasso (L1) can (feature selection)", "Standardise features before ridge"],
      sub: [["Regularization", ["Ridge objective & closed form", "Effect of λ", "Lasso (L1) comparison", "Choosing λ with CV"]]] },
    { id: "ml5", n: "Logistic Regression", f: "H", h: 5,
      d: "Know the sigmoid, log-odds, decision boundary, cross-entropy loss and its gradient. Compute a probability for a given input.",
      s: ["ISL — Ch 4.3 Logistic Regression", "Andrew Ng CS229 notes — Part II"],
      p: [["ISL Ch 4 exercises (logistic)", "6"], ["GATE DA PYQs — logistic regression", "all"]],
      q: "P(y=1|x) for a given w, b and x. Is the decision boundary linear? Gradient of the loss.",
      m: ["p = σ(wᵀx + b); log(p/(1−p)) = wᵀx + b", "Decision boundary wᵀx + b = 0 (linear)", "Loss = −[y log p + (1−y) log(1−p)]", "∂Loss/∂w = (p − y)x", "Multi-class: softmax"],
      sub: [["Logistic regression", ["Sigmoid & log-odds", "Decision boundary", "Cross-entropy / MLE", "Gradient", "Softmax (multi-class)"]]] },
    { id: "ml6", n: "k-Nearest Neighbours", f: "M", h: 4,
      d: "Classify a point by hand with k-NN using different distances. Know how k affects bias and variance, and the curse of dimensionality.",
      s: ["ISL — Ch 2.2.3, 4.7.6 KNN", "Han — Ch 9.5 (lazy learners)"],
      p: [["Hand-run k-NN on 10 small datasets", "10"], ["GATE DA PYQs — kNN", "all"]],
      q: "Predicted class for k = 1, 3, 5. Training error of 1-NN. Effect of k.",
      m: ["Euclidean, Manhattan, Minkowski-p, cosine distances", "1-NN has 0 training error (no duplicate points) and high variance", "Larger k ⇒ smoother boundary, more bias, less variance", "Scale features before k-NN", "k-NN is non-parametric and lazy (no training)"],
      sub: [["k-NN", ["Algorithm", "Distance metrics", "Choice of k & bias-variance", "Feature scaling", "k-NN regression", "Curse of dimensionality"]]] },
    { id: "ml7", n: "Naive Bayes Classifier", f: "H", h: 5,
      d: "Compute the posterior from a frequency table, with and without Laplace smoothing. Know the Gaussian NB variant.",
      s: ["Han — Ch 8.3 Bayes Classification", "Mitchell — Ch 6.9–6.10", "ISL — Ch 4.4.4"],
      p: [["Han Ch 8 exercises (NB)", "5"], ["Hand-compute NB on 10 tables", "10"], ["GATE DA PYQs — Naive Bayes", "all"]],
      q: "Predicted class and posterior probability for a new sample. The effect of a zero count.",
      m: ["P(C|x) ∝ P(C) Π P(xᵢ|C)", "Assumes conditional independence of features given the class", "Laplace smoothing: (count + 1)/(N_c + k), k = number of values of the feature", "Gaussian NB: each P(xᵢ|C) is normal", "NB is a generative model"],
      sub: [["Naive Bayes", ["Bayes rule for classification", "Conditional independence assumption", "Categorical NB from tables", "Laplace smoothing", "Gaussian NB", "Generative vs discriminative"]]] },
    { id: "ml8", n: "Linear Discriminant Analysis (LDA)", f: "M", h: 4,
      d: "Know Gaussian class-conditionals with a shared covariance and a linear boundary. Know the Fisher direction w ∝ Σ⁻¹(μ₁ − μ₀). Compare with QDA.",
      s: ["ISL — Ch 4.4 Generative Models (LDA, QDA)", "Bishop — Ch 4.1.4 Fisher's discriminant"],
      p: [["ISL Ch 4 exercises (LDA/QDA)", "6"], ["GATE DA PYQs — LDA", "all"]],
      q: "Fisher direction for given means and covariance, LDA vs QDA boundary shape, number of parameters.",
      m: ["LDA: shared Σ ⇒ linear boundary; QDA: separate Σ ⇒ quadratic", "Fisher: maximise between-class / within-class scatter; w ∝ S_w⁻¹(μ₁ − μ₀)", "LDA is a generative model (like NB)", "With C classes, LDA projects to at most C−1 dimensions"],
      sub: [["LDA", ["Generative Gaussian model", "Linear decision boundary", "Fisher's criterion & direction", "QDA comparison", "LDA for dimensionality reduction"]]] },
    { id: "ml9", n: "Support Vector Machines", f: "H", h: 6,
      d: "Know the margin geometry, support vectors, hard vs soft margin, the C parameter, hinge loss and kernels. Compute the margin for a given w.",
      s: ["ISL — Ch 9 Support Vector Machines", "Bishop — Ch 7.1 (reference)", "NPTEL IITM ML — SVM week"],
      p: [["ISL Ch 9 exercises", "8"], ["GATE DA PYQs — SVM", "all"]],
      q: "Margin width, which points are support vectors, effect of C, and whether a kernel is valid.",
      m: ["Decision: sign(wᵀx + b); margin width = 2/‖w‖", "Hard margin: minimise ½‖w‖² s.t. yᵢ(wᵀxᵢ + b) ≥ 1", "Support vectors lie on or inside the margin; only they determine w", "Soft margin: large C ⇒ fewer violations (low bias, high variance)", "Hinge loss = max(0, 1 − y·f(x))", "Kernels: polynomial (1 + xᵀz)^d, RBF exp(−γ‖x−z‖²); a valid kernel ⇔ PSD Gram matrix"],
      sub: [["SVM", ["Maximal margin classifier", "Support vectors", "Soft margin & C", "Hinge loss", "Kernel trick (poly, RBF)", "Dual form (basic idea)"]]] },
    { id: "ml10", n: "Decision Trees", f: "H", h: 6,
      d: "Compute entropy, information gain and the Gini index by hand, and choose the root split. Know pruning and overfitting.",
      s: ["Mitchell — Ch 3 Decision Tree Learning", "Han — Ch 8.2", "ISL — Ch 8.1"],
      p: [["Mitchell Ch 3 exercises", "5"], ["Han Ch 8 exercises (trees)", "5"], ["Hand-compute IG/Gini on 10 datasets", "10"], ["GATE DA PYQs — decision trees", "all"]],
      q: "NAT: entropy or information gain of a split. MCQ: which attribute is chosen at the root. Maximum depth.",
      m: ["Entropy H = −Σ pᵢ log₂ pᵢ; max = log₂ k (1 bit for 2 balanced classes)", "IG = H(parent) − Σ (nᵢ/n) H(childᵢ)", "Gini = 1 − Σ pᵢ²; max for 2 classes = 0.5", "Gain ratio = IG / SplitInfo (C4.5)", "Deeper tree ⇒ lower bias, higher variance", "Regression trees minimise RSS"],
      sub: [["Decision trees", ["Tree structure", "Entropy & information gain (ID3)", "Gini index (CART)", "Gain ratio (C4.5)", "Continuous attribute splits", "Pruning & overfitting", "Regression trees", "Bagging/Random forest (bonus)"]]] },
    { id: "ml11", n: "Bias–Variance Trade-off", f: "M", h: 3,
      d: "Know the decomposition, how bias and variance behave with model complexity, and how every model's hyperparameter moves along the curve.",
      s: ["ISL — Ch 2.2.2 The Bias-Variance Trade-Off"],
      p: [["ISL Ch 2 conceptual exercises", "4"], ["GATE DA PYQs — bias-variance", "all"]],
      q: "MSQ: which change increases bias or variance (k in k-NN, λ in ridge, tree depth, C in SVM).",
      m: ["E[(y − f̂)²] = Bias² + Variance + irreducible noise", "Complex model ⇒ low bias, high variance", "k-NN: small k ⇒ high variance; ridge: large λ ⇒ high bias", "More training data reduces variance"],
      sub: [["Bias–variance", ["Decomposition", "Under/overfitting", "Model complexity curves", "Effect of hyperparameters"]]] },
    { id: "ml12", n: "Cross-Validation: Validation Set, LOOCV, k-Fold", f: "M", h: 3,
      d: "Know the procedures, the number of model fits, cost, and the bias/variance of the error estimates.",
      s: ["ISL — Ch 5.1 Cross-Validation"],
      p: [["ISL Ch 5 exercises", "5"], ["GATE DA PYQs — cross-validation", "all"]],
      q: "How many models are trained? Which CV estimate has lower bias or higher variance? Compute the CV error from fold errors.",
      m: ["LOOCV: n fits; nearly unbiased but high variance; deterministic", "k-fold: k fits; k = 5 or 10 is a good bias-variance balance", "CV error = average of the fold errors", "Stratified k-fold keeps class proportions", "Never tune on the test set"],
      sub: [["Cross-validation", ["Validation set approach", "LOOCV", "k-fold CV", "Bias/variance of CV estimates", "Model selection with CV"]]] },
    { id: "ml13", n: "Neural Networks: Perceptron, MLP, Feed-Forward, Backprop", f: "H", h: 8,
      d: "Know the perceptron update rule and its limits (XOR). Compute a forward pass, count parameters, and know activation functions and their derivatives. Do one backprop step for a tiny network.",
      s: ["Mitchell — Ch 4 Artificial Neural Networks", "ISL — Ch 10.1–10.2, 10.7", "3Blue1Brown — Neural Networks series"],
      p: [["Mitchell Ch 4 exercises", "5"], ["Hand-compute forward pass + param count on 10 nets", "10"], ["GATE DA PYQs — neural networks", "all"]],
      q: "NAT: network output for a given input and weights, number of parameters, perceptron weights after an update. MSQ on activations and XOR.",
      m: ["Perceptron: w ← w + η(y − ŷ)x; converges iff the data is linearly separable", "A single perceptron cannot learn XOR; one hidden layer can", "Parameters in a dense layer = (inputs × outputs) + outputs (bias)", "ReLU(x) = max(0,x), derivative 0 or 1; sigmoid' = σ(1−σ)", "Without non-linear activations, stacked layers are still a linear model", "Backprop = chain rule applied layer by layer"],
      sub: [
        ["Perceptron", ["Model", "Learning rule", "Linear separability & XOR"]],
        ["MLP / feed-forward", ["Architecture & layers", "Activation functions", "Forward pass computation", "Parameter counting", "Universal approximation (idea)"]],
        ["Training", ["Loss functions", "Backpropagation", "Gradient descent / SGD", "Vanishing gradients (basic)"]]
      ] },
    { id: "ml14", n: "Clustering: k-Means, k-Medoids, Hierarchical (single/complete/average linkage)", f: "H", h: 7,
      d: "Run k-means iterations by hand. Know the difference between k-medoids and k-means. Build a dendrogram with single and complete linkage from a distance matrix. Know top-down vs bottom-up.",
      s: ["Han — Ch 10.2 (k-means, k-medoids), 10.3 (hierarchical)", "ISL — Ch 12.4 Clustering Methods"],
      p: [["Han Ch 10 exercises", "8"], ["ISL Ch 12 exercises (clustering)", "5"], ["Hand-run k-means / linkage on 10 datasets", "10"], ["GATE DA PYQs — clustering", "all"]],
      q: "Centroids after one iteration, cluster assignment, merge order and heights with single/complete linkage, number of clusters at a cut.",
      m: ["k-means: assign to the nearest centroid → recompute the mean; minimises the within-cluster SSE; converges to a local optimum", "k-medoids: centres are actual data points; robust to outliers (PAM)", "Single linkage = min distance (chaining); complete = max; average = mean; centroid linkage", "Agglomerative = bottom-up (n−1 merges); divisive = top-down", "k-means is sensitive to initialisation and scale"],
      sub: [
        ["Partitioning", ["k-means algorithm", "Objective (SSE) & convergence", "Initialisation (k-means++ idea)", "k-medoids / PAM", "Choosing k (elbow)"]],
        ["Hierarchical", ["Agglomerative (bottom-up)", "Divisive (top-down)", "Single linkage", "Complete linkage", "Average & centroid linkage", "Dendrograms & cutting"]]
      ] },
    { id: "ml15", n: "Dimensionality Reduction: PCA", f: "H", h: 6,
      d: "Compute the covariance matrix, eigenvectors and principal components of 2-D data by hand. Know variance explained and the SVD connection.",
      s: ["ISL — Ch 12.2 Principal Components Analysis", "Strang — Ch 7.3 (PCA via SVD)", "Han — Ch 3.4.3"],
      p: [["ISL Ch 12 exercises (PCA)", "5"], ["Hand-compute PCA on 8 small 2-D datasets", "8"], ["GATE DA PYQs — PCA", "all"]],
      q: "First principal component direction, proportion of variance explained, projection of a point, and the number of components for 95% variance.",
      m: ["Centre the data (and standardise if scales differ)", "PCs = eigenvectors of the covariance matrix, sorted by eigenvalue", "Variance explained by PCᵢ = λᵢ / Σλ", "PCs are orthogonal; PC1 maximises variance", "Via SVD of the centred X: PCs = columns of V; λᵢ = σᵢ²/(n−1)", "PCA is unsupervised and linear"],
      sub: [["PCA", ["Curse of dimensionality", "Covariance matrix", "Eigen decomposition for PCA", "Variance explained & scree plot", "Projection & reconstruction", "PCA via SVD"]]] }
  ]
},
/* ------------------------------------------------------------------ */
{
  id: "ai", name: "Artificial Intelligence", short: "AI", color: "#f08c00", marks: "8–12",
  why: "The syllabus follows Russell & Norvig (AIMA) closely. Hand-traced search, alpha-beta, logic and Bayes-net questions give reliable marks once practised.",
  books: [
    ["Russell & Norvig — AIMA (3rd ed; 4th ed chapter numbers in brackets)", "Main book. 'Variable elimination' and 'approximate inference through sampling' come from AIMA Ch 14 (3rd) / Ch 13 (4th)."],
    ["UC Berkeley CS188 — past exams & section worksheets (free)", "Very close in style: A*, alpha-beta, Bayes nets, variable elimination, sampling."],
    ["NPTEL — An Introduction to Artificial Intelligence (Mausam, IIT Delhi)", "Lectures and assignments aligned to AIMA."],
    ["Rosen — Discrete Maths Ch 1 (logic)", "Propositional and predicate logic practice. GATE CS PYQs on logic are also useful."]
  ],
  topics: [
    { id: "ai1", n: "Search Foundations (problem formulation, tree vs graph search)", f: "M", h: 3,
      d: "Know states, actions, goal test and path cost, the four evaluation criteria, and tree search vs graph search (explored set).",
      s: ["AIMA — Ch 3.1–3.3 [4th: 3.1–3.3]"],
      p: [["AIMA Ch 3 exercises (formulation)", "5"]],
      q: "Conceptual MCQ, usually combined with algorithm questions.",
      m: ["Criteria: completeness, optimality, time, space", "b = branching factor, d = depth of the shallowest goal, m = max depth", "Graph search avoids repeated states"],
      sub: [["Foundations", ["State space formulation", "Tree search vs graph search", "Frontier & explored set", "Evaluation criteria"]]] },
    { id: "ai2", n: "Uninformed Search: BFS, DFS, UCS, DLS, IDDFS, Bidirectional", f: "H", h: 5,
      d: "Trace node expansion order on a graph, including tie-breaking. Know complexity, completeness and optimality for each algorithm.",
      s: ["AIMA — Ch 3.4 [4th: 3.4]", "CS188 — Lecture 2 & Section 1"],
      p: [["AIMA Ch 3 exercises (uninformed)", "8"], ["CS188 past exam search questions", "10"], ["GATE DA PYQs — uninformed search", "all"]],
      q: "Order of expanded nodes, which algorithm returns which path, number of nodes generated.",
      m: ["BFS: complete, optimal for unit costs, O(b^d) time and space", "DFS: not complete (infinite spaces), not optimal, O(bm) space", "UCS: expands the lowest g(n); optimal for positive costs", "IDDFS: complete and optimal (unit costs), O(bd) space, O(b^d) time", "Bidirectional: O(b^(d/2))"],
      sub: [["Uninformed search", ["Breadth-first search", "Depth-first search", "Uniform-cost search", "Depth-limited search", "Iterative deepening DFS", "Bidirectional search", "Comparison table"]]] },
    { id: "ai3", n: "Informed Search: Greedy, A*, Heuristics", f: "H", h: 6,
      d: "Trace A* with f = g + h. Check whether a heuristic is admissible or consistent. Know the optimality conditions for tree vs graph search, and dominance.",
      s: ["AIMA — Ch 3.5–3.6 [4th: 3.5–3.6]", "CS188 — Lecture 3 & Section 2"],
      p: [["AIMA Ch 3 exercises (A*, heuristics)", "8"], ["CS188 past exam A* / heuristic questions", "12"], ["GATE DA PYQs — informed search", "all"]],
      q: "Expansion order and path from A*/greedy. MSQ: which heuristics are admissible/consistent. Is h1 + h2 or max(h1,h2) admissible?",
      m: ["Admissible: h(n) ≤ true cost h*(n)", "Consistent: h(n) ≤ c(n,n') + h(n'); consistent ⇒ admissible", "A* tree search is optimal with admissible h; graph search needs consistent h", "max(h1, h2) of admissible heuristics is admissible and dominates both", "h = 0 ⇒ A* becomes UCS; greedy uses only h (not optimal)"],
      sub: [["Informed search", ["Heuristic functions", "Greedy best-first", "A* search", "Admissibility & consistency", "Dominance & relaxed problems", "IDA* / local search, hill climbing (bonus)"]]] },
    { id: "ai4", n: "Adversarial Search: Minimax, Alpha-Beta, Expectimax", f: "H", h: 5,
      d: "Compute the minimax value of a tree. Mark every node pruned by alpha-beta (left-to-right order). Know the best-case ordering complexity and expectimax.",
      s: ["AIMA — Ch 5.1–5.3, 5.5 [4th: 5.1–5.3, 5.5]", "CS188 — Games lecture & Section 3"],
      p: [["AIMA Ch 5 exercises", "6"], ["CS188 past exam game-tree questions", "12"], ["GATE DA PYQs — adversarial search", "all"]],
      q: "Root value, number of leaves evaluated, which branches are pruned, and the value needed at a leaf for no pruning.",
      m: ["MAX takes the max of its children, MIN the min", "α = best for MAX so far, β = best for MIN so far; prune when α ≥ β", "Alpha-beta does not change the root value", "Perfect ordering: O(b^(m/2)); random ≈ O(b^(3m/4))", "Expectimax: chance nodes take the probability-weighted average (no pruning in general)"],
      sub: [["Adversarial search", ["Game trees", "Minimax", "Alpha-beta pruning", "Move ordering", "Expectimax / chance nodes", "Depth-limited search & evaluation functions"]]] },
    { id: "ai5", n: "Propositional Logic", f: "H", h: 6,
      d: "Check validity and satisfiability, decide entailment, convert to CNF and run resolution. Know Horn clauses and forward/backward chaining.",
      s: ["AIMA — Ch 7.3–7.6 [4th: 7.3–7.6]", "Rosen — Ch 1.1–1.3"],
      p: [["AIMA Ch 7 exercises", "10"], ["Rosen Ch 1.2–1.3 exercises", "15"], ["GATE CS/DA PYQs — propositional logic", "all"]],
      q: "Is a formula valid, satisfiable or a contradiction? Does KB ⊨ α? Number of models. Resolution steps.",
      m: ["p → q ≡ ¬p ∨ q; contrapositive ¬q → ¬p is equivalent", "KB ⊨ α iff KB ∧ ¬α is unsatisfiable", "Valid: true in all models; satisfiable: true in at least one", "De Morgan's laws; distribution for CNF", "Resolution is refutation-complete", "Horn clauses: forward/backward chaining in linear time"],
      sub: [["Propositional logic", ["Syntax & semantics", "Truth tables & models", "Validity, satisfiability, entailment", "Logical equivalences", "CNF conversion", "Resolution", "Horn clauses, forward/backward chaining"]]] },
    { id: "ai6", n: "Predicate (First-Order) Logic", f: "H", h: 6,
      d: "Translate English to FOL and back, including quantifier order and negation. Know unification, Skolemization and FOL resolution basics.",
      s: ["AIMA — Ch 8 FOL (8.1–8.3), Ch 9 Inference (9.1–9.2, 9.5) [4th: Ch 8, 9]", "Rosen — Ch 1.4–1.5"],
      p: [["AIMA Ch 8 exercises (translation)", "10"], ["Rosen Ch 1.4–1.5 exercises", "15"], ["GATE CS/DA PYQs — predicate logic", "all"]],
      q: "Which FOL formula represents this sentence? Negation of a quantified statement. Is ∀x∃y ≡ ∃y∀x? Most general unifier.",
      m: ["'All A are B': ∀x (A(x) → B(x)); 'Some A are B': ∃x (A(x) ∧ B(x))", "¬∀x P ≡ ∃x ¬P; ¬∃x P ≡ ∀x ¬P", "∃y∀x P ⇒ ∀x∃y P (not the reverse)", "∀ distributes over ∧; ∃ distributes over ∨", "Skolemization replaces ∃ with functions/constants", "Unification finds the most general unifier (MGU)"],
      sub: [["First-order logic", ["Syntax: predicates, functions, quantifiers", "English ↔ FOL translation", "Quantifier negation & order", "Equivalences", "Unification", "Skolemization & CNF", "FOL resolution (basic)"]]] },
    { id: "ai7", n: "Uncertainty: Conditional Independence & Bayesian Networks", f: "H", h: 7,
      d: "Factorise a joint distribution with a Bayes net. Count parameters. Decide conditional independence with d-separation. Compute a joint probability entry.",
      s: ["AIMA — Ch 13 (probability review), Ch 14.1–14.2 [4th: Ch 12, 13.1–13.2]", "CS188 — Bayes Nets lectures & sections"],
      p: [["AIMA Ch 14 exercises (representation)", "8"], ["CS188 past exam Bayes net independence questions", "12"], ["GATE DA PYQs — Bayes nets", "all"]],
      q: "P(x1,…,xn) from CPTs, the number of parameters, whether X ⊥ Y | Z (MSQ), Markov blanket.",
      m: ["P(X1..Xn) = Π P(Xi | Parents(Xi))", "Parameters for a Boolean node with k Boolean parents = 2^k", "Chain X→Y→Z and fork X←Y→Z: X ⊥ Z | Y", "Collider X→Y←Z: X ⊥ Z, but NOT given Y (or a descendant of Y)", "Markov blanket = parents + children + children's other parents", "X ⊥ Y | Z ⇔ P(X|Y,Z) = P(X|Z)"],
      sub: [["Bayes nets", ["Probability review & independence", "Conditional independence", "Bayes net semantics & factorization", "Parameter counting", "D-separation (chain, fork, collider)", "Markov blanket"]]] },
    { id: "ai8", n: "Exact Inference: Enumeration & Variable Elimination", f: "M", h: 5,
      d: "Compute P(query | evidence) by enumeration. Run variable elimination with factors: join, sum out, normalise. Understand how elimination order affects factor size.",
      s: ["AIMA — Ch 14.4 [4th: 13.3]", "CS188 — Variable Elimination lecture & section"],
      p: [["AIMA Ch 14 exercises (inference)", "5"], ["CS188 past exam VE questions", "10"], ["GATE DA PYQs — variable elimination", "all"]],
      q: "Numerical posterior query on a small net, the factor produced when eliminating X, and the size of the largest factor for a given order.",
      m: ["P(Q|e) = α Σ_hidden P(Q, e, hidden)", "VE: join all factors containing X, sum out X, repeat, then normalise", "Order matters: the complexity is set by the largest intermediate factor", "Exact inference is NP-hard in general; linear for polytrees"],
      sub: [["Exact inference", ["Inference by enumeration", "Factors & factor operations", "Variable elimination algorithm", "Elimination ordering", "Complexity (polytrees)"]]] },
    { id: "ai9", n: "Approximate Inference: Sampling (Prior, Rejection, Likelihood Weighting, Gibbs)", f: "M", h: 5,
      d: "Know each sampling method, compute an estimate from given samples, and compute likelihood weights. Know Gibbs sampling steps.",
      s: ["AIMA — Ch 14.5 [4th: 13.4]", "CS188 — Sampling lecture & section"],
      p: [["AIMA Ch 14 exercises (sampling)", "4"], ["CS188 past exam sampling questions", "10"], ["GATE DA PYQs — sampling", "all"]],
      q: "Estimate P(Q|e) from a set of samples, the weight of a sample in likelihood weighting, and which samples rejection sampling discards.",
      m: ["Prior sampling: sample each variable in topological order from its CPT", "Rejection: discard samples inconsistent with the evidence (wasteful when evidence is rare)", "Likelihood weighting: fix the evidence; weight = Π P(eᵢ | parents)", "Gibbs: resample one non-evidence variable at a time given its Markov blanket (MCMC)", "The estimate = weighted count normalised"],
      sub: [["Sampling", ["Prior (direct) sampling", "Rejection sampling", "Likelihood weighting", "Gibbs sampling / MCMC", "Consistency of estimates"]]] }
  ]
},
/* ------------------------------------------------------------------ */
{
  id: "ga", name: "General Aptitude", short: "GA", color: "#5c940d", marks: "15",
  why: "15 marks at the level of a school exam. Toppers lose very few marks here. 30 minutes daily keeps it sharp.",
  books: [
    ["GATE GA PYQs of ALL papers (2010–2026)", "GA is common across branches, which gives thousands of real questions. This is the best source."],
    ["R.S. Aggarwal — Quantitative Aptitude", "Percentages, ratio, time & work, speed."],
    ["R.S. Aggarwal — A Modern Approach to Verbal & Non-Verbal Reasoning", "Series, coding, syllogisms, paper folding, mirror images."],
    ["Wren & Martin — High School English Grammar", "Articles, prepositions, tenses, subject-verb agreement."]
  ],
  topics: [
    { id: "ga1", n: "Verbal Aptitude", f: "H", h: 8,
      d: "Grammar (articles, prepositions, tenses, agreement), vocabulary in context, analogies, sentence ordering and short passages.",
      s: ["Wren & Martin — articles, prepositions, tenses, agreement", "GATE GA PYQs (verbal)"],
      p: [["GATE GA PYQs — verbal (all papers)", "150"]],
      q: "Fill in the blank, correct/incorrect sentence, word meaning, analogy, and 1–2 short reading-comprehension passages.",
      m: ["Read all options before choosing; eliminate", "Subject–verb agreement with 'either/or', 'each', 'none'"],
      sub: [["Verbal", ["Grammar & usage", "Vocabulary & analogies", "Sentence completion", "Reading comprehension", "Sentence ordering / inference"]]] },
    { id: "ga2", n: "Quantitative Aptitude", f: "H", h: 10,
      d: "Percentages, ratio, averages, time–work, speed, simple probability, mensuration and data interpretation (tables and charts).",
      s: ["R.S. Aggarwal Quant — selected chapters", "GATE GA PYQs (quant)"],
      p: [["GATE GA PYQs — quantitative (all papers)", "200"]],
      q: "NAT/MCQ on percentages, profit/loss, work, speed, mixtures and data interpretation.",
      m: ["Successive % change: a + b + ab/100", "Work: rates add (1/a + 1/b)", "Average speed for equal distances = 2xy/(x+y)"],
      sub: [["Quant", ["Percentages, profit/loss", "Ratio, proportion, mixtures", "Averages", "Time–work, speed–distance", "Numbers, powers, logs", "Mensuration & geometry basics", "Data interpretation"]]] },
    { id: "ga3", n: "Analytical & Spatial Aptitude", f: "H", h: 8,
      d: "Logical deduction, arrangements, series, coding, and spatial questions (paper folding, rotation, mirror images, counting figures).",
      s: ["R.S. Aggarwal Reasoning — selected chapters", "GATE GA PYQs (analytical/spatial)"],
      p: [["GATE GA PYQs — analytical & spatial (all papers)", "150"]],
      q: "Seating arrangements, conclusions from statements, next figure/number, paper folding, cube faces.",
      m: ["Draw a diagram for every arrangement puzzle", "Opposite faces of a cube: check the unfolded net carefully"],
      sub: [["Analytical", ["Deduction & syllogisms", "Arrangements & puzzles", "Number/letter series", "Coding–decoding"]], ["Spatial", ["Paper folding/cutting", "Rotation & mirror images", "Counting figures", "Cube & dice"]]] }
  ]
}
];

/* ---------------------------------------------------------------------
   MASTER SCHEDULE: two parallel tracks (A = maths/ML, B = CS/AI)
   Sunday = weekly test + revision + backlog (no new topic).
   GA runs daily for 30 minutes on both tracks.
   ------------------------------------------------------------------- */
const SCHEDULE = {
  start: "2026-09-28",
  syllabusEnd: "2026-12-31",
  mockStart: "2027-01-01",
  segments: [
    { track: "A", subj: "la", from: "2026-09-28", to: "2026-10-18" },
    { track: "A", subj: "co", from: "2026-10-19", to: "2026-11-01" },
    { track: "A", subj: "ps", from: "2026-11-02", to: "2026-11-29" },
    { track: "A", subj: "ml", from: "2026-11-30", to: "2026-12-20", topics: ["ml1","ml2","ml3","ml4","ml5","ml6","ml7","ml8","ml9","ml10","ml11","ml12"] },
    { track: "B", subj: "pd", from: "2026-09-28", to: "2026-10-25" },
    { track: "B", subj: "db", from: "2026-10-26", to: "2026-11-15" },
    { track: "B", subj: "ai", from: "2026-11-16", to: "2026-12-06" },
    { track: "B", subj: "ml", from: "2026-12-07", to: "2026-12-20", topics: ["ml13","ml14","ml15"] }
  ],
  special: [
    { from: "2026-12-21", to: "2026-12-31", title: "PYQ marathon + short-notes consolidation",
      detail: "Solve ALL GATE DA PYQs (2024–2026 + sample papers) subject-wise in timed sets. Finish each subject's short notes. Take 2 full-syllabus tests on Dec 27 and Dec 31. Clear the tough-topic queue." }
  ],
  gaRotation: ["GA PYQ mixed set (30 Qs, timed)", "Verbal: grammar + vocabulary", "Quant: arithmetic", "Analytical: puzzles & series", "Spatial: folding, rotation, figures", "Quant: data interpretation", "Verbal: reading comprehension + analogies"]
};

const MOCK_PLAN = [
  { date: "2027-01-02", name: "Full Mock 1 (baseline)", type: "Full" },
  { date: "2027-01-04", name: "Subject test: P&S + LA", type: "Subject" },
  { date: "2027-01-06", name: "Subject test: PDSA + DBMS", type: "Subject" },
  { date: "2027-01-08", name: "Full Mock 2", type: "Full" },
  { date: "2027-01-10", name: "Subject test: ML + AI", type: "Subject" },
  { date: "2027-01-12", name: "Full Mock 3", type: "Full" },
  { date: "2027-01-14", name: "Full Mock 4", type: "Full" },
  { date: "2027-01-16", name: "Full Mock 5", type: "Full" },
  { date: "2027-01-18", name: "Full Mock 6", type: "Full" },
  { date: "2027-01-20", name: "Full Mock 7 (GATE time slot)", type: "Full" },
  { date: "2027-01-22", name: "Full Mock 8", type: "Full" },
  { date: "2027-01-24", name: "Full Mock 9", type: "Full" },
  { date: "2027-01-26", name: "Full Mock 10", type: "Full" },
  { date: "2027-01-28", name: "Full Mock 11 (GATE time slot)", type: "Full" },
  { date: "2027-01-30", name: "Full Mock 12", type: "Full" },
  { date: "2027-02-01", name: "Actual GATE DA 2024 paper (timed)", type: "PYQ" },
  { date: "2027-02-02", name: "Actual GATE DA 2025 paper (timed)", type: "PYQ" },
  { date: "2027-02-03", name: "Actual GATE DA 2026 paper (timed)", type: "PYQ" }
];

const MISTAKE_TYPES = ["Concept gap", "Formula forgotten", "Calculation error", "Misread question", "Silly mistake", "Time pressure", "Guessed wrong", "Topic not studied"];
