/* Practice question bank: GATE-relevant exercises only, as references (chapter, number, PDF page) plus tags.
   Question text stays in the book; open your own PDF at the page shown.
   Fields: c chapter, s section (P = Problems, TE = Theoretical Exercises, ST = Self-Test),
   n number, p PDF page (page number in your PDF viewer), l level (E/M/H), g GATE rating
   (3 GATE-likely, 2 good practice), k pattern, t short label (our words),
   x starred as harder in the book, a PDF page of the answer, o PDF page of the full solution. */
const PRACTICE_PATTERNS = {"cnt_arr": {"tid": "ps1", "label": "Arrangements with restrictions (counting NAT)"}, "cnt_sel": {"tid": "ps1", "label": "Selections / committees (counting NAT)"}, "cnt_multi": {"tid": "ps1", "label": "Identical objects, multinomial, lattice paths"}, "cnt_stars": {"tid": "ps1", "label": "Integer solutions / stars & bars"}, "cnt_id": {"tid": "ps1", "label": "Combinatorial identity (proof)"}, "ie": {"tid": "ps2", "label": "Inclusion–exclusion, at-least-one"}, "sample": {"tid": "ps2", "label": "Sample spaces & events"}, "events": {"tid": "ps2", "label": "Event algebra"}, "axioms": {"tid": "ps2", "label": "Axioms: P(A∪B), mutually exclusive"}, "prob_classic": {"tid": "ps2", "label": "Classical probability: cards, dice, urns"}, "cond": {"tid": "ps3", "label": "Conditional probability"}, "bayes": {"tid": "ps3", "label": "Bayes / total probability NAT"}, "total": {"tid": "ps3", "label": "Law of total probability"}, "indep": {"tid": "ps2", "label": "Independence, reliability, repeated trials"}, "condind": {"tid": "ps3", "label": "Conditional independence"}, "rv_disc": {"tid": "ps4", "label": "Discrete RV: PMF"}, "cdf": {"tid": "ps4", "label": "CDF ↔ PMF/PDF"}, "exp_var": {"tid": "ps4", "label": "Expectation & variance"}, "lin_exp": {"tid": "ps4", "label": "Linearity of expectation (indicators)"}, "cov": {"tid": "ps4", "label": "Covariance, correlation, Var of sums"}, "binom": {"tid": "ps5", "label": "Binomial distribution"}, "pois": {"tid": "ps5", "label": "Poisson distribution / approximation"}, "geom": {"tid": "ps5", "label": "Geometric distribution"}, "negbin": {"tid": "ps5", "label": "Negative binomial"}, "hyper": {"tid": "ps5", "label": "Hypergeometric"}, "cont_pdf": {"tid": "ps6", "label": "Continuous RV: PDF, constant, probabilities"}, "unif": {"tid": "ps6", "label": "Uniform distribution"}, "expo": {"tid": "ps6", "label": "Exponential, memoryless"}, "normal": {"tid": "ps6", "label": "Normal distribution, Z-table"}, "normal_approx": {"tid": "ps8", "label": "Normal approximation to binomial"}, "transform": {"tid": "ps6", "label": "Function of a random variable"}, "hazard": {"tid": "ps6", "label": "Hazard rate (beyond syllabus)"}, "gamma": {"tid": "ps6", "label": "Gamma distribution (support)"}, "beta": {"tid": "ps6", "label": "Beta distribution (beyond syllabus)"}, "joint": {"tid": "ps7", "label": "Joint distributions & marginals"}, "indep_rv": {"tid": "ps7", "label": "Independence of random variables"}, "cond_dist": {"tid": "ps7", "label": "Conditional PMF / PDF"}, "cond_exp": {"tid": "ps7", "label": "Conditional expectation & variance"}, "sumrv": {"tid": "ps7", "label": "Sums of independent RVs"}, "order": {"tid": "ps7", "label": "Order statistics, min/max"}, "transform2": {"tid": "ps7", "label": "Joint transformations (beyond syllabus)"}, "mgf": {"tid": "ps4", "label": "Moment generating functions (support)"}, "clt": {"tid": "ps8", "label": "Central limit theorem"}, "ineq": {"tid": "ps8", "label": "Markov / Chebyshev inequalities"}, "entropy": {"tid": "ml10", "label": "Entropy (used in decision trees)"}, "markov": {"tid": "ps2", "label": "Markov chains (not in DA syllabus)"}, "poisson_proc": {"tid": "ps5", "label": "Poisson process (beyond syllabus)"}, "lorenz": {"tid": "ps8", "label": "Lorenz curve (beyond syllabus)"}, "proof": {"tid": "ps2", "label": "Proof / theory"}, "desc": {"tid": "ps4", "label": "Descriptive statistics: mean, median, SD, percentiles, correlation"}, "sampling": {"tid": "ps8", "label": "Sampling distribution of the mean / proportion"}, "ci": {"tid": "ps9", "label": "Confidence intervals"}, "mle": {"tid": "ps9", "label": "Point estimation / MLE"}, "htest": {"tid": "ps10", "label": "Hypothesis tests (z, t, p-value)"}, "chisq": {"tid": "ps10", "label": "Chi-square goodness of fit / independence"}, "tchi": {"tid": "ps6", "label": "t and chi-square distributions"}, "regression": {"tid": "ml2", "label": "Simple linear regression"}, "mreg": {"tid": "ml3", "label": "Multiple linear regression"}, "logreg": {"tid": "ml5", "label": "Logistic regression"}};
const PRACTICE_BOOKS = [
  {
    id: "ross", dotted: true, title: "Sheldon Ross — A First Course in Probability (10th ed)", short: "Ross · First Course in Probability", subj: "ps",
    chapters: {1: "Combinatorial Analysis", 2: "Axioms of Probability", 3: "Conditional Probability and Independence", 4: "Random Variables", 5: "Continuous Random Variables", 6: "Jointly Distributed Random Variables", 7: "Properties of Expectation", 8: "Limit Theorems", 9: "Additional Topics (9.3 Entropy)"},
    notes: "Only GATE-relevant exercises are listed. Chapter 10 (Simulation) is skipped. Self-Test solutions are at the back of the book (page shown).",
    q: [
      {"c":1,"s":"P","n":1,"p":34,"l":"E","g":2,"k":"cnt_arr","t":"License plates with/without repetition","a":724},
      {"c":1,"s":"P","n":4,"p":34,"l":"E","g":2,"k":"cnt_arr","t":"Band instruments with restrictions","a":724},
      {"c":1,"s":"P","n":7,"p":35,"l":"M","g":3,"k":"cnt_arr","t":"Boys & girls in a row: together / alternate","a":724},
      {"c":1,"s":"P","n":8,"p":35,"l":"E","g":3,"k":"cnt_multi","t":"Letter arrangements with repeated letters","a":724},
      {"c":1,"s":"P","n":9,"p":35,"l":"E","g":2,"k":"cnt_multi","t":"Arrangements of coloured identical blocks","a":724},
      {"c":1,"s":"P","n":10,"p":35,"l":"M","g":3,"k":"cnt_arr","t":"Seating 8 people with adjacency constraints","a":724},
      {"c":1,"s":"P","n":11,"p":35,"l":"M","g":2,"k":"cnt_arr","t":"Books on a shelf, same subject together","a":724},
      {"c":1,"s":"P","n":12,"p":36,"l":"M","g":2,"k":"cnt_arr","t":"Digit numbers with equal digits","a":724},
      {"c":1,"s":"P","n":13,"p":36,"l":"M","g":2,"k":"cnt_multi","t":"Permutations of any length from MOTTO","a":724},
      {"c":1,"s":"P","n":14,"p":36,"l":"E","g":2,"k":"cnt_arr","t":"Awards to students, repeat allowed or not","a":724},
      {"c":1,"s":"P","n":15,"p":36,"l":"E","g":2,"k":"cnt_sel","t":"Handshakes in a group","a":724},
      {"c":1,"s":"P","n":16,"p":36,"l":"E","g":2,"k":"cnt_sel","t":"Number of 5-card poker hands","a":724},
      {"c":1,"s":"P","n":17,"p":36,"l":"M","g":2,"k":"cnt_sel","t":"Choose men & women, then pair them"},
      {"c":1,"s":"P","n":18,"p":36,"l":"E","g":2,"k":"cnt_sel","t":"Two books: same vs different subject","a":724},
      {"c":1,"s":"P","n":19,"p":36,"l":"E","g":2,"k":"cnt_arr","t":"Distinct gifts, at most one per child","a":724},
      {"c":1,"s":"P","n":20,"p":36,"l":"E","g":2,"k":"cnt_sel","t":"Committee from three groups","a":724},
      {"c":1,"s":"P","n":21,"p":36,"l":"M","g":3,"k":"cnt_sel","t":"Committee when two people refuse to serve together","a":724},
      {"c":1,"s":"P","n":22,"p":36,"l":"M","g":3,"k":"cnt_sel","t":"Party invites with feuding friends","a":724},
      {"c":1,"s":"P","n":23,"p":37,"l":"E","g":3,"k":"cnt_multi","t":"Lattice paths on a grid (figure)","a":724},
      {"c":1,"s":"P","n":24,"p":37,"l":"M","g":3,"k":"cnt_multi","t":"Lattice paths through a given point (figure)","a":724},
      {"c":1,"s":"P","n":30,"p":38,"l":"E","g":2,"k":"cnt_multi","t":"Divide 12 people into committees 3/4/5","a":724},
      {"c":1,"s":"P","n":31,"p":38,"l":"M","g":2,"k":"cnt_multi","t":"Teachers divided among schools","a":724},
      {"c":1,"s":"P","n":32,"p":38,"l":"M","g":2,"k":"cnt_multi","t":"Weight-lifter ranking outcomes by country","a":724},
      {"c":1,"s":"P","n":33,"p":38,"l":"M","g":2,"k":"cnt_arr","t":"Delegates seated with restrictions","a":724},
      {"c":1,"s":"P","n":34,"p":38,"l":"M","g":3,"k":"cnt_stars","t":"Identical blackboards to schools (stars & bars)","x":1,"a":724},
      {"c":1,"s":"P","n":35,"p":38,"l":"H","g":2,"k":"cnt_multi","t":"Elevator: people leaving at floors","x":1,"a":724},
      {"c":1,"s":"P","n":36,"p":38,"l":"H","g":3,"k":"cnt_stars","t":"Integer investments with minimums","x":1,"a":725},
      {"c":1,"s":"P","n":37,"p":38,"l":"H","g":2,"k":"cnt_stars","t":"Fish types: outcome counts","x":1},
      {"c":1,"s":"TE","n":5,"p":39,"l":"M","g":2,"k":"cnt_sel","t":"Binary vectors with sum at least k"},
      {"c":1,"s":"TE","n":20,"p":43,"l":"M","g":3,"k":"cnt_stars","t":"Identical balls into urns with minimums","x":1},
      {"c":1,"s":"TE","n":21,"p":43,"l":"H","g":2,"k":"cnt_stars","t":"Solutions with exactly k zeros","x":1},
      {"c":1,"s":"TE","n":23,"p":43,"l":"H","g":2,"k":"cnt_stars","t":"Nonnegative vectors with bounded sum","x":1},
      {"c":1,"s":"ST","n":1,"p":43,"l":"M","g":3,"k":"cnt_arr","t":"Letter arrangements: adjacent / before","o":733},
      {"c":1,"s":"ST","n":2,"p":43,"l":"M","g":3,"k":"cnt_arr","t":"Nationalities seated together","o":733},
      {"c":1,"s":"ST","n":3,"p":44,"l":"E","g":2,"k":"cnt_arr","t":"Club officers with constraints","o":733},
      {"c":1,"s":"ST","n":4,"p":44,"l":"M","g":3,"k":"cnt_sel","t":"Exam: choose 7 of 10 with a condition","o":734},
      {"c":1,"s":"ST","n":5,"p":44,"l":"E","g":2,"k":"cnt_multi","t":"Divide gifts 3/2/2 among children","o":734},
      {"c":1,"s":"ST","n":6,"p":44,"l":"E","g":2,"k":"cnt_arr","t":"License plates, letters/digits anywhere","o":734},
      {"c":1,"s":"ST","n":8,"p":44,"l":"M","g":3,"k":"cnt_arr","t":"Digit strings: no two consecutive equal","o":734},
      {"c":1,"s":"ST","n":9,"p":44,"l":"M","g":2,"k":"cnt_sel","t":"Choose 3 students from three classes","o":734},
      {"c":1,"s":"ST","n":10,"p":44,"l":"H","g":2,"k":"cnt_arr","t":"5-digit numbers, no digit more than twice","o":734},
      {"c":1,"s":"ST","n":11,"p":44,"l":"M","g":3,"k":"cnt_sel","t":"Select people with no married couple","o":735},
      {"c":1,"s":"ST","n":12,"p":45,"l":"M","g":3,"k":"cnt_sel","t":"Committee with at least 3 women, 2 men","o":735},
      {"c":1,"s":"ST","n":14,"p":45,"l":"H","g":2,"k":"cnt_stars","t":"Positive integer vectors with sum","x":1,"o":735},
      {"c":1,"s":"ST","n":15,"p":45,"l":"M","g":2,"k":"cnt_arr","t":"Exam result rankings with ties","o":735},
      {"c":1,"s":"ST","n":16,"p":45,"l":"M","g":3,"k":"ie","t":"Subsets containing at least one given element","o":736},
      {"c":1,"s":"ST","n":18,"p":45,"l":"M","g":2,"k":"cnt_sel","t":"Choosing among families","o":736},
      {"c":1,"s":"ST","n":19,"p":45,"l":"E","g":2,"k":"cnt_arr","t":"8-place license plates, any positions","o":736},
      {"c":2,"s":"P","n":3,"p":86,"l":"E","g":2,"k":"events","t":"Events on two dice: unions, intersections, complements"},
      {"c":2,"s":"P","n":8,"p":87,"l":"E","g":3,"k":"axioms","t":"Mutually exclusive events: union and differences"},
      {"c":2,"s":"P","n":9,"p":87,"l":"E","g":3,"k":"axioms","t":"Credit cards: P(A or B) from P(A), P(B), P(AB)","a":725},
      {"c":2,"s":"P","n":10,"p":87,"l":"E","g":3,"k":"axioms","t":"Ring/necklace: probability of both","a":725},
      {"c":2,"s":"P","n":11,"p":87,"l":"E","g":3,"k":"axioms","t":"Smokers: cigar/cigarette overlap","a":725},
      {"c":2,"s":"P","n":12,"p":87,"l":"M","g":3,"k":"ie","t":"Three language classes: inclusion–exclusion","a":725},
      {"c":2,"s":"P","n":13,"p":88,"l":"M","g":3,"k":"ie","t":"Three newspapers: readers of exactly one / none","a":725},
      {"c":2,"s":"P","n":14,"p":88,"l":"M","g":2,"k":"ie","t":"Survey data consistency (inclusion–exclusion)","a":725},
      {"c":2,"s":"P","n":15,"p":88,"l":"M","g":3,"k":"prob_classic","t":"Poker hand probabilities (flush, pairs …)","a":725},
      {"c":2,"s":"P","n":16,"p":89,"l":"M","g":2,"k":"prob_classic","t":"Poker dice outcome probabilities"},
      {"c":2,"s":"P","n":17,"p":89,"l":"M","g":2,"k":"prob_classic","t":"Ninth woman in position 17","a":725},
      {"c":2,"s":"P","n":18,"p":89,"l":"E","g":2,"k":"prob_classic","t":"Two cards forming blackjack","a":725},
      {"c":2,"s":"P","n":19,"p":89,"l":"M","g":2,"k":"prob_classic","t":"Painted dice: same colour","a":725},
      {"c":2,"s":"P","n":21,"p":89,"l":"M","g":2,"k":"prob_classic","t":"Random family vs random child: family size"},
      {"c":2,"s":"P","n":23,"p":90,"l":"E","g":3,"k":"prob_classic","t":"Second die higher than first","a":725},
      {"c":2,"s":"P","n":24,"p":90,"l":"E","g":3,"k":"prob_classic","t":"Sum of two dice equals i"},
      {"c":2,"s":"P","n":25,"p":90,"l":"M","g":3,"k":"prob_classic","t":"Dice until sum 5 or 7: 5 first","a":725},
      {"c":2,"s":"P","n":26,"p":90,"l":"M","g":2,"k":"prob_classic","t":"Game of craps: winning probability","a":725},
      {"c":2,"s":"P","n":27,"p":90,"l":"M","g":2,"k":"prob_classic","t":"Urn: who draws the first red ball"},
      {"c":2,"s":"P","n":28,"p":90,"l":"E","g":3,"k":"prob_classic","t":"Three balls: same colour / all different","a":725},
      {"c":2,"s":"P","n":29,"p":90,"l":"M","g":2,"k":"prob_classic","t":"Two balls same colour, with/without replacement"},
      {"c":2,"s":"P","n":30,"p":91,"l":"M","g":2,"k":"prob_classic","t":"Chess club pairings probability","a":725},
      {"c":2,"s":"P","n":31,"p":91,"l":"M","g":2,"k":"prob_classic","t":"Basketball teams: one of each position","a":725},
      {"c":2,"s":"P","n":32,"p":91,"l":"E","g":2,"k":"prob_classic","t":"Random line-up: girl in position i"},
      {"c":2,"s":"P","n":33,"p":91,"l":"E","g":3,"k":"prob_classic","t":"Capture–recapture (hypergeometric) elk","a":725},
      {"c":2,"s":"P","n":35,"p":91,"l":"M","g":3,"k":"prob_classic","t":"Balls by colour counts drawn from urn"},
      {"c":2,"s":"P","n":36,"p":92,"l":"E","g":3,"k":"prob_classic","t":"Two cards: both aces / same value","a":725},
      {"c":2,"s":"P","n":37,"p":92,"l":"M","g":2,"k":"prob_classic","t":"Exam problem selection probability","a":725},
      {"c":2,"s":"P","n":38,"p":92,"l":"M","g":2,"k":"prob_classic","t":"Find number of socks from a probability","a":725},
      {"c":2,"s":"P","n":39,"p":92,"l":"E","g":2,"k":"prob_classic","t":"People checking into different hotels","a":725},
      {"c":2,"s":"P","n":40,"p":92,"l":"M","g":3,"k":"prob_classic","t":"At least one green / one of each colour","a":725},
      {"c":2,"s":"P","n":41,"p":92,"l":"E","g":3,"k":"prob_classic","t":"At least one 6 in 4 rolls (complement)","a":725},
      {"c":2,"s":"P","n":42,"p":92,"l":"M","g":3,"k":"prob_classic","t":"Double six at least once in n throws"},
      {"c":2,"s":"P","n":43,"p":92,"l":"M","g":3,"k":"prob_classic","t":"Two given people adjacent in a line / circle"},
      {"c":2,"s":"P","n":44,"p":92,"l":"M","g":2,"k":"prob_classic","t":"Five people: separation between two of them","a":725},
      {"c":2,"s":"P","n":45,"p":93,"l":"M","g":2,"k":"prob_classic","t":"Keys tried at random: opens on k-th try"},
      {"c":2,"s":"P","n":46,"p":93,"l":"M","g":3,"k":"prob_classic","t":"Birthday-month problem","a":725},
      {"c":2,"s":"P","n":47,"p":93,"l":"M","g":2,"k":"prob_classic","t":"Third smallest of chosen numbers","a":725},
      {"c":2,"s":"P","n":49,"p":93,"l":"M","g":2,"k":"prob_classic","t":"Split 6 men 6 women: equal men in groups","a":725},
      {"c":2,"s":"P","n":51,"p":93,"l":"M","g":2,"k":"prob_classic","t":"Balls into compartments: m in first"},
      {"c":2,"s":"P","n":52,"p":93,"l":"H","g":2,"k":"prob_classic","t":"Shoes: no complete pair / one pair","a":725},
      {"c":2,"s":"P","n":53,"p":93,"l":"H","g":2,"k":"ie","t":"Couples in a row: nobody next to partner","a":725},
      {"c":2,"s":"P","n":54,"p":93,"l":"H","g":2,"k":"ie","t":"Bridge hand void in at least one suit","a":725},
      {"c":2,"s":"TE","n":6,"p":95,"l":"E","g":2,"k":"events","t":"Express events: only E occurs, at least two …"},
      {"c":2,"s":"TE","n":12,"p":96,"l":"M","g":2,"k":"axioms","t":"Exactly one of E or F occurs"},
      {"c":2,"s":"TE","n":15,"p":96,"l":"M","g":2,"k":"prob_classic","t":"Sample from urn: k white balls"},
      {"c":2,"s":"ST","n":1,"p":97,"l":"E","g":2,"k":"prob_classic","t":"Meal choices from a table","o":737},
      {"c":2,"s":"ST","n":2,"p":98,"l":"M","g":3,"k":"ie","t":"Suit / shirt / tie purchase probabilities","o":737},
      {"c":2,"s":"ST","n":3,"p":98,"l":"M","g":3,"k":"prob_classic","t":"14th card is an ace / first ace at 14","o":737},
      {"c":2,"s":"ST","n":5,"p":98,"l":"E","g":3,"k":"prob_classic","t":"Top four cards: different denominations / suits","o":738},
      {"c":2,"s":"ST","n":6,"p":98,"l":"E","g":2,"k":"prob_classic","t":"Ball from each of two urns: same colour","o":738},
      {"c":2,"s":"ST","n":7,"p":98,"l":"M","g":2,"k":"prob_classic","t":"Lottery: matching numbers","o":738},
      {"c":2,"s":"ST","n":8,"p":98,"l":"M","g":3,"k":"prob_classic","t":"Committee has one of each class","o":738},
      {"c":2,"s":"ST","n":10,"p":99,"l":"M","g":2,"k":"prob_classic","t":"Horse race outcome events","o":739},
      {"c":2,"s":"ST","n":11,"p":99,"l":"M","g":3,"k":"ie","t":"5-card hand with every suit","o":739},
      {"c":2,"s":"ST","n":12,"p":99,"l":"M","g":2,"k":"prob_classic","t":"Roommate pairing by position","o":740},
      {"c":2,"s":"ST","n":13,"p":99,"l":"E","g":3,"k":"prob_classic","t":"Same letter from two words","o":740},
      {"c":2,"s":"ST","n":17,"p":100,"l":"M","g":3,"k":"ie","t":"At least one ball of each colour","o":741},
      {"c":2,"s":"ST","n":18,"p":100,"l":"M","g":2,"k":"prob_classic","t":"Balls in a line: first positions blue","o":741},
      {"c":2,"s":"ST","n":20,"p":100,"l":"H","g":2,"k":"prob_classic","t":"All red balls removed before blue","o":742},
      {"c":3,"s":"P","n":1,"p":165,"l":"E","g":3,"k":"cond","t":"Two dice: at least one 6 given different numbers","a":726},
      {"c":3,"s":"P","n":2,"p":165,"l":"E","g":3,"k":"cond","t":"First die is 6 given the sum","a":726},
      {"c":3,"s":"P","n":4,"p":165,"l":"E","g":3,"k":"cond","t":"At least one 6 given the sum"},
      {"c":3,"s":"P","n":5,"p":165,"l":"E","g":3,"k":"cond","t":"Urn: first two white given 3 white drawn","a":726},
      {"c":3,"s":"P","n":6,"p":165,"l":"M","g":3,"k":"cond","t":"With vs without replacement: conditional on count","a":726},
      {"c":3,"s":"P","n":7,"p":165,"l":"E","g":2,"k":"cond","t":"King's sibling is a sister","a":726},
      {"c":3,"s":"P","n":8,"p":165,"l":"E","g":3,"k":"cond","t":"Both girls given older is a girl","a":726},
      {"c":3,"s":"P","n":9,"p":165,"l":"M","g":3,"k":"bayes","t":"Three urns: which urn given colours drawn","a":726},
      {"c":3,"s":"P","n":10,"p":165,"l":"M","g":2,"k":"cond","t":"Three cards: first is spade given others","a":726},
      {"c":3,"s":"P","n":11,"p":166,"l":"M","g":3,"k":"cond","t":"Two cards: both aces given one is an ace / ace of spades","a":726},
      {"c":3,"s":"P","n":13,"p":166,"l":"M","g":2,"k":"cond","t":"Actuarial exams: pass sequence (chain rule)","a":726},
      {"c":3,"s":"P","n":14,"p":166,"l":"M","g":2,"k":"cond","t":"Each hand gets one ace (chain rule)"},
      {"c":3,"s":"P","n":15,"p":166,"l":"M","g":2,"k":"cond","t":"Pólya urn: colours of successive draws","a":726},
      {"c":3,"s":"P","n":16,"p":166,"l":"M","g":3,"k":"bayes","t":"Ectopic pregnancy: smoker given condition","a":726},
      {"c":3,"s":"P","n":17,"p":166,"l":"M","g":3,"k":"bayes","t":"C-section survival probabilities","a":726},
      {"c":3,"s":"P","n":18,"p":167,"l":"E","g":3,"k":"cond","t":"Dog and cat ownership conditional","a":726},
      {"c":3,"s":"P","n":19,"p":167,"l":"M","g":3,"k":"bayes","t":"Voter groups: party given voted","a":726},
      {"c":3,"s":"P","n":20,"p":167,"l":"M","g":3,"k":"bayes","t":"Quit-smoking class: woman given success","a":726},
      {"c":3,"s":"P","n":21,"p":167,"l":"M","g":2,"k":"cond","t":"Female given CS major (percentages)","a":726},
      {"c":3,"s":"P","n":22,"p":167,"l":"M","g":3,"k":"cond","t":"Joint salary table: conditional from table","a":726},
      {"c":3,"s":"P","n":23,"p":168,"l":"M","g":2,"k":"cond","t":"Three dice ordering given condition","a":726},
      {"c":3,"s":"P","n":24,"p":168,"l":"M","g":3,"k":"bayes","t":"Ball moved between urns: colour given draw","a":726},
      {"c":3,"s":"P","n":25,"p":168,"l":"M","g":2,"k":"bayes","t":"Phone calls: daughter given hang-up"},
      {"c":3,"s":"P","n":26,"p":168,"l":"M","g":2,"k":"bayes","t":"Painted balls: colour given draws","a":726},
      {"c":3,"s":"P","n":28,"p":169,"l":"E","g":3,"k":"bayes","t":"Colour blind person: male given colour blind","a":726},
      {"c":3,"s":"P","n":30,"p":169,"l":"M","g":2,"k":"cond","t":"First ace position given conditions","a":726},
      {"c":3,"s":"P","n":31,"p":169,"l":"M","g":2,"k":"bayes","t":"Tennis balls: used vs new given draw","a":726},
      {"c":3,"s":"P","n":32,"p":170,"l":"E","g":3,"k":"bayes","t":"Two boxes of marbles: which box given white","a":726},
      {"c":3,"s":"P","n":33,"p":170,"l":"M","g":2,"k":"bayes","t":"Biopsy news: conditional reasoning"},
      {"c":3,"s":"P","n":34,"p":170,"l":"M","g":2,"k":"bayes","t":"Family size given eldest child"},
      {"c":3,"s":"P","n":35,"p":170,"l":"E","g":3,"k":"bayes","t":"Rain and lateness: rain given late","a":726},
      {"c":3,"s":"P","n":37,"p":170,"l":"M","g":3,"k":"bayes","t":"Present hidden upstairs: mom or dad","a":726},
      {"c":3,"s":"P","n":38,"p":171,"l":"M","g":3,"k":"bayes","t":"Resignation from one of three stores","a":726},
      {"c":3,"s":"P","n":39,"p":171,"l":"E","g":3,"k":"bayes","t":"Fair vs two-headed coin given heads","a":726},
      {"c":3,"s":"P","n":40,"p":171,"l":"M","g":3,"k":"bayes","t":"Coin chooses urn: urn given colour","a":726},
      {"c":3,"s":"P","n":41,"p":171,"l":"M","g":2,"k":"bayes","t":"Accident-prone: accident year 2 given none year 1","a":726},
      {"c":3,"s":"P","n":42,"p":171,"l":"M","g":2,"k":"cond","t":"Draws with replacement plus extra balls","a":726},
      {"c":3,"s":"P","n":43,"p":171,"l":"M","g":2,"k":"bayes","t":"Half deck: ace given ace drawn","a":726},
      {"c":3,"s":"P","n":44,"p":172,"l":"M","g":2,"k":"cond","t":"Households: California given income","a":726},
      {"c":3,"s":"P","n":45,"p":172,"l":"E","g":3,"k":"bayes","t":"Three coins: which coin given heads","a":726},
      {"c":3,"s":"P","n":46,"p":172,"l":"M","g":2,"k":"cond","t":"Three prisoners paradox"},
      {"c":3,"s":"P","n":47,"p":172,"l":"M","g":2,"k":"bayes","t":"Computer fixed by A or B","a":726},
      {"c":3,"s":"P","n":48,"p":172,"l":"M","g":2,"k":"bayes","t":"Policyholder claims: male given claim"},
      {"c":3,"s":"P","n":49,"p":172,"l":"M","g":2,"k":"total","t":"Die decides how many balls drawn"},
      {"c":3,"s":"P","n":50,"p":172,"l":"E","g":3,"k":"bayes","t":"Cabinets with coins: other drawer silver","a":727},
      {"c":3,"s":"P","n":51,"p":173,"l":"M","g":3,"k":"bayes","t":"PSA test: cancer given test result"},
      {"c":3,"s":"P","n":52,"p":173,"l":"M","g":3,"k":"bayes","t":"Insurance risk class given accident","a":727},
      {"c":3,"s":"P","n":53,"p":173,"l":"M","g":2,"k":"bayes","t":"Job offer given strong recommendation","a":727},
      {"c":3,"s":"P","n":56,"p":174,"l":"M","g":2,"k":"bayes","t":"Two coins: probability of heads sequence","a":727},
      {"c":3,"s":"P","n":57,"p":174,"l":"M","g":2,"k":"indep","t":"Series won by first to n wins","a":727},
      {"c":3,"s":"P","n":58,"p":174,"l":"E","g":3,"k":"indep","t":"Parallel system reliability","a":727},
      {"c":3,"s":"P","n":59,"p":174,"l":"E","g":2,"k":"indep","t":"Would you model these events as independent?"},
      {"c":3,"s":"P","n":60,"p":175,"l":"E","g":2,"k":"indep","t":"Sex and class independence in a class","a":727},
      {"c":3,"s":"P","n":64,"p":176,"l":"E","g":3,"k":"indep","t":"Independent flips: specific outcome sequences"},
      {"c":3,"s":"P","n":65,"p":176,"l":"M","g":2,"k":"bayes","t":"Eye-colour genetics","a":727},
      {"c":3,"s":"P","n":66,"p":176,"l":"M","g":2,"k":"bayes","t":"Albinism genetics","a":727},
      {"c":3,"s":"P","n":67,"p":176,"l":"M","g":2,"k":"indep","t":"Target shooting: who hit"},
      {"c":3,"s":"P","n":68,"p":177,"l":"M","g":2,"k":"indep","t":"Duel: probability of outcomes"},
      {"c":3,"s":"P","n":69,"p":177,"l":"M","g":2,"k":"bayes","t":"Twins: identical given same sex","a":727},
      {"c":3,"s":"P","n":70,"p":177,"l":"M","g":3,"k":"indep","t":"Relay circuit (figure): current flows"},
      {"c":3,"s":"P","n":71,"p":178,"l":"M","g":3,"k":"indep","t":"k-out-of-n system reliability"},
      {"c":3,"s":"P","n":72,"p":178,"l":"M","g":2,"k":"bayes","t":"Relays closed given current flows"},
      {"c":3,"s":"P","n":74,"p":179,"l":"M","g":2,"k":"bayes","t":"Hemophilia: queen carrier given healthy princes","a":727},
      {"c":3,"s":"P","n":76,"p":179,"l":"M","g":2,"k":"cond","t":"Children: sex distribution conditional","a":727},
      {"c":3,"s":"P","n":77,"p":179,"l":"M","g":2,"k":"indep","t":"Alternating dice rolls until target sums","a":727},
      {"c":3,"s":"P","n":79,"p":180,"l":"M","g":2,"k":"indep","t":"E before F in repeated trials"},
      {"c":3,"s":"P","n":82,"p":180,"l":"H","g":2,"k":"indep","t":"2 sevens before 6 even numbers","a":727},
      {"c":3,"s":"P","n":86,"p":181,"l":"M","g":2,"k":"bayes","t":"Dice chosen by coin: red faces","a":727},
      {"c":3,"s":"P","n":87,"p":181,"l":"M","g":2,"k":"indep","t":"Players draw in turn until white","a":727},
      {"c":3,"s":"P","n":88,"p":182,"l":"M","g":2,"k":"indep","t":"Same as 3.87 with separate urns"},
      {"c":3,"s":"P","n":91,"p":183,"l":"M","g":2,"k":"bayes","t":"Key search with miss probability","a":727},
      {"c":3,"s":"P","n":94,"p":184,"l":"M","g":3,"k":"bayes","t":"Three-judge panel: guilty given verdict","a":727},
      {"c":3,"s":"TE","n":3,"p":185,"l":"M","g":2,"k":"cond","t":"Random family vs random child: sizes"},
      {"c":3,"s":"TE","n":4,"p":185,"l":"M","g":2,"k":"bayes","t":"Ball search in boxes: box i given search failed"},
      {"c":3,"s":"TE","n":8,"p":186,"l":"M","g":2,"k":"indep","t":"Dice events: independence proof"},
      {"c":3,"s":"TE","n":9,"p":187,"l":"E","g":3,"k":"indep","t":"Pairwise but not mutually independent (coin tosses)"},
      {"c":3,"s":"TE","n":10,"p":187,"l":"M","g":3,"k":"bayes","t":"Mammogram: cancer given positive"},
      {"c":3,"s":"TE","n":11,"p":187,"l":"M","g":2,"k":"indep","t":"Tosses needed for P(at least one head) ≥ p"},
      {"c":3,"s":"TE","n":15,"p":188,"l":"M","g":2,"k":"indep","t":"Trials until r successes"},
      {"c":3,"s":"TE","n":22,"p":189,"l":"M","g":2,"k":"cond","t":"Wet/dry weather model (Markov-type)"},
      {"c":3,"s":"TE","n":28,"p":190,"l":"M","g":2,"k":"condind","t":"Independent does not imply conditionally independent"},
      {"c":3,"s":"ST","n":1,"p":191,"l":"M","g":2,"k":"cond","t":"Bridge: partner's aces given West has none","o":742},
      {"c":3,"s":"ST","n":2,"p":191,"l":"E","g":3,"k":"cond","t":"Battery life: survive given survived","o":743},
      {"c":3,"s":"ST","n":3,"p":192,"l":"M","g":2,"k":"total","t":"Arrange balls in two urns to maximise P(white)","o":743},
      {"c":3,"s":"ST","n":4,"p":192,"l":"M","g":3,"k":"bayes","t":"Ball moved between urns: reverse inference","o":743},
      {"c":3,"s":"ST","n":5,"p":192,"l":"M","g":2,"k":"cond","t":"Red balls removed one at a time","o":743},
      {"c":3,"s":"ST","n":6,"p":192,"l":"M","g":2,"k":"cond","t":"Pólya urn: colours of draws","o":743},
      {"c":3,"s":"ST","n":7,"p":192,"l":"M","g":3,"k":"cond","t":"Two cards: both aces under different information","o":743},
      {"c":3,"s":"ST","n":8,"p":192,"l":"M","g":2,"k":"bayes","t":"Odds form of Bayes' rule","o":744},
      {"c":3,"s":"ST","n":9,"p":193,"l":"E","g":3,"k":"bayes","t":"Plant watering: neighbour forgot given plant died","o":744},
      {"c":3,"s":"ST","n":10,"p":193,"l":"M","g":3,"k":"cond","t":"At least one red; conditional on colour counts","o":744},
      {"c":3,"s":"ST","n":11,"p":193,"l":"M","g":3,"k":"bayes","t":"Battery type given it works","o":745},
      {"c":3,"s":"ST","n":12,"p":193,"l":"M","g":2,"k":"indep","t":"Liking two books: combinations","o":745},
      {"c":3,"s":"ST","n":13,"p":193,"l":"H","g":2,"k":"cond","t":"All red balls removed before blue","o":745},
      {"c":3,"s":"ST","n":14,"p":194,"l":"M","g":2,"k":"bayes","t":"Noisy message relay: true outcome given report","o":746},
      {"c":3,"s":"ST","n":15,"p":194,"l":"M","g":2,"k":"bayes","t":"Rat genetics: carrier probabilities","o":746},
      {"c":3,"s":"ST","n":16,"p":194,"l":"M","g":2,"k":"total","t":"Circuit: condition on relay 1","o":746},
      {"c":3,"s":"ST","n":17,"p":194,"l":"M","g":2,"k":"bayes","t":"k-out-of-n: component works given system works","o":747},
      {"c":3,"s":"ST","n":20,"p":195,"l":"M","g":2,"k":"indep","t":"Two trials give same outcome","o":748},
      {"c":3,"s":"ST","n":22,"p":195,"l":"M","g":3,"k":"indep","t":"Is independence transitive? (true/false)","o":749},
      {"c":3,"s":"ST","n":23,"p":195,"l":"M","g":3,"k":"cond","t":"True/false statements on conditional probability","o":749},
      {"c":3,"s":"ST","n":24,"p":195,"l":"M","g":2,"k":"indep","t":"Rank events by likelihood","o":749},
      {"c":3,"s":"ST","n":25,"p":195,"l":"M","g":3,"k":"bayes","t":"Defective radio: which factory","o":750},
      {"c":3,"s":"ST","n":29,"p":196,"l":"M","g":2,"k":"indep","t":"Coupon types collected","o":751},
      {"c":3,"s":"ST","n":31,"p":196,"l":"E","g":2,"k":"axioms","t":"Odds to probability conversion","o":752},
      {"c":3,"s":"ST","n":35,"p":197,"l":"M","g":2,"k":"cond","t":"All white given same colour","o":753},
      {"c":4,"s":"P","n":1,"p":276,"l":"E","g":3,"k":"rv_disc","t":"Winnings from two balls: PMF of X","a":727},
      {"c":4,"s":"P","n":2,"p":276,"l":"E","g":3,"k":"rv_disc","t":"PMF of product of two dice"},
      {"c":4,"s":"P","n":3,"p":276,"l":"E","g":2,"k":"rv_disc","t":"Sum of three dice: PMF"},
      {"c":4,"s":"P","n":4,"p":276,"l":"M","g":2,"k":"rv_disc","t":"Highest-ranked woman: PMF","a":727},
      {"c":4,"s":"P","n":5,"p":277,"l":"E","g":2,"k":"rv_disc","t":"Heads minus tails: possible values","a":727},
      {"c":4,"s":"P","n":6,"p":277,"l":"E","g":2,"k":"rv_disc","t":"Heads minus tails: probabilities","a":727},
      {"c":4,"s":"P","n":7,"p":277,"l":"E","g":2,"k":"rv_disc","t":"Two die rolls: max, min, sum, difference values"},
      {"c":4,"s":"P","n":8,"p":277,"l":"E","g":3,"k":"rv_disc","t":"Probabilities for max/min/sum of two dice"},
      {"c":4,"s":"P","n":9,"p":277,"l":"M","g":2,"k":"rv_disc","t":"Example 1c with replacement"},
      {"c":4,"s":"P","n":10,"p":277,"l":"M","g":2,"k":"rv_disc","t":"Gambler: win given positive winnings"},
      {"c":4,"s":"P","n":12,"p":277,"l":"M","g":2,"k":"exp_var","t":"Two-Finger Morra: expected winnings","a":727},
      {"c":4,"s":"P","n":13,"p":278,"l":"E","g":3,"k":"exp_var","t":"Salesman: PMF and expected sales","a":727},
      {"c":4,"s":"P","n":14,"p":278,"l":"M","g":2,"k":"rv_disc","t":"Number comparisons game PMF","a":728},
      {"c":4,"s":"P","n":16,"p":279,"l":"M","g":2,"k":"exp_var","t":"Card guessing: expected correct guesses","a":728},
      {"c":4,"s":"P","n":17,"p":279,"l":"E","g":3,"k":"cdf","t":"Probabilities from a given CDF","a":728},
      {"c":4,"s":"P","n":18,"p":279,"l":"E","g":3,"k":"binom","t":"PMF plot of number of heads in 4 flips"},
      {"c":4,"s":"P","n":19,"p":279,"l":"E","g":3,"k":"cdf","t":"PMF from a step CDF","a":728},
      {"c":4,"s":"P","n":20,"p":280,"l":"M","g":2,"k":"exp_var","t":"Roulette strategy: expected winnings","a":728},
      {"c":4,"s":"P","n":21,"p":280,"l":"M","g":3,"k":"exp_var","t":"Bus students: E[X] vs E[Y] (size-biased)","a":728},
      {"c":4,"s":"P","n":22,"p":280,"l":"M","g":2,"k":"exp_var","t":"Series length expectation"},
      {"c":4,"s":"P","n":25,"p":281,"l":"E","g":3,"k":"exp_var","t":"Two biased coins: E[number of heads]","a":728},
      {"c":4,"s":"P","n":26,"p":281,"l":"M","g":2,"k":"exp_var","t":"Guessing a number with yes–no questions"},
      {"c":4,"s":"P","n":27,"p":282,"l":"E","g":2,"k":"exp_var","t":"Insurance premium from expected payout","a":728},
      {"c":4,"s":"P","n":28,"p":282,"l":"E","g":3,"k":"hyper","t":"Expected defectives in a sample","a":728},
      {"c":4,"s":"P","n":30,"p":282,"l":"M","g":2,"k":"exp_var","t":"St. Petersburg-type expectation"},
      {"c":4,"s":"P","n":32,"p":283,"l":"M","g":3,"k":"exp_var","t":"Pooled blood testing: expected tests","a":728},
      {"c":4,"s":"P","n":33,"p":283,"l":"M","g":2,"k":"exp_var","t":"Newsboy problem: optimal stock","a":728},
      {"c":4,"s":"P","n":35,"p":283,"l":"E","g":3,"k":"exp_var","t":"Marble game: expected winnings, variance","a":728},
      {"c":4,"s":"P","n":38,"p":284,"l":"E","g":3,"k":"exp_var","t":"Variance of given random variables","a":728},
      {"c":4,"s":"P","n":39,"p":284,"l":"E","g":3,"k":"exp_var","t":"E[X²], Var from mean and variance"},
      {"c":4,"s":"P","n":40,"p":284,"l":"E","g":3,"k":"binom","t":"Replace-and-draw: number of white","a":728},
      {"c":4,"s":"P","n":41,"p":284,"l":"E","g":3,"k":"binom","t":"Multiple-choice guessing: 4 or more correct","a":728},
      {"c":4,"s":"P","n":42,"p":284,"l":"E","g":3,"k":"binom","t":"ESP test: probability by chance"},
      {"c":4,"s":"P","n":43,"p":284,"l":"M","g":2,"k":"binom","t":"Two students: questions answered correctly","a":728},
      {"c":4,"s":"P","n":44,"p":284,"l":"M","g":3,"k":"binom","t":"Channel errors with repetition coding"},
      {"c":4,"s":"P","n":45,"p":284,"l":"M","g":2,"k":"binom","t":"Satellite k-of-n system in rain/dry"},
      {"c":4,"s":"P","n":46,"p":285,"l":"M","g":2,"k":"binom","t":"Oral exam: on/off day","a":728},
      {"c":4,"s":"P","n":47,"p":285,"l":"M","g":2,"k":"binom","t":"Jury conviction probability"},
      {"c":4,"s":"P","n":49,"p":285,"l":"E","g":3,"k":"binom","t":"Defective diskettes: package returned"},
      {"c":4,"s":"P","n":50,"p":286,"l":"M","g":2,"k":"binom","t":"Coin chosen, heads count: Bayes with binomial"},
      {"c":4,"s":"P","n":53,"p":286,"l":"M","g":2,"k":"binom","t":"Given 6 heads in 10, first flips","a":728},
      {"c":4,"s":"P","n":54,"p":286,"l":"E","g":3,"k":"pois","t":"Typos per page: Poisson","a":728},
      {"c":4,"s":"P","n":55,"p":287,"l":"E","g":3,"k":"pois","t":"Airplane crashes: Poisson"},
      {"c":4,"s":"P","n":56,"p":287,"l":"M","g":2,"k":"pois","t":"Shared birthday among couples (Poisson approx)","a":728},
      {"c":4,"s":"P","n":57,"p":287,"l":"E","g":3,"k":"pois","t":"Abandoned cars: Poisson","a":728},
      {"c":4,"s":"P","n":58,"p":287,"l":"M","g":2,"k":"pois","t":"Two typists: errors (mixture of Poissons)","a":728},
      {"c":4,"s":"P","n":59,"p":287,"l":"M","g":2,"k":"pois","t":"People needed to share your birthday","a":728},
      {"c":4,"s":"P","n":60,"p":287,"l":"M","g":2,"k":"pois","t":"Accidents per day: Poisson with conditions"},
      {"c":4,"s":"P","n":61,"p":287,"l":"M","g":2,"k":"pois","t":"Poisson vs exact binomial comparison"},
      {"c":4,"s":"P","n":62,"p":287,"l":"E","g":3,"k":"pois","t":"Lottery wins: Poisson approximation"},
      {"c":4,"s":"P","n":63,"p":288,"l":"M","g":3,"k":"pois","t":"Cold drug: Bayes with Poisson","a":728},
      {"c":4,"s":"P","n":64,"p":288,"l":"E","g":2,"k":"pois","t":"Full houses in 1000 hands","a":728},
      {"c":4,"s":"P","n":66,"p":288,"l":"E","g":3,"k":"pois","t":"Casino arrivals: Poisson counts","a":728},
      {"c":4,"s":"P","n":67,"p":288,"l":"E","g":2,"k":"pois","t":"Suicide rate: Poisson"},
      {"c":4,"s":"P","n":68,"p":289,"l":"M","g":2,"k":"pois","t":"Pooled blood tests in army","a":728},
      {"c":4,"s":"P","n":74,"p":290,"l":"M","g":2,"k":"binom","t":"Roulette: winning bets count","a":728},
      {"c":4,"s":"P","n":75,"p":290,"l":"M","g":2,"k":"negbin","t":"Best-of-7 series: stronger team wins"},
      {"c":4,"s":"P","n":76,"p":290,"l":"M","g":2,"k":"negbin","t":"Expected games in best-of-7","a":728},
      {"c":4,"s":"P","n":77,"p":290,"l":"M","g":2,"k":"negbin","t":"Interviewer: people contacted","a":728},
      {"c":4,"s":"P","n":78,"p":290,"l":"M","g":2,"k":"negbin","t":"Tails before 10th head"},
      {"c":4,"s":"P","n":81,"p":291,"l":"M","g":2,"k":"geom","t":"Urn repeated draws until 2-and-2: geometric"},
      {"c":4,"s":"P","n":82,"p":291,"l":"M","g":3,"k":"hyper","t":"Defectives in a sample (hypergeometric)"},
      {"c":4,"s":"P","n":84,"p":292,"l":"M","g":2,"k":"hyper","t":"Lot inspection: rejection","a":728},
      {"c":4,"s":"P","n":85,"p":292,"l":"M","g":3,"k":"hyper","t":"Transistor lot acceptance","a":728},
      {"c":4,"s":"P","n":86,"p":292,"l":"M","g":2,"k":"pois","t":"Three highways: total accidents","a":728},
      {"c":4,"s":"P","n":87,"p":292,"l":"M","g":2,"k":"lin_exp","t":"Balls into boxes: expected empty boxes"},
      {"c":4,"s":"P","n":89,"p":293,"l":"M","g":2,"k":"total","t":"Urn with random colour choice","a":729},
      {"c":4,"s":"TE","n":2,"p":293,"l":"E","g":2,"k":"cdf","t":"CDF of a transformed discrete RV"},
      {"c":4,"s":"TE","n":3,"p":293,"l":"E","g":2,"k":"cdf","t":"CDF of aX+b"},
      {"c":4,"s":"TE","n":5,"p":293,"l":"M","g":2,"k":"exp_var","t":"E[X] = Σ P(X ≥ i) (tail-sum formula)"},
      {"c":4,"s":"TE","n":7,"p":294,"l":"E","g":3,"k":"exp_var","t":"Mean & variance of standardised variable"},
      {"c":4,"s":"TE","n":8,"p":294,"l":"E","g":2,"k":"exp_var","t":"Find constant from expectation condition"},
      {"c":4,"s":"TE","n":10,"p":294,"l":"M","g":2,"k":"binom","t":"Binomial identity E[1/(X+1)]"},
      {"c":4,"s":"TE","n":14,"p":295,"l":"M","g":3,"k":"binom","t":"Mode of the binomial (most likely value)"},
      {"c":4,"s":"TE","n":15,"p":295,"l":"M","g":2,"k":"pois","t":"Poisson family sizes: proportions"},
      {"c":4,"s":"TE","n":16,"p":295,"l":"M","g":2,"k":"binom","t":"Even number of heads in n tosses"},
      {"c":4,"s":"TE","n":18,"p":295,"l":"M","g":2,"k":"pois","t":"P(Poisson is even)"},
      {"c":4,"s":"TE","n":19,"p":296,"l":"M","g":2,"k":"pois","t":"Mode of the Poisson"},
      {"c":4,"s":"TE","n":28,"p":298,"l":"M","g":2,"k":"geom","t":"Geometric: tail probability, memoryless"},
      {"c":4,"s":"TE","n":31,"p":299,"l":"M","g":2,"k":"rv_disc","t":"Max of balls drawn: PMF"},
      {"c":4,"s":"TE","n":32,"p":299,"l":"M","g":2,"k":"rv_disc","t":"Chips drawn: largest number PMF"},
      {"c":4,"s":"ST","n":1,"p":300,"l":"E","g":3,"k":"exp_var","t":"Hits in 3 at-bats: E[X] from PMF","o":754},
      {"c":4,"s":"ST","n":2,"p":300,"l":"E","g":3,"k":"rv_disc","t":"Find constant c of a PMF","o":754},
      {"c":4,"s":"ST","n":3,"p":300,"l":"M","g":2,"k":"exp_var","t":"Flip until one side twice: expected flips","o":755},
      {"c":4,"s":"ST","n":4,"p":300,"l":"M","g":3,"k":"exp_var","t":"Random family vs random child: E[children]","o":755},
      {"c":4,"s":"ST","n":5,"p":301,"l":"E","g":3,"k":"exp_var","t":"Find E[X²] / Var from given moments","o":756},
      {"c":4,"s":"ST","n":6,"p":301,"l":"M","g":2,"k":"bayes","t":"Two coins: expected heads, Bayes update","o":756},
      {"c":4,"s":"ST","n":9,"p":302,"l":"E","g":3,"k":"binom","t":"Binomial from mean 6, variance 2.4","o":757},
      {"c":4,"s":"ST","n":10,"p":302,"l":"M","g":2,"k":"rv_disc","t":"Draw with replacement until repeat: PMF","o":757},
      {"c":4,"s":"ST","n":11,"p":302,"l":"M","g":2,"k":"negbin","t":"First to 3 wins: series probability","o":757},
      {"c":4,"s":"ST","n":12,"p":302,"l":"M","g":2,"k":"total","t":"Soccer team bracket outcomes","o":758},
      {"c":4,"s":"ST","n":13,"p":302,"l":"M","g":3,"k":"binom","t":"7-judge majority decision correct","o":758},
      {"c":4,"s":"ST","n":14,"p":302,"l":"E","g":3,"k":"pois","t":"Hurricanes per year: P(≤3)","o":758},
      {"c":4,"s":"ST","n":15,"p":302,"l":"M","g":2,"k":"pois","t":"Truncated Poisson eggs","o":759},
      {"c":4,"s":"ST","n":16,"p":303,"l":"M","g":2,"k":"lin_exp","t":"Boys and girls choosing: expected couples","o":759},
      {"c":4,"s":"ST","n":18,"p":303,"l":"M","g":2,"k":"negbin","t":"Roulette until 4 wins: bets placed","o":760},
      {"c":4,"s":"ST","n":19,"p":303,"l":"M","g":2,"k":"geom","t":"Odd-person coffee game: rounds","o":760},
      {"c":4,"s":"ST","n":20,"p":304,"l":"M","g":2,"k":"geom","t":"Geometric: variance derivation","o":760},
      {"c":4,"s":"ST","n":21,"p":304,"l":"E","g":2,"k":"exp_var","t":"Show variable is Bernoulli; variance","o":761},
      {"c":4,"s":"ST","n":23,"p":304,"l":"M","g":2,"k":"cond","t":"Balls withdrawn: colour at position","o":762},
      {"c":4,"s":"ST","n":24,"p":304,"l":"M","g":2,"k":"binom","t":"Balls into urns: count in urn i","o":762},
      {"c":4,"s":"ST","n":25,"p":304,"l":"M","g":3,"k":"lin_exp","t":"Matching problem: expected matches and variance","o":762},
      {"c":4,"s":"ST","n":26,"p":305,"l":"M","g":2,"k":"geom","t":"Geometric value is even","o":763},
      {"c":4,"s":"ST","n":29,"p":305,"l":"M","g":2,"k":"bayes","t":"Coins with different p: flips until heads","o":764},
      {"c":4,"s":"ST","n":30,"p":305,"l":"E","g":2,"k":"binom","t":"n − X is binomial too","o":765},
      {"c":4,"s":"ST","n":31,"p":306,"l":"M","g":2,"k":"rv_disc","t":"Smallest of a random sample: PMF","o":765},
      {"c":5,"s":"P","n":1,"p":364,"l":"E","g":3,"k":"cont_pdf","t":"Find constant C of a PDF and its CDF"},
      {"c":5,"s":"P","n":2,"p":364,"l":"E","g":3,"k":"cont_pdf","t":"Unit + spare lifetime: probability from PDF","a":729},
      {"c":5,"s":"P","n":3,"p":364,"l":"E","g":3,"k":"cont_pdf","t":"Can this function be a PDF? Find C","a":729},
      {"c":5,"s":"P","n":4,"p":364,"l":"E","g":3,"k":"cont_pdf","t":"Device lifetime PDF: P(X > t)","a":729},
      {"c":5,"s":"P","n":5,"p":364,"l":"M","g":2,"k":"cont_pdf","t":"Filling station: tank capacity from sales PDF","a":729},
      {"c":5,"s":"P","n":6,"p":365,"l":"E","g":3,"k":"cont_pdf","t":"E[X] for three given densities","a":729},
      {"c":5,"s":"P","n":7,"p":365,"l":"E","g":3,"k":"cont_pdf","t":"Find a, b from PDF and E[X]","a":729},
      {"c":5,"s":"P","n":8,"p":365,"l":"E","g":3,"k":"cont_pdf","t":"Expected lifetime of a tube","a":729},
      {"c":5,"s":"P","n":10,"p":365,"l":"E","g":3,"k":"unif","t":"Train arrival: uniform arrival time","a":729},
      {"c":5,"s":"P","n":11,"p":366,"l":"M","g":2,"k":"unif","t":"Random point on a segment: ratio of pieces","a":729},
      {"c":5,"s":"P","n":12,"p":366,"l":"M","g":2,"k":"unif","t":"Bus breakdown location: service station placement"},
      {"c":5,"s":"P","n":13,"p":366,"l":"E","g":3,"k":"unif","t":"Bus stop waiting time: uniform, conditional","a":729},
      {"c":5,"s":"P","n":14,"p":366,"l":"E","g":2,"k":"unif","t":"E[X^n] for uniform two ways"},
      {"c":5,"s":"P","n":15,"p":366,"l":"E","g":3,"k":"normal","t":"Normal probabilities via Φ","a":729},
      {"c":5,"s":"P","n":16,"p":366,"l":"M","g":2,"k":"normal","t":"Rainfall: first year over a threshold","a":729},
      {"c":5,"s":"P","n":17,"p":366,"l":"M","g":3,"k":"normal","t":"Salaries: find μ, σ from percentiles","a":729},
      {"c":5,"s":"P","n":18,"p":366,"l":"E","g":3,"k":"normal","t":"Find variance from a normal probability","a":729},
      {"c":5,"s":"P","n":19,"p":366,"l":"E","g":3,"k":"normal","t":"Find c with P(X > c) given","a":729},
      {"c":5,"s":"P","n":20,"p":367,"l":"E","g":3,"k":"normal_approx","t":"Poll support: normal approx to binomial","a":729},
      {"c":5,"s":"P","n":21,"p":367,"l":"E","g":3,"k":"normal","t":"Heights: percentage over a value"},
      {"c":5,"s":"P","n":22,"p":367,"l":"M","g":2,"k":"normal_approx","t":"Tennis serves: normal approximation","a":729},
      {"c":5,"s":"P","n":23,"p":367,"l":"E","g":3,"k":"normal_approx","t":"1000 die rolls: number of sixes","a":729},
      {"c":5,"s":"P","n":24,"p":367,"l":"M","g":2,"k":"normal","t":"Chip lifetimes: normal probabilities"},
      {"c":5,"s":"P","n":25,"p":367,"l":"E","g":3,"k":"normal_approx","t":"Acceptable items: normal approximation"},
      {"c":5,"s":"P","n":26,"p":367,"l":"M","g":2,"k":"normal_approx","t":"Which coin? decision rule via normal approx","a":729},
      {"c":5,"s":"P","n":27,"p":367,"l":"M","g":3,"k":"normal_approx","t":"Is the coin fair? 5800 heads in 10000"},
      {"c":5,"s":"P","n":28,"p":368,"l":"E","g":3,"k":"normal_approx","t":"At least 20 left-handers in 200","a":729},
      {"c":5,"s":"P","n":30,"p":368,"l":"M","g":2,"k":"normal","t":"Image region classification by normal readings"},
      {"c":5,"s":"P","n":32,"p":368,"l":"E","g":3,"k":"expo","t":"Repair time: exponential probabilities","a":729},
      {"c":5,"s":"P","n":33,"p":368,"l":"M","g":2,"k":"transform","t":"Distribution of a function of a uniform","a":729},
      {"c":5,"s":"P","n":34,"p":368,"l":"E","g":3,"k":"expo","t":"Car lifetime: memoryless exponential","a":729},
      {"c":5,"s":"P","n":35,"p":369,"l":"M","g":2,"k":"transform","t":"cX for exponential X: density","a":729},
      {"c":5,"s":"P","n":38,"p":369,"l":"M","g":2,"k":"transform","t":"Uniform: density of a function of X"},
      {"c":5,"s":"P","n":39,"p":369,"l":"M","g":3,"k":"unif","t":"Uniform coefficient: roots of quadratic real","a":729},
      {"c":5,"s":"P","n":40,"p":369,"l":"M","g":2,"k":"transform","t":"Density of a function of an exponential"},
      {"c":5,"s":"P","n":41,"p":369,"l":"M","g":2,"k":"transform","t":"Uniform: E and density of transformed variable","a":729},
      {"c":5,"s":"P","n":42,"p":369,"l":"M","g":2,"k":"transform","t":"Density of e^U for uniform U","a":729},
      {"c":5,"s":"TE","n":7,"p":371,"l":"E","g":2,"k":"exp_var","t":"SD of aX + b"},
      {"c":5,"s":"TE","n":9,"p":371,"l":"E","g":2,"k":"normal","t":"Standard normal symmetry identities"},
      {"c":5,"s":"TE","n":12,"p":372,"l":"M","g":2,"k":"expo","t":"Moments of the exponential"},
      {"c":5,"s":"TE","n":13,"p":372,"l":"E","g":3,"k":"cont_pdf","t":"Median of a continuous RV"},
      {"c":5,"s":"TE","n":14,"p":372,"l":"E","g":2,"k":"cont_pdf","t":"Mode of a continuous RV"},
      {"c":5,"s":"TE","n":15,"p":372,"l":"E","g":2,"k":"expo","t":"cX of exponential is exponential"},
      {"c":5,"s":"TE","n":26,"p":373,"l":"M","g":2,"k":"transform","t":"Probability integral transform F(X)"},
      {"c":5,"s":"TE","n":27,"p":373,"l":"E","g":2,"k":"unif","t":"Linear transform of uniform"},
      {"c":5,"s":"TE","n":30,"p":373,"l":"M","g":2,"k":"transform","t":"Density of a transformed variable"},
      {"c":5,"s":"TE","n":31,"p":373,"l":"M","g":2,"k":"transform","t":"Density of e^X for normal X (lognormal)"},
      {"c":5,"s":"ST","n":1,"p":374,"l":"E","g":3,"k":"cont_pdf","t":"Playing-time density: probabilities","o":766},
      {"c":5,"s":"ST","n":2,"p":375,"l":"E","g":3,"k":"cont_pdf","t":"Find constant and probability from PDF","o":766},
      {"c":5,"s":"ST","n":3,"p":375,"l":"E","g":3,"k":"cont_pdf","t":"Find E[X] and Var(X) from PDF","o":766},
      {"c":5,"s":"ST","n":4,"p":375,"l":"E","g":3,"k":"cont_pdf","t":"Find parameters from PDF and E[X]","o":766},
      {"c":5,"s":"ST","n":6,"p":375,"l":"M","g":2,"k":"unif","t":"Sealed bid: optimal bid with uniform","o":767},
      {"c":5,"s":"ST","n":7,"p":375,"l":"M","g":2,"k":"unif","t":"Three successful rounds with uniform","o":767},
      {"c":5,"s":"ST","n":8,"p":376,"l":"E","g":3,"k":"normal","t":"IQ scores: normal probabilities","o":767},
      {"c":5,"s":"ST","n":9,"p":376,"l":"E","g":3,"k":"normal","t":"Travel time: when to leave","o":767},
      {"c":5,"s":"ST","n":10,"p":376,"l":"E","g":3,"k":"normal","t":"Tire life: normal probabilities","o":768},
      {"c":5,"s":"ST","n":11,"p":376,"l":"E","g":3,"k":"normal","t":"Rainfall: independent years","o":768},
      {"c":5,"s":"ST","n":12,"p":376,"l":"M","g":2,"k":"normal","t":"Salary table: normal approx","o":768},
      {"c":5,"s":"ST","n":13,"p":377,"l":"E","g":3,"k":"expo","t":"Teller service time: exponential, memoryless","o":769},
      {"c":5,"s":"ST","n":14,"p":377,"l":"M","g":2,"k":"cdf","t":"From a CDF: probabilities, hazard, mean","o":769},
      {"c":5,"s":"ST","n":17,"p":377,"l":"E","g":3,"k":"normal_approx","t":"Roulette winnings: normal approx","o":770},
      {"c":5,"s":"ST","n":18,"p":378,"l":"M","g":3,"k":"bayes","t":"Battery type given lifetime (exponential Bayes)","o":771},
      {"c":5,"s":"ST","n":19,"p":378,"l":"M","g":2,"k":"bayes","t":"Evidence value: exponential Bayes","o":772},
      {"c":5,"s":"ST","n":21,"p":378,"l":"E","g":3,"k":"normal","t":"True/false on normal CDF values","o":773},
      {"c":5,"s":"ST","n":22,"p":378,"l":"E","g":2,"k":"unif","t":"Linear transform of uniform","o":773},
      {"c":5,"s":"ST","n":23,"p":379,"l":"M","g":2,"k":"cont_pdf","t":"Verify density and compute probability","o":774},
      {"c":5,"s":"ST","n":24,"p":379,"l":"M","g":2,"k":"transform","t":"Density of min/max of U and 1 − U","o":774},
      {"c":6,"s":"P","n":1,"p":453,"l":"E","g":3,"k":"joint","t":"Joint PMF of max/sum etc. of two dice"},
      {"c":6,"s":"P","n":2,"p":454,"l":"E","g":3,"k":"joint","t":"Joint PMF of indicator draws (without replacement)","a":729},
      {"c":6,"s":"P","n":3,"p":454,"l":"M","g":2,"k":"joint","t":"Joint PMF of numbered white balls selected","a":729},
      {"c":6,"s":"P","n":4,"p":454,"l":"E","g":3,"k":"joint","t":"Joint PMF with replacement","a":729},
      {"c":6,"s":"P","n":5,"p":454,"l":"E","g":2,"k":"joint","t":"Joint PMF with replacement (numbered)"},
      {"c":6,"s":"P","n":6,"p":454,"l":"M","g":2,"k":"joint","t":"Cancer grade scores: joint PMF","a":729},
      {"c":6,"s":"P","n":7,"p":454,"l":"M","g":2,"k":"joint","t":"Failures before successes: joint PMF","a":729},
      {"c":6,"s":"P","n":8,"p":454,"l":"E","g":3,"k":"joint","t":"Joint PDF: find c and marginals","a":730},
      {"c":6,"s":"P","n":9,"p":455,"l":"E","g":3,"k":"joint","t":"Verify joint PDF, marginal, P(X > Y)","a":730},
      {"c":6,"s":"P","n":10,"p":455,"l":"E","g":3,"k":"joint","t":"Joint PDF: P(X > 1, Y < 1), P(X < Y)","a":730},
      {"c":6,"s":"P","n":12,"p":455,"l":"M","g":2,"k":"joint","t":"Poisson arrivals split by sex","a":730},
      {"c":6,"s":"P","n":13,"p":455,"l":"M","g":3,"k":"joint","t":"Meeting problem: uniform arrivals, wait ≤ 10 min","a":730},
      {"c":6,"s":"P","n":15,"p":456,"l":"M","g":2,"k":"joint","t":"Uniform over a region: probabilities by area","a":730},
      {"c":6,"s":"P","n":17,"p":457,"l":"M","g":2,"k":"joint","t":"Three random points: middle one","a":730},
      {"c":6,"s":"P","n":18,"p":457,"l":"E","g":2,"k":"joint","t":"Independent binomials: joint probabilities"},
      {"c":6,"s":"P","n":19,"p":457,"l":"E","g":3,"k":"joint","t":"Joint density: marginals","a":730},
      {"c":6,"s":"P","n":20,"p":457,"l":"E","g":3,"k":"indep_rv","t":"Are X and Y independent? (factorisation, support)"},
      {"c":6,"s":"P","n":21,"p":457,"l":"E","g":3,"k":"joint","t":"Joint PDF: verify, E[X], E[Y]","a":730},
      {"c":6,"s":"P","n":22,"p":457,"l":"E","g":3,"k":"indep_rv","t":"Independence and density of a function","a":730},
      {"c":6,"s":"P","n":23,"p":457,"l":"M","g":3,"k":"indep_rv","t":"Independence check with triangular support","a":730},
      {"c":6,"s":"P","n":25,"p":458,"l":"M","g":2,"k":"joint","t":"Arrivals uniformly distributed: counts","a":730},
      {"c":6,"s":"P","n":26,"p":458,"l":"M","g":2,"k":"order","t":"Max of independent uniforms: CDF"},
      {"c":6,"s":"P","n":27,"p":458,"l":"M","g":3,"k":"sumrv","t":"Independent exponentials: min, P(X < Y)"},
      {"c":6,"s":"P","n":28,"p":458,"l":"M","g":3,"k":"expo","t":"Car service times: exponential race","a":730},
      {"c":6,"s":"P","n":29,"p":459,"l":"E","g":3,"k":"sumrv","t":"Sum of normal daily sales","a":730},
      {"c":6,"s":"P","n":30,"p":459,"l":"E","g":3,"k":"sumrv","t":"Jill vs Jack bowling: difference of normals","a":730},
      {"c":6,"s":"P","n":31,"p":459,"l":"M","g":2,"k":"normal_approx","t":"Breakfast survey: normal approx","a":730},
      {"c":6,"s":"P","n":32,"p":459,"l":"M","g":2,"k":"sumrv","t":"Monthly sales: exactly k exceed a value","a":730},
      {"c":6,"s":"P","n":33,"p":459,"l":"M","g":2,"k":"sumrv","t":"Compare probabilities for sums of normals","a":730},
      {"c":6,"s":"P","n":34,"p":459,"l":"M","g":2,"k":"sumrv","t":"Find constant for P(X+Y) condition","a":730},
      {"c":6,"s":"P","n":37,"p":460,"l":"E","g":3,"k":"sumrv","t":"Typos in 10 pages: sum of Poissons","a":730},
      {"c":6,"s":"P","n":38,"p":460,"l":"E","g":3,"k":"sumrv","t":"Airplane crashes: sum of Poissons"},
      {"c":6,"s":"P","n":39,"p":460,"l":"E","g":3,"k":"cond_dist","t":"Conditional PMF given a value","a":730},
      {"c":6,"s":"P","n":40,"p":461,"l":"E","g":2,"k":"cond_dist","t":"Conditional PMF from Problem 6.3","a":730},
      {"c":6,"s":"P","n":42,"p":461,"l":"M","g":3,"k":"cond_dist","t":"Two-stage random choice: joint & conditional"},
      {"c":6,"s":"P","n":43,"p":461,"l":"E","g":3,"k":"cond_dist","t":"Max and min of two dice: conditional PMF"},
      {"c":6,"s":"P","n":44,"p":461,"l":"E","g":3,"k":"cond_dist","t":"Joint PMF table: conditional and independence"},
      {"c":6,"s":"P","n":45,"p":461,"l":"M","g":3,"k":"cond_dist","t":"Joint PDF: conditional densities","a":730},
      {"c":6,"s":"P","n":46,"p":462,"l":"M","g":2,"k":"cond_dist","t":"Conditional distribution from joint density","a":730},
      {"c":6,"s":"P","n":47,"p":462,"l":"M","g":2,"k":"cond_dist","t":"Accident parameter: Poisson–gamma mixture"},
      {"c":6,"s":"P","n":48,"p":462,"l":"M","g":2,"k":"order","t":"Largest of three uniforms vs others"},
      {"c":6,"s":"P","n":49,"p":462,"l":"E","g":3,"k":"binom","t":"Machine with 3 of 5 motors working"},
      {"c":6,"s":"P","n":51,"p":462,"l":"M","g":2,"k":"order","t":"Median of 5 uniforms in an interval","a":730},
      {"c":6,"s":"P","n":52,"p":462,"l":"M","g":2,"k":"order","t":"Min/max of iid exponentials","a":730},
      {"c":6,"s":"P","n":56,"p":463,"l":"M","g":2,"k":"joint","t":"Point uniform in a circle: marginals","a":730},
      {"c":6,"s":"TE","n":9,"p":465,"l":"M","g":2,"k":"sumrv","t":"Min of iid exponentials"},
      {"c":6,"s":"TE","n":10,"p":465,"l":"M","g":2,"k":"sumrv","t":"Battery lifetimes: exponential race"},
      {"c":6,"s":"TE","n":14,"p":466,"l":"M","g":2,"k":"sumrv","t":"Sum of two geometrics: conditional distribution"},
      {"c":6,"s":"TE","n":16,"p":466,"l":"M","g":2,"k":"sumrv","t":"Sum of independent binomials (same p)"},
      {"c":6,"s":"TE","n":17,"p":466,"l":"M","g":2,"k":"cond_dist","t":"Poisson given sum is binomial"},
      {"c":6,"s":"TE","n":19,"p":467,"l":"M","g":2,"k":"order","t":"iid continuous: P(X1 < X2) etc. by symmetry"},
      {"c":6,"s":"TE","n":20,"p":467,"l":"M","g":2,"k":"cond_dist","t":"Uniform given conditions"},
      {"c":6,"s":"ST","n":1,"p":471,"l":"M","g":2,"k":"joint","t":"Unfair die: joint distribution of outcomes","o":774},
      {"c":6,"s":"ST","n":2,"p":471,"l":"E","g":3,"k":"joint","t":"Joint PMF: compute given probabilities","o":774},
      {"c":6,"s":"ST","n":3,"p":472,"l":"M","g":3,"k":"joint","t":"Joint density: find c, marginals, E[·]","o":775},
      {"c":6,"s":"ST","n":5,"p":472,"l":"E","g":2,"k":"sumrv","t":"PMF of X + Y for two-valued RVs","o":776},
      {"c":6,"s":"ST","n":6,"p":472,"l":"E","g":3,"k":"indep_rv","t":"Joint density: constant, independence","o":776},
      {"c":6,"s":"ST","n":7,"p":472,"l":"M","g":3,"k":"indep_rv","t":"Joint density: independence, marginals","o":777},
      {"c":6,"s":"ST","n":13,"p":475,"l":"M","g":2,"k":"normal","t":"NBA point differential: normal model","o":778},
      {"c":6,"s":"ST","n":15,"p":476,"l":"M","g":2,"k":"transform2","t":"Joint density of U + V and U − V","o":779},
      {"c":6,"s":"ST","n":16,"p":476,"l":"M","g":2,"k":"order","t":"Bidding against uniform bids","o":780},
      {"c":6,"s":"ST","n":20,"p":477,"l":"M","g":2,"k":"order","t":"iid continuous: ordering probabilities","o":781},
      {"c":7,"s":"P","n":1,"p":584,"l":"E","g":3,"k":"exp_var","t":"Die and coin game: expected winnings","a":730},
      {"c":7,"s":"P","n":3,"p":584,"l":"M","g":2,"k":"exp_var","t":"Net winnings of independent gambles","a":730},
      {"c":7,"s":"P","n":4,"p":585,"l":"E","g":3,"k":"joint","t":"E[g(X,Y)] from a joint density","a":730},
      {"c":7,"s":"P","n":5,"p":585,"l":"M","g":2,"k":"joint","t":"Hospital in a square: expected distance","a":731},
      {"c":7,"s":"P","n":6,"p":585,"l":"E","g":3,"k":"lin_exp","t":"Expected sum of 10 die rolls","a":731},
      {"c":7,"s":"P","n":7,"p":585,"l":"E","g":3,"k":"lin_exp","t":"Two people pick 3 of 10 objects: expected overlaps","a":731},
      {"c":7,"s":"P","n":8,"p":585,"l":"M","g":2,"k":"lin_exp","t":"Dinner arrivals: expected new tables","a":731},
      {"c":7,"s":"P","n":9,"p":585,"l":"M","g":3,"k":"lin_exp","t":"Balls into urns: expected empty urns"},
      {"c":7,"s":"P","n":10,"p":585,"l":"M","g":2,"k":"lin_exp","t":"Three trials: E and Var of successes","a":731},
      {"c":7,"s":"P","n":11,"p":586,"l":"M","g":3,"k":"lin_exp","t":"Expected number of changeovers in coin flips","a":731},
      {"c":7,"s":"P","n":12,"p":586,"l":"M","g":3,"k":"lin_exp","t":"Men with a woman next to them (indicators)","a":731},
      {"c":7,"s":"P","n":13,"p":586,"l":"M","g":2,"k":"lin_exp","t":"Cards: expected people whose card beats theirs"},
      {"c":7,"s":"P","n":15,"p":587,"l":"M","g":2,"k":"lin_exp","t":"Hat matching: expected matched pairs","a":731},
      {"c":7,"s":"P","n":17,"p":587,"l":"M","g":2,"k":"lin_exp","t":"Shuffled deck: expected guesses correct"},
      {"c":7,"s":"P","n":18,"p":588,"l":"M","g":2,"k":"lin_exp","t":"Card turns: expected matches with position","a":731},
      {"c":7,"s":"P","n":19,"p":588,"l":"M","g":2,"k":"lin_exp","t":"Insect types: expected types caught"},
      {"c":7,"s":"P","n":21,"p":588,"l":"M","g":3,"k":"lin_exp","t":"Birthdays of exactly 3 people: expected days","a":731},
      {"c":7,"s":"P","n":22,"p":588,"l":"M","g":3,"k":"lin_exp","t":"Rolls until all 6 faces (coupon collector)","a":731},
      {"c":7,"s":"P","n":23,"p":588,"l":"M","g":2,"k":"lin_exp","t":"Two urns: expected white balls selected","a":731},
      {"c":7,"s":"P","n":26,"p":589,"l":"M","g":2,"k":"order","t":"E[max], E[min] of uniforms","a":731},
      {"c":7,"s":"P","n":30,"p":590,"l":"H","g":2,"k":"exp_var","t":"E[(X − Y)²] for iid variables","x":1},
      {"c":7,"s":"P","n":31,"p":590,"l":"E","g":3,"k":"cov","t":"Variance of sum of 10 die rolls","a":731},
      {"c":7,"s":"P","n":32,"p":590,"l":"M","g":2,"k":"cov","t":"Variance of number of empty urns"},
      {"c":7,"s":"P","n":33,"p":590,"l":"E","g":3,"k":"cov","t":"E[(2 + X)²], Var(4 + 3X)","a":731},
      {"c":7,"s":"P","n":34,"p":590,"l":"H","g":2,"k":"cov","t":"Couples at round table: E and Var of adjacent pairs","a":731},
      {"c":7,"s":"P","n":35,"p":590,"l":"M","g":2,"k":"lin_exp","t":"Cards until first ace: expectation","a":731},
      {"c":7,"s":"P","n":36,"p":590,"l":"M","g":3,"k":"cov","t":"Cov of number of 1s and 2s in die rolls","a":731},
      {"c":7,"s":"P","n":37,"p":590,"l":"E","g":3,"k":"cov","t":"Cov of sum and difference of two dice","a":731},
      {"c":7,"s":"P","n":38,"p":590,"l":"M","g":3,"k":"cov","t":"Joint PMF table: covariance","a":731},
      {"c":7,"s":"P","n":39,"p":591,"l":"M","g":2,"k":"cov","t":"Indicators of red draws: covariance"},
      {"c":7,"s":"P","n":40,"p":591,"l":"M","g":2,"k":"cov","t":"Covariance from a joint density","a":731},
      {"c":7,"s":"P","n":41,"p":591,"l":"M","g":3,"k":"cov","t":"Cov/Var of partial sums of iid variables"},
      {"c":7,"s":"P","n":42,"p":591,"l":"M","g":2,"k":"cov","t":"Joint density: Cov(X, Y)"},
      {"c":7,"s":"P","n":43,"p":591,"l":"M","g":3,"k":"hyper","t":"Pond fish: mean and variance of carp caught","a":731},
      {"c":7,"s":"P","n":44,"p":591,"l":"M","g":2,"k":"cov","t":"Random pairing: E and Var of mixed pairs","a":731},
      {"c":7,"s":"P","n":47,"p":592,"l":"M","g":3,"k":"cov","t":"Correlation of linear combinations","a":731},
      {"c":7,"s":"P","n":50,"p":593,"l":"M","g":2,"k":"cond_exp","t":"Rolls until 6 given info about 5","a":731},
      {"c":7,"s":"P","n":51,"p":593,"l":"M","g":2,"k":"cond_exp","t":"Two misshapen coins: expected flips","a":731},
      {"c":7,"s":"P","n":52,"p":593,"l":"M","g":3,"k":"cond_exp","t":"E[X | Y] from a joint density","a":731},
      {"c":7,"s":"P","n":53,"p":593,"l":"M","g":3,"k":"cond_exp","t":"E[X | Y] from a joint density","a":731},
      {"c":7,"s":"P","n":54,"p":593,"l":"M","g":2,"k":"cond_exp","t":"Subgroups: law of total expectation"},
      {"c":7,"s":"P","n":55,"p":594,"l":"M","g":3,"k":"cond_exp","t":"Prisoner with 3 doors: expected time","a":731},
      {"c":7,"s":"P","n":56,"p":594,"l":"M","g":2,"k":"cond_exp","t":"Dice game: expected winnings by conditioning","a":731},
      {"c":7,"s":"P","n":57,"p":594,"l":"M","g":2,"k":"lin_exp","t":"Ducks shot: expected survivors"},
      {"c":7,"s":"P","n":58,"p":594,"l":"M","g":2,"k":"cond_exp","t":"Elevator: expected stops (Poisson people)","a":731},
      {"c":7,"s":"P","n":59,"p":594,"l":"M","g":3,"k":"cond_exp","t":"Random sum: expected injured workers","a":731},
      {"c":7,"s":"P","n":60,"p":594,"l":"M","g":2,"k":"cond_exp","t":"Flip until both heads and tails appear"},
      {"c":7,"s":"P","n":64,"p":596,"l":"M","g":2,"k":"cond_exp","t":"Goals given win/loss: Poisson mixture","a":731},
      {"c":7,"s":"P","n":68,"p":597,"l":"M","g":2,"k":"cond_exp","t":"Balls drawn: E[red] given blue count","a":731},
      {"c":7,"s":"P","n":69,"p":598,"l":"M","g":3,"k":"cond_exp","t":"Light bulb types: mean and variance (total variance)"},
      {"c":7,"s":"P","n":70,"p":598,"l":"M","g":3,"k":"cond_exp","t":"Winter storms: good/bad year mixture","a":732},
      {"c":7,"s":"P","n":71,"p":598,"l":"M","g":2,"k":"cond_exp","t":"Miner: variance of time to safety","a":732},
      {"c":7,"s":"P","n":73,"p":598,"l":"M","g":2,"k":"cond_exp","t":"Accidents with random rate: mean, variance"},
      {"c":7,"s":"P","n":75,"p":598,"l":"M","g":2,"k":"cond_exp","t":"Coins with random p: P(heads)","a":732},
      {"c":7,"s":"P","n":78,"p":599,"l":"M","g":2,"k":"cond_exp","t":"Signal received: prediction (normal)","a":732},
      {"c":7,"s":"P","n":80,"p":599,"l":"M","g":2,"k":"mgf","t":"MGFs of independent X and Y: sum"},
      {"c":7,"s":"TE","n":1,"p":601,"l":"M","g":2,"k":"exp_var","t":"E[(X − c)²] minimised at c = mean"},
      {"c":7,"s":"TE","n":2,"p":601,"l":"M","g":2,"k":"exp_var","t":"E|X − c| minimised at the median"},
      {"c":7,"s":"TE","n":10,"p":603,"l":"M","g":2,"k":"lin_exp","t":"Expected number of runs in coin flips"},
      {"c":7,"s":"TE","n":16,"p":604,"l":"M","g":2,"k":"cov","t":"Variance of successes with different p_i"},
      {"c":7,"s":"TE","n":26,"p":606,"l":"M","g":2,"k":"cond_exp","t":"E[X | Y] = E[X] when independent"},
      {"c":7,"s":"TE","n":28,"p":606,"l":"M","g":2,"k":"cov","t":"E[X|Y] = E[X] implies uncorrelated (not converse)"},
      {"c":7,"s":"TE","n":30,"p":606,"l":"M","g":2,"k":"cond_exp","t":"E[X1 | X1 + … + Xn] for iid"},
      {"c":7,"s":"TE","n":34,"p":606,"l":"M","g":2,"k":"cond_exp","t":"Expected flips until two heads in a row"},
      {"c":7,"s":"TE","n":39,"p":608,"l":"M","g":2,"k":"cond_exp","t":"Best linear predictor"},
      {"c":7,"s":"TE","n":41,"p":608,"l":"M","g":2,"k":"cond_exp","t":"Geometric variance via conditional variance"},
      {"c":7,"s":"TE","n":49,"p":610,"l":"E","g":2,"k":"mgf","t":"MGF of aX + b"},
      {"c":7,"s":"ST","n":2,"p":611,"l":"M","g":3,"k":"lin_exp","t":"Black balls: expected white-to-black changes","o":784},
      {"c":7,"s":"ST","n":3,"p":611,"l":"M","g":2,"k":"lin_exp","t":"Couples at tables: expected couples together","o":785},
      {"c":7,"s":"ST","n":4,"p":611,"l":"M","g":2,"k":"cond_exp","t":"Rolls until all sides: expected number of 1s","o":786},
      {"c":7,"s":"ST","n":13,"p":613,"l":"M","g":2,"k":"lin_exp","t":"Basketball pairing by position","o":790},
      {"c":7,"s":"ST","n":14,"p":613,"l":"M","g":2,"k":"cov","t":"Aces and spades in a bridge hand: covariance","o":791},
      {"c":7,"s":"ST","n":15,"p":613,"l":"M","g":2,"k":"cond_exp","t":"Coin values: expected value of heads","o":792},
      {"c":7,"s":"ST","n":17,"p":613,"l":"M","g":2,"k":"cov","t":"Items into cells: covariance of counts","o":792},
      {"c":7,"s":"ST","n":18,"p":613,"l":"M","g":2,"k":"lin_exp","t":"Initial run length: expectation","o":793},
      {"c":7,"s":"ST","n":24,"p":615,"l":"E","g":3,"k":"cov","t":"Aces in 3 cards: E, Var","o":796},
      {"c":7,"s":"ST","n":29,"p":616,"l":"M","g":2,"k":"indep","t":"Bernoulli: independent iff uncorrelated","o":800},
      {"c":7,"s":"ST","n":33,"p":616,"l":"M","g":2,"k":"cov","t":"max + min = X + Y: covariance","o":801},
      {"c":8,"s":"P","n":1,"p":660,"l":"E","g":3,"k":"ineq","t":"Markov/Chebyshev bounds from mean and variance","a":732},
      {"c":8,"s":"P","n":2,"p":660,"l":"E","g":3,"k":"ineq","t":"Exam scores: Markov and Chebyshev bounds","a":732},
      {"c":8,"s":"P","n":3,"p":660,"l":"E","g":3,"k":"clt","t":"CLT for average exam score","a":732},
      {"c":8,"s":"P","n":4,"p":660,"l":"M","g":3,"k":"clt","t":"Sum of Poissons: Markov vs CLT","a":732},
      {"c":8,"s":"P","n":5,"p":661,"l":"M","g":3,"k":"clt","t":"Round-off errors: CLT for sum of uniforms","a":732},
      {"c":8,"s":"P","n":7,"p":661,"l":"M","g":3,"k":"clt","t":"100 bulbs, exponential lifetimes: CLT","a":732},
      {"c":8,"s":"P","n":8,"p":661,"l":"M","g":2,"k":"clt","t":"Bulbs with random replacement time","a":732},
      {"c":8,"s":"P","n":10,"p":661,"l":"M","g":2,"k":"clt","t":"Bridge load: CLT for total weight","a":732},
      {"c":8,"s":"P","n":11,"p":661,"l":"M","g":2,"k":"clt","t":"Stock daily changes: CLT","a":732},
      {"c":8,"s":"P","n":12,"p":661,"l":"M","g":2,"k":"clt","t":"Sequential components: total lifetime"},
      {"c":8,"s":"P","n":13,"p":662,"l":"M","g":3,"k":"clt","t":"Class average: CLT, two classes","a":732},
      {"c":8,"s":"P","n":14,"p":662,"l":"M","g":2,"k":"clt","t":"Spare parts: CLT","a":732},
      {"c":8,"s":"P","n":15,"p":662,"l":"E","g":3,"k":"clt","t":"Insurance: total claims via CLT"},
      {"c":8,"s":"P","n":16,"p":662,"l":"M","g":2,"k":"clt","t":"Jobs in sequence: CLT with deadline","a":732},
      {"c":8,"s":"P","n":18,"p":663,"l":"E","g":3,"k":"ineq","t":"Chebyshev with known variance","a":732},
      {"c":8,"s":"P","n":20,"p":663,"l":"M","g":2,"k":"ineq","t":"Markov/Jensen with mean 25"},
      {"c":8,"s":"P","n":23,"p":663,"l":"M","g":3,"k":"ineq","t":"Poisson(20): Markov vs one-sided Chebyshev vs CLT","a":732},
      {"c":8,"s":"P","n":24,"p":663,"l":"M","g":2,"k":"clt","t":"Poisson(100): normal approximation choice","a":732},
      {"c":8,"s":"TE","n":7,"p":666,"l":"M","g":2,"k":"clt","t":"Product of 100 die rolls: CLT on logs"},
      {"c":8,"s":"TE","n":9,"p":666,"l":"E","g":2,"k":"clt","t":"Gambler's fallacy: 1000 tosses"},
      {"c":8,"s":"ST","n":1,"p":668,"l":"E","g":3,"k":"ineq","t":"Car sales: Markov bound","o":802},
      {"c":8,"s":"ST","n":2,"p":668,"l":"E","g":3,"k":"ineq","t":"Car sales with variance: Chebyshev","o":802},
      {"c":8,"s":"ST","n":3,"p":668,"l":"E","g":2,"k":"ineq","t":"Upper bounds from given moments","o":802},
      {"c":8,"s":"ST","n":4,"p":668,"l":"M","g":3,"k":"clt","t":"Two factories: difference via CLT","o":802},
      {"c":8,"s":"ST","n":5,"p":668,"l":"M","g":2,"k":"clt","t":"Component lifetimes: total via CLT","o":802},
      {"c":8,"s":"ST","n":6,"p":669,"l":"M","g":2,"k":"clt","t":"How many components for 90% certainty","o":803},
      {"c":8,"s":"ST","n":7,"p":669,"l":"M","g":2,"k":"clt","t":"Two-step servicing: CLT","o":803},
      {"c":8,"s":"ST","n":8,"p":669,"l":"E","g":3,"k":"clt","t":"Gambler's total winnings via CLT","o":804},
      {"c":8,"s":"ST","n":9,"p":669,"l":"M","g":2,"k":"clt","t":"Deadline for repairs via CLT","o":804},
      {"c":8,"s":"ST","n":10,"p":669,"l":"E","g":3,"k":"clt","t":"Nicotine claim: is it believable?","o":804},
      {"c":8,"s":"ST","n":11,"p":669,"l":"M","g":2,"k":"clt","t":"Batteries of two types: total life","o":804},
      {"c":8,"s":"ST","n":14,"p":670,"l":"E","g":3,"k":"clt","t":"Book processing time: CLT","o":807},
      {"c":9,"s":"P","n":12,"p":697,"l":"E","g":3,"k":"entropy","t":"Entropy of the sum of two dice"},
      {"c":9,"s":"P","n":13,"p":697,"l":"M","g":3,"k":"entropy","t":"Entropy is maximised by the uniform distribution"},
      {"c":9,"s":"P","n":14,"p":697,"l":"M","g":3,"k":"entropy","t":"Joint and conditional entropy of dice","a":732},
      {"c":9,"s":"P","n":15,"p":697,"l":"E","g":3,"k":"entropy","t":"Entropy of 6 coin flips","a":732},
      {"c":9,"s":"ST","n":5,"p":698,"l":"E","g":3,"k":"entropy","t":"Entropy of a 5-valued distribution","o":810}
    ]
  },
  {
    id: "rossips", title: "Sheldon Ross — Introduction to Probability and Statistics for Engineers and Scientists (5th ed)", short: "Ross · Prob & Stats for Engineers", subj: "ps",
    chapters: {2: "Descriptive Statistics", 3: "Elements of Probability", 4: "Random Variables and Expectation", 5: "Special Random Variables", 6: "Distributions of Sampling Statistics", 7: "Parameter Estimation", 8: "Hypothesis Testing", 9: "Regression", 11: "Goodness of Fit and Categorical Data"},
    notes: "Only GATE-relevant problems are listed. Skipped: Ch 1, 10 (ANOVA), 12–15 (nonparametric, quality control, reliability, simulation). Answers are in the Instructor's Manual at the start of your PDF (page shown).",
    q: [
      {"c":2,"s":"P","n":8,"p":110,"l":"M","g":2,"k":"desc","t":"Comparing sample means of two towns (weighting)","a":12},
      {"c":2,"s":"P","n":9,"p":111,"l":"E","g":2,"k":"desc","t":"Sample mean & median from a table"},
      {"c":2,"s":"P","n":10,"p":111,"l":"M","g":2,"k":"desc","t":"Average pay across companies (weighted mean)","a":12},
      {"c":2,"s":"P","n":11,"p":111,"l":"E","g":3,"k":"desc","t":"Combined sample mean of two groups","a":12},
      {"c":2,"s":"P","n":13,"p":112,"l":"E","g":3,"k":"desc","t":"Ash data: mean, median, standard deviation","a":12},
      {"c":2,"s":"P","n":14,"p":112,"l":"M","g":3,"k":"desc","t":"Recover missing values from mean and variance","a":13},
      {"c":2,"s":"P","n":15,"p":112,"l":"M","g":2,"k":"desc","t":"Average of state averages vs national average","a":13},
      {"c":2,"s":"P","n":16,"p":112,"l":"E","g":2,"k":"desc","t":"Transistor lifetimes: summary statistics"},
      {"c":2,"s":"P","n":18,"p":113,"l":"M","g":2,"k":"desc","t":"Efficient formula for sample variance"},
      {"c":2,"s":"P","n":19,"p":113,"l":"E","g":2,"k":"desc","t":"Percentiles from data","a":13},
      {"c":2,"s":"P","n":20,"p":114,"l":"E","g":3,"k":"desc","t":"Quartiles of ages","a":13},
      {"c":2,"s":"P","n":26,"p":115,"l":"E","g":2,"k":"desc","t":"GPA data: mean, SD, Chebyshev proportions","a":13},
      {"c":2,"s":"P","n":29,"p":116,"l":"E","g":2,"k":"desc","t":"Mean, median, SD and normality check"},
      {"c":2,"s":"P","n":30,"p":116,"l":"M","g":3,"k":"desc","t":"Sample correlation: height vs salary","a":13},
      {"c":2,"s":"P","n":33,"p":117,"l":"M","g":3,"k":"desc","t":"Sample correlation: study hours vs GPA","a":13},
      {"c":2,"s":"P","n":34,"p":117,"l":"M","g":2,"k":"desc","t":"Correlation unchanged by linear transformation","a":14},
      {"c":2,"s":"P","n":35,"p":117,"l":"M","g":2,"k":"desc","t":"Correlation sign under scaling","a":14},
      {"c":2,"s":"P","n":37,"p":117,"l":"E","g":2,"k":"desc","t":"Correlation does not imply causation","a":14},
      {"c":3,"s":"P","n":12,"p":146,"l":"M","g":2,"k":"axioms","t":"Bonferroni: P(EF) ≥ P(E) + P(F) − 1","a":15},
      {"c":3,"s":"P","n":14,"p":146,"l":"E","g":2,"k":"axioms","t":"Exactly one of E or F occurs","a":16},
      {"c":3,"s":"P","n":18,"p":146,"l":"M","g":2,"k":"prob_classic","t":"Boys and girls lined up at random","a":16},
      {"c":3,"s":"P","n":21,"p":146,"l":"E","g":3,"k":"total","t":"A then B: total probability","a":16},
      {"c":3,"s":"P","n":23,"p":147,"l":"E","g":3,"k":"bayes","t":"Three painted cards: other side red","a":16},
      {"c":3,"s":"P","n":24,"p":147,"l":"E","g":3,"k":"cond","t":"Both girls given eldest is a girl","a":16},
      {"c":3,"s":"P","n":25,"p":147,"l":"M","g":3,"k":"cond","t":"Female given CS major","a":17},
      {"c":3,"s":"P","n":26,"p":147,"l":"M","g":3,"k":"cond","t":"Salary table: conditional probabilities","a":17},
      {"c":3,"s":"P","n":27,"p":148,"l":"M","g":3,"k":"bayes","t":"Defective microwave: which factory","a":17},
      {"c":3,"s":"P","n":29,"p":148,"l":"E","g":3,"k":"bayes","t":"Plant watering: neighbour forgot","a":17},
      {"c":3,"s":"P","n":31,"p":148,"l":"M","g":3,"k":"bayes","t":"Retirement community: party given voted","a":18},
      {"c":3,"s":"P","n":33,"p":149,"l":"E","g":3,"k":"bayes","t":"Cabinets with coins","a":18},
      {"c":3,"s":"P","n":34,"p":149,"l":"M","g":3,"k":"bayes","t":"Prostate test: cancer given result","a":18},
      {"c":3,"s":"P","n":35,"p":149,"l":"M","g":3,"k":"bayes","t":"Insurance risk class given accident","a":18},
      {"c":3,"s":"P","n":36,"p":149,"l":"M","g":3,"k":"indep","t":"Sum 7 independent of first die","a":18},
      {"c":3,"s":"P","n":37,"p":149,"l":"M","g":2,"k":"indep","t":"Relay circuit reliability (figure)","a":18},
      {"c":3,"s":"P","n":38,"p":150,"l":"M","g":2,"k":"indep","t":"k-out-of-n system","a":18},
      {"c":3,"s":"P","n":39,"p":150,"l":"E","g":2,"k":"indep","t":"Five coin flips: events","a":19},
      {"c":3,"s":"P","n":41,"p":150,"l":"E","g":3,"k":"indep","t":"Parallel system reliability","a":19},
      {"c":3,"s":"P","n":47,"p":152,"l":"E","g":3,"k":"axioms","t":"At least one of A, B: independent vs exclusive","a":20},
      {"c":3,"s":"P","n":48,"p":152,"l":"M","g":3,"k":"bayes","t":"Mammogram: cancer given positive","a":20},
      {"c":3,"s":"P","n":50,"p":152,"l":"E","g":3,"k":"total","t":"A then B: total probability","a":20},
      {"c":4,"s":"P","n":4,"p":195,"l":"E","g":3,"k":"cdf","t":"Probabilities from a mixed CDF","a":21},
      {"c":4,"s":"P","n":5,"p":195,"l":"E","g":3,"k":"cont_pdf","t":"Find c of a PDF and probabilities","a":21},
      {"c":4,"s":"P","n":6,"p":196,"l":"E","g":3,"k":"cont_pdf","t":"Computer lifetime PDF","a":21},
      {"c":4,"s":"P","n":8,"p":196,"l":"E","g":3,"k":"cont_pdf","t":"Find c and P(X > 2)","a":21},
      {"c":4,"s":"P","n":10,"p":196,"l":"M","g":3,"k":"joint","t":"Joint density: verify, marginal, probabilities","a":21},
      {"c":4,"s":"P","n":12,"p":197,"l":"M","g":3,"k":"joint","t":"Joint density: marginals and independence","a":22},
      {"c":4,"s":"P","n":13,"p":197,"l":"M","g":3,"k":"joint","t":"Joint density on a triangle","a":22},
      {"c":4,"s":"P","n":19,"p":198,"l":"M","g":3,"k":"cond_dist","t":"Conditional density of X given Y","a":22},
      {"c":4,"s":"P","n":21,"p":198,"l":"E","g":2,"k":"exp_var","t":"Expected value of a discrete RV","a":22},
      {"c":4,"s":"P","n":22,"p":198,"l":"E","g":2,"k":"exp_var","t":"Expected value from a PMF","a":22},
      {"c":4,"s":"P","n":25,"p":198,"l":"M","g":3,"k":"exp_var","t":"Bus students: E[X] vs E[Y]","a":23},
      {"c":4,"s":"P","n":27,"p":199,"l":"E","g":3,"k":"cont_pdf","t":"Find a, b from PDF and E[X]","a":23},
      {"c":4,"s":"P","n":29,"p":199,"l":"M","g":2,"k":"order","t":"E[max] of uniforms","a":23},
      {"c":4,"s":"P","n":30,"p":199,"l":"E","g":2,"k":"cont_pdf","t":"E[X^n] two ways","a":23},
      {"c":4,"s":"P","n":32,"p":199,"l":"E","g":3,"k":"exp_var","t":"E[(2 + 4X)²] from moments","a":24},
      {"c":4,"s":"P","n":33,"p":199,"l":"M","g":2,"k":"hyper","t":"Expected number of white balls chosen","a":24},
      {"c":4,"s":"P","n":34,"p":200,"l":"E","g":3,"k":"cont_pdf","t":"Median of a continuous distribution","a":24},
      {"c":4,"s":"P","n":36,"p":200,"l":"E","g":2,"k":"cont_pdf","t":"Percentile of a distribution","a":24},
      {"c":4,"s":"P","n":38,"p":201,"l":"E","g":2,"k":"binom","t":"Mean and variance of number of successes","a":24},
      {"c":4,"s":"P","n":39,"p":201,"l":"E","g":3,"k":"exp_var","t":"Discrete uniform: mean and variance","a":24},
      {"c":4,"s":"P","n":40,"p":201,"l":"M","g":2,"k":"exp_var","t":"Maximise/minimise variance given the mean","a":25},
      {"c":4,"s":"P","n":41,"p":201,"l":"E","g":2,"k":"binom","t":"Heads in 3 flips: mean and variance","a":25},
      {"c":4,"s":"P","n":42,"p":201,"l":"M","g":2,"k":"exp_var","t":"E[X²] ≥ (E[X])²","a":25},
      {"c":4,"s":"P","n":44,"p":201,"l":"M","g":3,"k":"cov","t":"Joint density: covariance","a":25},
      {"c":4,"s":"P","n":45,"p":202,"l":"M","g":3,"k":"cov","t":"Joint PMF table: covariance","a":25},
      {"c":4,"s":"P","n":46,"p":202,"l":"M","g":3,"k":"cov","t":"Correlation of vote shares","a":25},
      {"c":4,"s":"P","n":49,"p":202,"l":"M","g":2,"k":"cov","t":"Proof that −1 ≤ Corr ≤ 1","a":26},
      {"c":4,"s":"P","n":52,"p":203,"l":"M","g":3,"k":"cov","t":"Cov(X1 − X2, X1 + X2) = 0","a":27},
      {"c":4,"s":"P","n":55,"p":203,"l":"E","g":3,"k":"ineq","t":"Chebyshev bound for P(0 ≤ X ≤ 40)","a":27},
      {"c":4,"s":"P","n":56,"p":204,"l":"E","g":3,"k":"ineq","t":"Exam score: Markov and Chebyshev","a":27},
      {"c":4,"s":"P","n":57,"p":204,"l":"M","g":2,"k":"exp_var","t":"Location-scale: E and Var","a":27},
      {"c":5,"s":"P","n":1,"p":261,"l":"E","g":3,"k":"binom","t":"Satellite: at least 2 of 4 work","a":28},
      {"c":5,"s":"P","n":2,"p":261,"l":"M","g":2,"k":"binom","t":"Channel errors with repetition","a":28},
      {"c":5,"s":"P","n":3,"p":262,"l":"E","g":3,"k":"binom","t":"Exactly 7 of 10 voters","a":28},
      {"c":5,"s":"P","n":5,"p":262,"l":"M","g":2,"k":"binom","t":"Airplane engines: 2 vs 4 engines","a":28},
      {"c":5,"s":"P","n":6,"p":262,"l":"E","g":3,"k":"binom","t":"Binomial from mean and variance","a":28},
      {"c":5,"s":"P","n":10,"p":263,"l":"M","g":2,"k":"pois","t":"Poisson vs binomial approximations","a":28},
      {"c":5,"s":"P","n":11,"p":263,"l":"E","g":3,"k":"pois","t":"Lottery wins: Poisson approximation","a":29},
      {"c":5,"s":"P","n":12,"p":263,"l":"M","g":3,"k":"pois","t":"Cold drug: Bayes with Poisson","a":29},
      {"c":5,"s":"P","n":16,"p":263,"l":"E","g":2,"k":"pois","t":"Transmission errors: Poisson approximation","a":29},
      {"c":5,"s":"P","n":17,"p":264,"l":"M","g":2,"k":"pois","t":"Mode of the Poisson","a":29},
      {"c":5,"s":"P","n":18,"p":264,"l":"M","g":3,"k":"hyper","t":"Transistor shipment acceptance","a":29},
      {"c":5,"s":"P","n":20,"p":264,"l":"E","g":2,"k":"geom","t":"First success: geometric","a":29},
      {"c":5,"s":"P","n":22,"p":265,"l":"E","g":3,"k":"unif","t":"Bus stop: uniform waiting time","a":29},
      {"c":5,"s":"P","n":23,"p":265,"l":"E","g":3,"k":"normal","t":"Normal probabilities, μ = 10, σ² = 36","a":29},
      {"c":5,"s":"P","n":24,"p":265,"l":"E","g":3,"k":"normal","t":"SAT scores: normal probabilities","a":29},
      {"c":5,"s":"P","n":25,"p":265,"l":"E","g":2,"k":"normal","t":"Rainfall: normal probabilities","a":29},
      {"c":5,"s":"P","n":26,"p":265,"l":"E","g":3,"k":"normal","t":"Weekly demand: stock to meet demand","a":30},
      {"c":5,"s":"P","n":28,"p":265,"l":"E","g":3,"k":"normal","t":"Bolts within specification","a":30},
      {"c":5,"s":"P","n":31,"p":266,"l":"M","g":3,"k":"normal","t":"Salaries: μ and σ from percentiles","a":30},
      {"c":5,"s":"P","n":32,"p":266,"l":"E","g":3,"k":"normal","t":"Compare exam performance by z-scores","a":31},
      {"c":5,"s":"P","n":34,"p":267,"l":"E","g":2,"k":"normal","t":"Rainfall: normal probabilities","a":31},
      {"c":5,"s":"P","n":35,"p":267,"l":"E","g":2,"k":"normal","t":"Heights: normal probabilities","a":31},
      {"c":5,"s":"P","n":36,"p":267,"l":"E","g":3,"k":"normal","t":"IQ: cut-off for top 1 percent","a":31},
      {"c":5,"s":"P","n":37,"p":267,"l":"E","g":3,"k":"expo","t":"Repair time: exponential","a":31},
      {"c":5,"s":"P","n":38,"p":267,"l":"E","g":3,"k":"expo","t":"Used radio: memoryless property","a":31},
      {"c":5,"s":"P","n":39,"p":267,"l":"M","g":3,"k":"expo","t":"Car miles: exponential, memoryless","a":31},
      {"c":5,"s":"P","n":42,"p":268,"l":"M","g":2,"k":"tchi","t":"Miss distance: chi-square with 2 df","a":32},
      {"c":5,"s":"P","n":43,"p":268,"l":"E","g":3,"k":"tchi","t":"Chi-square (6 df) probabilities","a":32},
      {"c":5,"s":"P","n":44,"p":268,"l":"M","g":3,"k":"tchi","t":"Sum of independent chi-squares","a":32},
      {"c":5,"s":"P","n":46,"p":268,"l":"E","g":3,"k":"tchi","t":"t-distribution (8 df) probabilities","a":32},
      {"c":6,"s":"P","n":1,"p":290,"l":"M","g":2,"k":"sampling","t":"Distribution of sample mean from a PMF","a":33},
      {"c":6,"s":"P","n":2,"p":290,"l":"E","g":3,"k":"clt","t":"Sum of 10 dice: CLT","a":33},
      {"c":6,"s":"P","n":3,"p":290,"l":"E","g":3,"k":"clt","t":"Sum of 16 uniforms: CLT","a":33},
      {"c":6,"s":"P","n":4,"p":290,"l":"E","g":2,"k":"clt","t":"Roulette winnings: CLT","a":33},
      {"c":6,"s":"P","n":5,"p":291,"l":"M","g":2,"k":"clt","t":"Snowfall total: CLT","a":33},
      {"c":6,"s":"P","n":6,"p":291,"l":"M","g":3,"k":"clt","t":"Round-off errors: CLT for uniforms","a":33},
      {"c":6,"s":"P","n":8,"p":291,"l":"M","g":2,"k":"clt","t":"Battery lifetimes: CLT","a":34},
      {"c":6,"s":"P","n":9,"p":291,"l":"E","g":3,"k":"clt","t":"Part lifetime: sample mean via CLT","a":34},
      {"c":6,"s":"P","n":10,"p":291,"l":"E","g":3,"k":"clt","t":"Nicotine claim: sample mean check","a":34},
      {"c":6,"s":"P","n":11,"p":291,"l":"E","g":3,"k":"clt","t":"Bulb lifetime: sample mean","a":34},
      {"c":6,"s":"P","n":12,"p":292,"l":"M","g":3,"k":"clt","t":"Two class sizes: sample means compared","a":34},
      {"c":6,"s":"P","n":13,"p":292,"l":"M","g":2,"k":"normal_approx","t":"Binomial exact vs normal approximation"},
      {"c":6,"s":"P","n":14,"p":292,"l":"E","g":3,"k":"normal_approx","t":"Defective chips: normal approximation","a":34},
      {"c":6,"s":"P","n":18,"p":294,"l":"M","g":3,"k":"sampling","t":"Thermostat: sample mean within bounds (normal)","a":34},
      {"c":6,"s":"P","n":19,"p":294,"l":"M","g":3,"k":"sampling","t":"Sample size for a required probability"},
      {"c":6,"s":"P","n":20,"p":294,"l":"M","g":2,"k":"sampling","t":"Difference of two sample means","a":34},
      {"c":6,"s":"P","n":21,"p":294,"l":"E","g":3,"k":"normal_approx","t":"Left-handers between 10 and 14","a":35},
      {"c":6,"s":"P","n":22,"p":294,"l":"E","g":3,"k":"normal_approx","t":"Proportion in favour: normal approximation","a":35},
      {"c":6,"s":"P","n":24,"p":294,"l":"M","g":2,"k":"sampling","t":"Sample proportion from a table","a":35},
      {"c":6,"s":"P","n":25,"p":295,"l":"M","g":2,"k":"sampling","t":"Difference of two sample proportions","a":35},
      {"c":6,"s":"P","n":28,"p":295,"l":"M","g":3,"k":"sampling","t":"SAT: probability for a sample mean","a":35},
      {"c":6,"s":"P","n":29,"p":296,"l":"E","g":3,"k":"sampling","t":"Salary: sample mean exceeds a value","a":35},
      {"c":6,"s":"P","n":30,"p":296,"l":"M","g":2,"k":"clt","t":"Spare components needed (CLT)"},
      {"c":7,"s":"P","n":1,"p":347,"l":"M","g":2,"k":"mle","t":"MLE of a shift parameter","a":36},
      {"c":7,"s":"P","n":3,"p":347,"l":"M","g":2,"k":"mle","t":"MLE of σ² with known mean","a":36},
      {"c":7,"s":"P","n":8,"p":349,"l":"E","g":3,"k":"ci","t":"Electric scale: CI for weight (σ known)","a":37},
      {"c":7,"s":"P","n":9,"p":349,"l":"E","g":3,"k":"ci","t":"PCB measurement: CI, σ known","a":37},
      {"c":7,"s":"P","n":10,"p":349,"l":"E","g":3,"k":"ci","t":"Test scores: CI for mean, σ known","a":37},
      {"c":7,"s":"P","n":12,"p":349,"l":"M","g":2,"k":"ci","t":"Sample size for a given CI width","a":37},
      {"c":7,"s":"P","n":13,"p":349,"l":"E","g":3,"k":"ci","t":"Nicotine: 95% CI, σ known","a":38},
      {"c":7,"s":"P","n":14,"p":350,"l":"E","g":3,"k":"ci","t":"Nicotine: CI with σ unknown (t)","a":38},
      {"c":7,"s":"P","n":15,"p":350,"l":"M","g":3,"k":"ci","t":"One-sided 99% confidence bound","a":38},
      {"c":7,"s":"P","n":16,"p":350,"l":"M","g":2,"k":"ci","t":"Expected CI width with unknown variance","a":38},
      {"c":7,"s":"P","n":17,"p":350,"l":"E","g":3,"k":"ci","t":"Melting point: CI from data (t)","a":38},
      {"c":7,"s":"P","n":18,"p":350,"l":"E","g":3,"k":"ci","t":"IQ scores: CI from data","a":38},
      {"c":7,"s":"P","n":19,"p":350,"l":"E","g":3,"k":"ci","t":"House prices: t-based CI","a":38},
      {"c":7,"s":"P","n":20,"p":351,"l":"E","g":3,"k":"ci","t":"Repair cost: CI for mean","a":38},
      {"c":7,"s":"P","n":21,"p":351,"l":"E","g":3,"k":"ci","t":"Test scores: large-sample CI","a":38},
      {"c":7,"s":"P","n":22,"p":351,"l":"E","g":3,"k":"ci","t":"Melting point: CI from summary","a":38},
      {"c":7,"s":"P","n":23,"p":351,"l":"E","g":3,"k":"ci","t":"Card debt: large-sample CI","a":38},
      {"c":7,"s":"P","n":24,"p":351,"l":"M","g":3,"k":"ci","t":"One-sided 90% bound for debt","a":38},
      {"c":7,"s":"P","n":26,"p":351,"l":"E","g":3,"k":"ci","t":"Daily steps: CI from data","a":38},
      {"c":7,"s":"P","n":31,"p":352,"l":"E","g":3,"k":"ci","t":"Professors' salaries: CI","a":38},
      {"c":7,"s":"P","n":36,"p":353,"l":"M","g":2,"k":"ci","t":"Batteries: CI for variance (chi-square)","a":39},
      {"c":7,"s":"P","n":37,"p":353,"l":"M","g":2,"k":"ci","t":"Rivet diameter: CI for variance","a":39},
      {"c":7,"s":"P","n":38,"p":353,"l":"M","g":3,"k":"ci","t":"Two normal means, common σ: CI for difference","a":39},
      {"c":7,"s":"P","n":41,"p":354,"l":"M","g":2,"k":"ci","t":"Concrete strength: difference of means","a":39},
      {"c":7,"s":"P","n":42,"p":354,"l":"M","g":3,"k":"ci","t":"Two machines: CI for difference of means","a":39},
      {"c":7,"s":"P","n":43,"p":355,"l":"E","g":3,"k":"ci","t":"Same with known variances (z)","a":39},
      {"c":7,"s":"P","n":44,"p":355,"l":"M","g":2,"k":"ci","t":"Website visits: difference of means","a":39},
      {"c":7,"s":"P","n":48,"p":356,"l":"E","g":3,"k":"ci","t":"CI for proportions","a":39},
      {"c":7,"s":"P","n":49,"p":356,"l":"E","g":3,"k":"ci","t":"Proportion of male births: CI","a":39},
      {"c":7,"s":"P","n":50,"p":356,"l":"M","g":3,"k":"ci","t":"Sample size for a proportion","a":39},
      {"c":7,"s":"P","n":51,"p":356,"l":"M","g":3,"k":"ci","t":"Margin of error in a poll","a":39},
      {"c":7,"s":"P","n":52,"p":356,"l":"M","g":2,"k":"ci","t":"Proportion: sample size needed","a":39},
      {"c":7,"s":"P","n":53,"p":356,"l":"E","g":3,"k":"ci","t":"Meteorites: CI for proportion","a":39},
      {"c":7,"s":"P","n":54,"p":357,"l":"E","g":3,"k":"ci","t":"Defectives: 95% CI for proportion","a":39},
      {"c":7,"s":"P","n":55,"p":357,"l":"E","g":2,"k":"ci","t":"Lung cancer: proportion estimate and CI","a":39},
      {"c":7,"s":"P","n":61,"p":358,"l":"M","g":3,"k":"mle","t":"Compare estimators by mean squared error","a":40},
      {"c":8,"s":"P","n":1,"p":401,"l":"E","g":3,"k":"htest","t":"Jury analogy: null hypothesis, significance level","a":42},
      {"c":8,"s":"P","n":2,"p":401,"l":"E","g":3,"k":"htest","t":"Mice weights: z-test decision","a":42},
      {"c":8,"s":"P","n":3,"p":402,"l":"E","g":3,"k":"htest","t":"p-value of a z-test","a":42},
      {"c":8,"s":"P","n":4,"p":402,"l":"E","g":3,"k":"htest","t":"pH level: two-sided z-test","a":42},
      {"c":8,"s":"P","n":5,"p":402,"l":"E","g":3,"k":"htest","t":"Fiber strength: one-sided z-test","a":42},
      {"c":8,"s":"P","n":6,"p":402,"l":"E","g":3,"k":"htest","t":"Heights: z-test","a":42},
      {"c":8,"s":"P","n":7,"p":403,"l":"M","g":2,"k":"htest","t":"Sample size for a given power","a":42},
      {"c":8,"s":"P","n":9,"p":403,"l":"M","g":2,"k":"htest","t":"Drug test: one-sided test","a":43},
      {"c":8,"s":"P","n":10,"p":403,"l":"E","g":3,"k":"htest","t":"Salmon weights: z-test","a":43},
      {"c":8,"s":"P","n":11,"p":404,"l":"M","g":3,"k":"htest","t":"p-value for a one-sided z-test","a":43},
      {"c":8,"s":"P","n":12,"p":404,"l":"M","g":2,"k":"htest","t":"Toothpaste claim: test","a":43},
      {"c":8,"s":"P","n":13,"p":404,"l":"E","g":3,"k":"htest","t":"Phenobarbital: t-test","a":43},
      {"c":8,"s":"P","n":14,"p":404,"l":"E","g":3,"k":"htest","t":"Push-ups: t-test for a change in mean","a":43},
      {"c":8,"s":"P","n":15,"p":404,"l":"E","g":3,"k":"htest","t":"Response time: t-test","a":43},
      {"c":8,"s":"P","n":17,"p":404,"l":"M","g":2,"k":"htest","t":"Basal temperature: t-test","a":43},
      {"c":8,"s":"P","n":20,"p":405,"l":"E","g":3,"k":"htest","t":"Gas mileage claim: t-test","a":43},
      {"c":8,"s":"P","n":21,"p":405,"l":"E","g":3,"k":"htest","t":"Battery lifetime claim: t-test","a":44},
      {"c":8,"s":"P","n":23,"p":405,"l":"E","g":3,"k":"htest","t":"Sulfur content: one-sided t-test","a":44},
      {"c":8,"s":"P","n":24,"p":405,"l":"M","g":2,"k":"htest","t":"New plastic: test for improvement","a":44},
      {"c":8,"s":"P","n":25,"p":406,"l":"E","g":3,"k":"htest","t":"Transistor gain claim: t-test","a":44},
      {"c":8,"s":"P","n":26,"p":406,"l":"E","g":3,"k":"htest","t":"Capacitor voltage claim: t-test","a":44},
      {"c":8,"s":"P","n":27,"p":406,"l":"M","g":2,"k":"htest","t":"PCB in fish: t-test","a":44},
      {"c":8,"s":"P","n":28,"p":406,"l":"M","g":2,"k":"htest","t":"pH measurement: test","a":44},
      {"c":8,"s":"P","n":29,"p":407,"l":"M","g":3,"k":"htest","t":"Two samples: test equal means","a":44},
      {"c":8,"s":"P","n":30,"p":407,"l":"M","g":3,"k":"htest","t":"Electronic tubes: two-sample z-test","a":44},
      {"c":8,"s":"P","n":31,"p":408,"l":"M","g":3,"k":"htest","t":"Car oil viscosity: two-sample t-test","a":44},
      {"c":8,"s":"P","n":32,"p":408,"l":"M","g":2,"k":"htest","t":"Wire resistance: two-sample test","a":44},
      {"c":8,"s":"P","n":35,"p":409,"l":"M","g":2,"k":"htest","t":"Starting salaries: two-sample test","a":44},
      {"c":8,"s":"P","n":37,"p":410,"l":"M","g":3,"k":"htest","t":"Diet winter vs summer: paired t-test","a":44},
      {"c":8,"s":"P","n":39,"p":411,"l":"M","g":2,"k":"htest","t":"Lead in hair: two-sample test from summary","a":44},
      {"c":8,"s":"P","n":40,"p":411,"l":"M","g":2,"k":"htest","t":"Baby weights: two-sample test","a":44},
      {"c":8,"s":"P","n":42,"p":412,"l":"M","g":3,"k":"htest","t":"Blood pressure before/after: paired t-test","a":44},
      {"c":8,"s":"P","n":43,"p":412,"l":"M","g":3,"k":"htest","t":"Jogging and pulse: paired t-test","a":44},
      {"c":8,"s":"P","n":44,"p":412,"l":"M","g":2,"k":"htest","t":"Test for variance (chi-square)","a":44},
      {"c":8,"s":"P","n":47,"p":413,"l":"M","g":2,"k":"htest","t":"Drug weight SD: chi-square test for variance","a":45},
      {"c":8,"s":"P","n":52,"p":414,"l":"M","g":2,"k":"htest","t":"Aspirin study: test on proportions","a":45},
      {"c":8,"s":"P","n":54,"p":414,"l":"E","g":3,"k":"htest","t":"Drug effectiveness: test on a proportion","a":45},
      {"c":8,"s":"P","n":57,"p":415,"l":"E","g":3,"k":"htest","t":"Ambulance claim: proportion test","a":46},
      {"c":8,"s":"P","n":58,"p":415,"l":"M","g":2,"k":"htest","t":"Drug 75%: exact binomial test","a":46},
      {"c":8,"s":"P","n":59,"p":415,"l":"E","g":3,"k":"htest","t":"Same via normal approximation","a":46},
      {"c":8,"s":"P","n":71,"p":418,"l":"E","g":2,"k":"htest","t":"Smokers study: interpretation","a":47},
      {"c":9,"s":"P","n":1,"p":483,"l":"E","g":3,"k":"regression","t":"Fit a regression line to data","a":48},
      {"c":9,"s":"P","n":2,"p":483,"l":"E","g":3,"k":"regression","t":"Units ordered vs price: regression line","a":48},
      {"c":9,"s":"P","n":3,"p":483,"l":"E","g":2,"k":"regression","t":"Corrosion vs time: regression line","a":48},
      {"c":9,"s":"P","n":4,"p":484,"l":"E","g":3,"k":"regression","t":"Wood gravity vs strength: regression","a":48},
      {"c":9,"s":"P","n":5,"p":484,"l":"E","g":3,"k":"regression","t":"Reading speed vs weeks: regression","a":48},
      {"c":9,"s":"P","n":9,"p":487,"l":"M","g":2,"k":"regression","t":"Variance estimate and CI for slope","a":48},
      {"c":9,"s":"P","n":12,"p":487,"l":"M","g":3,"k":"regression","t":"Heights vs salaries: regression & prediction","a":49},
      {"c":9,"s":"P","n":13,"p":488,"l":"M","g":2,"k":"regression","t":"Regression to the mean"},
      {"c":9,"s":"P","n":15,"p":489,"l":"M","g":2,"k":"regression","t":"Praise and landings: regression to the mean","a":49},
      {"c":9,"s":"P","n":17,"p":489,"l":"E","g":2,"k":"regression","t":"Alignment errors vs rivets: regression","a":49},
      {"c":9,"s":"P","n":25,"p":491,"l":"M","g":2,"k":"regression","t":"Coefficient of determination R²"},
      {"c":9,"s":"P","n":27,"p":492,"l":"E","g":2,"k":"regression","t":"Age vs weight: regression and R²"},
      {"c":9,"s":"P","n":29,"p":493,"l":"M","g":3,"k":"regression","t":"Regression through the origin: estimator","a":49},
      {"c":9,"s":"P","n":30,"p":493,"l":"E","g":2,"k":"regression","t":"BMI vs blood pressure regression"},
      {"c":9,"s":"P","n":45,"p":499,"l":"M","g":3,"k":"mreg","t":"Fit multiple linear regression","a":50},
      {"c":9,"s":"P","n":47,"p":500,"l":"M","g":2,"k":"mreg","t":"Multiple regression: tests on coefficients","a":50},
      {"c":9,"s":"P","n":50,"p":502,"l":"M","g":2,"k":"mreg","t":"Prediction vs confidence interval","a":51},
      {"c":9,"s":"P","n":51,"p":502,"l":"M","g":2,"k":"mreg","t":"Multiple regression on a data set","a":51},
      {"c":9,"s":"P","n":56,"p":505,"l":"M","g":3,"k":"logreg","t":"Logistic regression: x where p(x) = 0.5"},
      {"c":9,"s":"P","n":57,"p":505,"l":"M","g":2,"k":"logreg","t":"Logistic regression on infant data"},
      {"c":9,"s":"P","n":58,"p":505,"l":"M","g":2,"k":"logreg","t":"Logistic regression: anger score"},
      {"c":11,"s":"P","n":1,"p":576,"l":"E","g":3,"k":"chisq","t":"Mendel peas: chi-square goodness of fit","a":55},
      {"c":11,"s":"P","n":2,"p":576,"l":"E","g":3,"k":"chisq","t":"Is the die fair? chi-square test","a":55},
      {"c":11,"s":"P","n":4,"p":577,"l":"M","g":2,"k":"chisq","t":"Power failures: Poisson fit","a":55},
      {"c":11,"s":"P","n":6,"p":577,"l":"E","g":3,"k":"chisq","t":"Machine grades: goodness of fit","a":55},
      {"c":11,"s":"P","n":9,"p":579,"l":"E","g":3,"k":"chisq","t":"Insurance accidents: goodness of fit","a":55},
      {"c":11,"s":"P","n":14,"p":579,"l":"M","g":2,"k":"chisq","t":"Test Poisson distribution for failures"},
      {"c":11,"s":"P","n":15,"p":579,"l":"M","g":3,"k":"chisq","t":"Region vs income: test of independence"},
      {"c":11,"s":"P","n":16,"p":580,"l":"M","g":3,"k":"chisq","t":"Maternal age vs birthweight: independence","a":55},
      {"c":11,"s":"P","n":17,"p":580,"l":"M","g":2,"k":"chisq","t":"Doubling data changes χ² statistic","a":55},
      {"c":11,"s":"P","n":19,"p":580,"l":"M","g":3,"k":"chisq","t":"Hypertension vs smoking: independence","a":55},
      {"c":11,"s":"P","n":20,"p":580,"l":"M","g":2,"k":"chisq","t":"Quality before/after: independence","a":55},
      {"c":11,"s":"P","n":21,"p":581,"l":"M","g":2,"k":"chisq","t":"Phones and accidents: contingency test","a":55},
      {"c":11,"s":"P","n":22,"p":581,"l":"M","g":2,"k":"chisq","t":"Fluoride and tooth decay: contingency test","a":55}
    ]
  }
];
PRACTICE_BOOKS.forEach(b => { b.patterns = PRACTICE_PATTERNS; });
