/* GATE DA previous-year questions (2024, 2025, 2026), from the official papers.
   References only: year, question number, PDF page of that year's paper, plus our tags.
   Fields: y year, n question number, p PDF page, m marks, ty type (MCQ/MSQ/NAT),
   tid syllabus topic, l level (E/M/H, our judgement), k matching practice pattern (or null), t short label (our words).
   Answer keys are not in these PDFs. */
const PYQ = {
  papers: {
    2024: { inst: "IISc Bengaluru", pages: 41 },
    2025: { inst: "IIT Roorkee", pages: 34 },
    2026: { inst: "IIT Guwahati", pages: 39 }
  },
  q: [
    {"y":2024,"n":1,"p":1,"m":1,"ty":"MCQ","tid":"ga1","l":"E","k":null,"t":"Word analogy by intensity"},
    {"y":2024,"n":2,"p":2,"m":1,"ty":"MCQ","tid":"ga3","l":"M","k":null,"t":"Colour the parts of a figure (adjacency)"},
    {"y":2024,"n":3,"p":3,"m":1,"ty":"MCQ","tid":"ga2","l":"M","k":null,"t":"4-digit numbers divisible by 3 from given digits"},
    {"y":2024,"n":4,"p":3,"m":1,"ty":"MCQ","tid":"ga2","l":"E","k":null,"t":"Sum of a mixed geometric series"},
    {"y":2024,"n":5,"p":4,"m":1,"ty":"MCQ","tid":"ga2","l":"E","k":null,"t":"Vote shares from a pie chart"},
    {"y":2024,"n":6,"p":5,"m":2,"ty":"MCQ","tid":"ga1","l":"M","k":null,"t":"Reading comprehension: inference"},
    {"y":2024,"n":7,"p":5,"m":2,"ty":"MCQ","tid":"ga2","l":"E","k":null,"t":"Probability for a family of three children"},
    {"y":2024,"n":8,"p":6,"m":2,"ty":"MCQ","tid":"ga2","l":"M","k":null,"t":"Data interpretation: mutual fund investments"},
    {"y":2024,"n":9,"p":7,"m":2,"ty":"MCQ","tid":"ga3","l":"M","k":null,"t":"Dice views: which paper folds into it"},
    {"y":2024,"n":10,"p":8,"m":2,"ty":"MCQ","tid":"ga3","l":"M","k":null,"t":"Two cones: visualise the solid"},
    {"y":2024,"n":11,"p":9,"m":1,"ty":"MCQ","tid":"ps5","l":"E","k":"pois","t":"Poisson mean = variance; standard normal facts"},
    {"y":2024,"n":12,"p":9,"m":1,"ty":"MCQ","tid":"ps2","l":"E","k":"prob_classic","t":"Three coins: P(T ∩ S)"},
    {"y":2024,"n":13,"p":10,"m":1,"ty":"MCQ","tid":"la5","l":"E","k":"la_eig","t":"Eigenvalues of a 2×2 matrix"},
    {"y":2024,"n":14,"p":10,"m":1,"ty":"MCQ","tid":"pd11","l":"M","k":null,"t":"DFS on undirected graph: edge property"},
    {"y":2024,"n":15,"p":11,"m":1,"ty":"MCQ","tid":"co5","l":"E","k":null,"t":"f′ = 0, f″ > 0 ⇒ local minimum"},
    {"y":2024,"n":16,"p":11,"m":1,"ty":"MCQ","tid":"pd3","l":"E","k":null,"t":"Match FIFO / LIFO / lookup to structures"},
    {"y":2024,"n":17,"p":12,"m":1,"ty":"MCQ","tid":"ml9","l":"M","k":null,"t":"Hard-margin SVM: support vectors of a dataset"},
    {"y":2024,"n":18,"p":12,"m":1,"ty":"MCQ","tid":"ml1","l":"E","k":null,"t":"Generative vs discriminative vs dimensionality reduction"},
    {"y":2024,"n":19,"p":13,"m":1,"ty":"MCQ","tid":"ml14","l":"M","k":null,"t":"k-means: which point must be in the same cluster"},
    {"y":2024,"n":20,"p":13,"m":1,"ty":"MCQ","tid":"ml7","l":"M","k":null,"t":"Parameter count of naive Bayes"},
    {"y":2024,"n":21,"p":14,"m":1,"ty":"MCQ","tid":"pd6","l":"M","k":null,"t":"Open addressing: expected probes to insert"},
    {"y":2024,"n":22,"p":14,"m":1,"ty":"MCQ","tid":"ml8","l":"H","k":null,"t":"Fisher LDA: optimal direction and eigenvalue"},
    {"y":2024,"n":23,"p":15,"m":1,"ty":"MCQ","tid":"ai3","l":"E","k":null,"t":"Which combination of admissible heuristics is admissible"},
    {"y":2024,"n":24,"p":15,"m":1,"ty":"MCQ","tid":"ai7","l":"M","k":"condind","t":"Bayes net factorisation: conditional independence"},
    {"y":2024,"n":25,"p":16,"m":1,"ty":"MCQ","tid":"ai4","l":"E","k":null,"t":"Alpha-beta pruning definitions"},
    {"y":2024,"n":26,"p":16,"m":1,"ty":"MCQ","tid":"db3","l":"M","k":null,"t":"Relational algebra: containment check"},
    {"y":2024,"n":27,"p":17,"m":1,"ty":"MCQ","tid":"db8","l":"E","k":null,"t":"Z-score normalisation of income"},
    {"y":2024,"n":28,"p":17,"m":1,"ty":"MSQ","tid":"pd5","l":"M","k":null,"t":"Which traversals reconstruct a full binary tree"},
    {"y":2024,"n":29,"p":18,"m":1,"ty":"MSQ","tid":"ai5","l":"E","k":null,"t":"Which formulas are tautologies"},
    {"y":2024,"n":30,"p":18,"m":1,"ty":"NAT","tid":"pd9","l":"M","k":null,"t":"Quicksort (last pivot): minimum swaps"},
    {"y":2024,"n":31,"p":19,"m":1,"ty":"NAT","tid":"db5","l":"M","k":null,"t":"SQL query result on two tables"},
    {"y":2024,"n":32,"p":20,"m":1,"ty":"NAT","tid":"pd3","l":"M","k":null,"t":"Deque operations sequence"},
    {"y":2024,"n":33,"p":20,"m":1,"ty":"NAT","tid":"co3","l":"E","k":null,"t":"Derivative of sigmoid at f(x) = 0.4"},
    {"y":2024,"n":34,"p":21,"m":1,"ty":"NAT","tid":"ps4","l":"E","k":"desc","t":"Updated sample mean after adding a point"},
    {"y":2024,"n":35,"p":21,"m":1,"ty":"NAT","tid":"la2","l":"M","k":"la_det","t":"Determinant of M² + 12M"},
    {"y":2024,"n":36,"p":21,"m":2,"ty":"MCQ","tid":"ps7","l":"H","k":"cond_exp","t":"Expected throws until two consecutive evens"},
    {"y":2024,"n":37,"p":22,"m":2,"ty":"MCQ","tid":"co2","l":"M","k":null,"t":"Piecewise function: continuous and differentiable"},
    {"y":2024,"n":38,"p":23,"m":2,"ty":"MCQ","tid":"pd1","l":"M","k":null,"t":"Python recursion over a dict (tree size)"},
    {"y":2024,"n":39,"p":24,"m":2,"ty":"MCQ","tid":"pd2","l":"M","k":null,"t":"Pseudocode on an array (stack-span style)"},
    {"y":2024,"n":40,"p":25,"m":2,"ty":"MCQ","tid":"pd7","l":"E","k":null,"t":"Binary search comparisons recurrence"},
    {"y":2024,"n":41,"p":25,"m":2,"ty":"MCQ","tid":"pd1","l":"E","k":null,"t":"Python recursive swap: what it does"},
    {"y":2024,"n":42,"p":26,"m":2,"ty":"MCQ","tid":"ml14","l":"M","k":null,"t":"Single-linkage clustering from a distance table"},
    {"y":2024,"n":43,"p":27,"m":2,"ty":"MCQ","tid":"ml13","l":"M","k":null,"t":"Two ReLU networks (figure): equivalence"},
    {"y":2024,"n":44,"p":28,"m":2,"ty":"MCQ","tid":"ai2","l":"M","k":null,"t":"State-space search: expansion order"},
    {"y":2024,"n":45,"p":28,"m":2,"ty":"MCQ","tid":"pd8","l":"M","k":null,"t":"Sorting after exactly two passes"},
    {"y":2024,"n":46,"p":29,"m":2,"ty":"MSQ","tid":"db6","l":"M","k":null,"t":"Derivable functional dependencies"},
    {"y":2024,"n":47,"p":30,"m":2,"ty":"MSQ","tid":"la4","l":"M","k":"la_space","t":"Which sets are subspaces of R³"},
    {"y":2024,"n":48,"p":31,"m":2,"ty":"MSQ","tid":"la3","l":"M","k":"la_elim","t":"Existence of solutions of Mx = p"},
    {"y":2024,"n":49,"p":32,"m":2,"ty":"MSQ","tid":"la6","l":"H","k":"la_proj","t":"Projection matrix: null space, rank"},
    {"y":2024,"n":50,"p":32,"m":2,"ty":"MSQ","tid":"co5","l":"M","k":null,"t":"Local extrema of a quartic"},
    {"y":2024,"n":51,"p":33,"m":2,"ty":"MSQ","tid":"pd11","l":"M","k":null,"t":"Valid topological orders of a DAG"},
    {"y":2024,"n":52,"p":34,"m":2,"ty":"MSQ","tid":"pd5","l":"M","k":null,"t":"Binary tree: height, internal, leaf bounds"},
    {"y":2024,"n":53,"p":35,"m":2,"ty":"MSQ","tid":"ml9","l":"E","k":null,"t":"Linear separability of datasets (figure, MSQ)"},
    {"y":2024,"n":54,"p":36,"m":2,"ty":"MSQ","tid":"ai6","l":"M","k":null,"t":"First-order logic sentences: entailment"},
    {"y":2024,"n":55,"p":37,"m":2,"ty":"NAT","tid":"db5","l":"H","k":null,"t":"SQL query on a movie database"},
    {"y":2024,"n":56,"p":37,"m":2,"ty":"NAT","tid":"ps6","l":"M","k":"joint","t":"P(X ≥ Y) for independent uniforms"},
    {"y":2024,"n":57,"p":38,"m":2,"ty":"NAT","tid":"ps6","l":"E","k":"expo","t":"Exponential: 5E(X) = Var(X)"},
    {"y":2024,"n":58,"p":38,"m":2,"ty":"NAT","tid":"ps3","l":"E","k":"bayes","t":"Bayes: P(T | S)"},
    {"y":2024,"n":59,"p":38,"m":2,"ty":"NAT","tid":"ps7","l":"M","k":"cond_exp","t":"E[Y | X = 1.5] from a joint density"},
    {"y":2024,"n":60,"p":38,"m":2,"ty":"NAT","tid":"co1","l":"M","k":null,"t":"Limit of ln((x²+1)cos x)/x²"},
    {"y":2024,"n":61,"p":39,"m":2,"ty":"NAT","tid":"la8","l":"E","k":"la_svd","t":"Sum of singular values of uuᵀ"},
    {"y":2024,"n":62,"p":39,"m":2,"ty":"NAT","tid":"ml10","l":"M","k":"entropy","t":"Decision tree: information gain from a table"},
    {"y":2024,"n":63,"p":40,"m":2,"ty":"NAT","tid":"ml6","l":"M","k":null,"t":"k-NN: minimum odd k for a class (figure)"},
    {"y":2024,"n":64,"p":41,"m":2,"ty":"NAT","tid":"ai8","l":"H","k":null,"t":"Bayesian network: exact inference with CPTs"},
    {"y":2024,"n":65,"p":41,"m":2,"ty":"NAT","tid":"ps4","l":"M","k":"cov","t":"Covariance of two coin indicators"},
    {"y":2025,"n":1,"p":1,"m":1,"ty":"MCQ","tid":"ga1","l":"E","k":null,"t":"Word analogy"},
    {"y":2025,"n":2,"p":1,"m":1,"ty":"MCQ","tid":"ga1","l":"E","k":null,"t":"Tense: fill in the blank"},
    {"y":2025,"n":3,"p":2,"m":1,"ty":"MCQ","tid":"ga2","l":"E","k":null,"t":"Pixel intensity grid (figure): count"},
    {"y":2025,"n":4,"p":3,"m":1,"ty":"MCQ","tid":"ga3","l":"M","k":null,"t":"Numbers on overlapping shapes (figure)"},
    {"y":2025,"n":5,"p":4,"m":1,"ty":"MCQ","tid":"ga2","l":"E","k":null,"t":"Rectangle: percentage change"},
    {"y":2025,"n":6,"p":5,"m":2,"ty":"MCQ","tid":"ga1","l":"M","k":null,"t":"Match statements to responses"},
    {"y":2025,"n":7,"p":6,"m":2,"ty":"MCQ","tid":"ga3","l":"M","k":null,"t":"Graph of weight vs age: interpretation"},
    {"y":2025,"n":8,"p":7,"m":2,"ty":"MCQ","tid":"ga2","l":"M","k":null,"t":"Regular dodecagon in a circle: area"},
    {"y":2025,"n":9,"p":8,"m":2,"ty":"MCQ","tid":"ga2","l":"E","k":null,"t":"Exponent equation"},
    {"y":2025,"n":10,"p":9,"m":2,"ty":"MCQ","tid":"ga2","l":"M","k":null,"t":"Histogram of patients: data interpretation"},
    {"y":2025,"n":11,"p":10,"m":1,"ty":"MCQ","tid":"ps7","l":"E","k":"cond_exp","t":"E[E[X | Y]] = E[X]"},
    {"y":2025,"n":12,"p":10,"m":1,"ty":"MCQ","tid":"la3","l":"E","k":"la_elim","t":"Cost of Gaussian elimination on a triangular matrix"},
    {"y":2025,"n":13,"p":10,"m":1,"ty":"MCQ","tid":"la5","l":"M","k":"la_eig","t":"Row sums 1: solutions of Bx = 0"},
    {"y":2025,"n":14,"p":11,"m":1,"ty":"MCQ","tid":"co4","l":"E","k":null,"t":"10th derivative of sinh at 0 (Taylor)"},
    {"y":2025,"n":15,"p":11,"m":1,"ty":"MCQ","tid":"ai5","l":"E","k":null,"t":"Equivalent propositional statements"},
    {"y":2025,"n":16,"p":11,"m":1,"ty":"MCQ","tid":"db6","l":"E","k":null,"t":"Non-dependency-preserving decomposition needs joins"},
    {"y":2025,"n":17,"p":12,"m":1,"ty":"MCQ","tid":"db3","l":"M","k":null,"t":"Relational algebra on Car / Make / Own"},
    {"y":2025,"n":18,"p":12,"m":1,"ty":"MCQ","tid":"pd6","l":"E","k":null,"t":"Linear probing with h(x) = 3x mod 10"},
    {"y":2025,"n":19,"p":13,"m":1,"ty":"MCQ","tid":"ps6","l":"E","k":"cdf","t":"Uniform CDF with median 3: find t"},
    {"y":2025,"n":20,"p":13,"m":1,"ty":"MCQ","tid":"ps6","l":"M","k":"normal","t":"X = aZ + b: find a and b from moments"},
    {"y":2025,"n":21,"p":14,"m":1,"ty":"MCQ","tid":"ps6","l":"E","k":"expo","t":"Exponential: λ from P(X ≥ 2)"},
    {"y":2025,"n":22,"p":14,"m":1,"ty":"MCQ","tid":"ml9","l":"M","k":null,"t":"Linear classifier: margin and scaling"},
    {"y":2025,"n":23,"p":15,"m":1,"ty":"MCQ","tid":"pd1","l":"E","k":null,"t":"Python list extend vs append"},
    {"y":2025,"n":24,"p":15,"m":1,"ty":"MSQ","tid":"co2","l":"M","k":null,"t":"Differentiability of sums/products/compositions"},
    {"y":2025,"n":25,"p":15,"m":1,"ty":"MSQ","tid":"la6","l":"E","k":"la_orth","t":"Orthonormal bases of Rⁿ"},
    {"y":2025,"n":26,"p":16,"m":1,"ty":"MSQ","tid":"ai8","l":"E","k":null,"t":"Exact vs approximate inference methods"},
    {"y":2025,"n":27,"p":16,"m":1,"ty":"MSQ","tid":"pd7","l":"E","k":null,"t":"When binary search is O(log n)"},
    {"y":2025,"n":28,"p":16,"m":1,"ty":"MSQ","tid":"la5","l":"M","k":"la_eig","t":"I + xxᵀ: rank, invertibility, eigenvalues"},
    {"y":2025,"n":29,"p":16,"m":1,"ty":"MSQ","tid":"pd8","l":"M","k":null,"t":"Insertion sort: values giving exactly two swaps"},
    {"y":2025,"n":30,"p":17,"m":1,"ty":"MSQ","tid":"ml14","l":"E","k":null,"t":"Single / complete / average linkage definitions"},
    {"y":2025,"n":31,"p":17,"m":1,"ty":"NAT","tid":"ps3","l":"M","k":"bayes","t":"Three boxes: Bayes posterior"},
    {"y":2025,"n":32,"p":17,"m":1,"ty":"NAT","tid":"co1","l":"E","k":null,"t":"Limit of √(t² + t) − t"},
    {"y":2025,"n":33,"p":18,"m":1,"ty":"NAT","tid":"db5","l":"M","k":null,"t":"SQL aggregate on Loan table"},
    {"y":2025,"n":34,"p":18,"m":1,"ty":"NAT","tid":"ml2","l":"E","k":"regression","t":"Least squares through the origin"},
    {"y":2025,"n":35,"p":18,"m":1,"ty":"NAT","tid":"ml7","l":"E","k":null,"t":"Naive Bayes posterior"},
    {"y":2025,"n":36,"p":19,"m":2,"ty":"MCQ","tid":"ps6","l":"M","k":"tchi","t":"Variance of Z² (chi-square)"},
    {"y":2025,"n":37,"p":19,"m":2,"ty":"MCQ","tid":"la1","l":"M","k":"la_mat","t":"A³ = A: which property always holds"},
    {"y":2025,"n":38,"p":19,"m":2,"ty":"MCQ","tid":"la4","l":"M","k":"la_rank","t":"Gram matrix of independent vectors"},
    {"y":2025,"n":39,"p":20,"m":2,"ty":"MCQ","tid":"ps6","l":"M","k":"cdf","t":"P(X² ≤ 0.25) from a CDF"},
    {"y":2025,"n":40,"p":20,"m":2,"ty":"MCQ","tid":"ps5","l":"M","k":"binom","t":"Sum of Bernoullis: binomial properties"},
    {"y":2025,"n":41,"p":21,"m":2,"ty":"MCQ","tid":"ps6","l":"H","k":"expo","t":"Floor of an exponential is geometric"},
    {"y":2025,"n":42,"p":22,"m":2,"ty":"MCQ","tid":"ml13","l":"E","k":null,"t":"ReLU network forward pass (figure)"},
    {"y":2025,"n":43,"p":23,"m":2,"ty":"MCQ","tid":"ai4","l":"M","k":null,"t":"Alpha-beta pruning on two trees (figure)"},
    {"y":2025,"n":44,"p":24,"m":2,"ty":"MCQ","tid":"ai3","l":"M","k":null,"t":"A* search on a state graph (figure)"},
    {"y":2025,"n":45,"p":24,"m":2,"ty":"MCQ","tid":"ps2","l":"E","k":"prob_classic","t":"100 dice: at least one shows 1"},
    {"y":2025,"n":46,"p":25,"m":2,"ty":"MCQ","tid":"db9","l":"M","k":null,"t":"OLAP fact table: cube and aggregates"},
    {"y":2025,"n":47,"p":26,"m":2,"ty":"MCQ","tid":"pd1","l":"H","k":null,"t":"Python sets updated in a loop: final values"},
    {"y":2025,"n":48,"p":26,"m":2,"ty":"MSQ","tid":"ml13","l":"E","k":null,"t":"Properties of ReLU"},
    {"y":2025,"n":49,"p":27,"m":2,"ty":"MSQ","tid":"co5","l":"M","k":null,"t":"Max/min of a cubic on an interval"},
    {"y":2025,"n":50,"p":27,"m":2,"ty":"MSQ","tid":"la8","l":"M","k":"la_svd","t":"Sum of xxᵀ over orthonormal vectors: SVD"},
    {"y":2025,"n":51,"p":27,"m":2,"ty":"MSQ","tid":"co5","l":"M","k":null,"t":"Consequences of f″ > 0"},
    {"y":2025,"n":52,"p":28,"m":2,"ty":"MSQ","tid":"la1","l":"M","k":"la_orth","t":"Norm-preserving matrix is orthogonal"},
    {"y":2025,"n":53,"p":28,"m":2,"ty":"MSQ","tid":"ml9","l":"M","k":null,"t":"Hard-margin SVM on a small dataset"},
    {"y":2025,"n":54,"p":29,"m":2,"ty":"MSQ","tid":"ps8","l":"M","k":"sampling","t":"Sample proportion: unbiasedness, variance"},
    {"y":2025,"n":55,"p":29,"m":2,"ty":"MSQ","tid":"ml8","l":"M","k":null,"t":"Nearest-mean classifier: linear boundary"},
    {"y":2025,"n":56,"p":30,"m":2,"ty":"MSQ","tid":"db2","l":"M","k":null,"t":"Primary / foreign key constraints"},
    {"y":2025,"n":57,"p":31,"m":2,"ty":"MSQ","tid":"db6","l":"M","k":null,"t":"Candidate keys from FDs"},
    {"y":2025,"n":58,"p":31,"m":2,"ty":"MSQ","tid":"pd10","l":"M","k":null,"t":"Shortest paths in a graph (figure, MSQ)"},
    {"y":2025,"n":59,"p":31,"m":2,"ty":"NAT","tid":"co2","l":"M","k":null,"t":"|f(x) − f(y)| ≤ (x − y)² ⇒ f constant"},
    {"y":2025,"n":60,"p":32,"m":2,"ty":"NAT","tid":"ml15","l":"M","k":"la_pca","t":"PCA: variance along the top direction"},
    {"y":2025,"n":61,"p":32,"m":2,"ty":"NAT","tid":"ps5","l":"E","k":"binom","t":"Expected black balls with replacement"},
    {"y":2025,"n":62,"p":32,"m":2,"ty":"NAT","tid":"db5","l":"M","k":null,"t":"SQL join on Loan and Borrower"},
    {"y":2025,"n":63,"p":33,"m":2,"ty":"NAT","tid":"pd1","l":"M","k":null,"t":"Python recursion output"},
    {"y":2025,"n":64,"p":34,"m":2,"ty":"NAT","tid":"pd3","l":"M","k":null,"t":"Stack pseudocode: final sum"},
    {"y":2025,"n":65,"p":34,"m":2,"ty":"NAT","tid":"pd11","l":"H","k":null,"t":"DFS on a DAG with ordered adjacency"},
    {"y":2026,"n":1,"p":1,"m":1,"ty":"MCQ","tid":"ga1","l":"E","k":null,"t":"Word analogy"},
    {"y":2026,"n":2,"p":1,"m":1,"ty":"MCQ","tid":"ga2","l":"E","k":null,"t":"Digits with product 70: sum"},
    {"y":2026,"n":3,"p":2,"m":1,"ty":"MCQ","tid":"ga3","l":"M","k":null,"t":"Puzzle pieces (figure)"},
    {"y":2026,"n":4,"p":3,"m":1,"ty":"MCQ","tid":"ga2","l":"M","k":null,"t":"Compare n^log m and m^log n"},
    {"y":2026,"n":5,"p":3,"m":1,"ty":"MCQ","tid":"ga1","l":"M","k":null,"t":"Conditional sentence: inference"},
    {"y":2026,"n":6,"p":4,"m":2,"ty":"MCQ","tid":"ga1","l":"E","k":null,"t":"Prepositions"},
    {"y":2026,"n":7,"p":4,"m":2,"ty":"MCQ","tid":"ga2","l":"M","k":null,"t":"Five integers with given mean, median, mode"},
    {"y":2026,"n":8,"p":5,"m":2,"ty":"MCQ","tid":"ga3","l":"M","k":null,"t":"Classmates arrangement puzzle"},
    {"y":2026,"n":9,"p":6,"m":2,"ty":"MCQ","tid":"ga2","l":"H","k":null,"t":"Digit puzzle with distinct digits"},
    {"y":2026,"n":10,"p":7,"m":2,"ty":"MCQ","tid":"ga2","l":"M","k":null,"t":"Points on a circle: geometry (figure)"},
    {"y":2026,"n":11,"p":8,"m":1,"ty":"MCQ","tid":"ml15","l":"E","k":"la_pca","t":"PCA: angle between principal components"},
    {"y":2026,"n":12,"p":8,"m":1,"ty":"MCQ","tid":"ml12","l":"M","k":null,"t":"LOOCV on a dataset: number of fits"},
    {"y":2026,"n":13,"p":9,"m":1,"ty":"MCQ","tid":"ai2","l":"E","k":null,"t":"Which search is not uninformed"},
    {"y":2026,"n":14,"p":9,"m":1,"ty":"MCQ","tid":"ai6","l":"M","k":null,"t":"First-order logic statements: which is false"},
    {"y":2026,"n":15,"p":10,"m":1,"ty":"MCQ","tid":"pd9","l":"M","k":null,"t":"Quicksort (first pivot): expected-time recurrence"},
    {"y":2026,"n":16,"p":11,"m":1,"ty":"MCQ","tid":"pd1","l":"M","k":null,"t":"Python mutable default argument"},
    {"y":2026,"n":17,"p":12,"m":1,"ty":"MCQ","tid":"db6","l":"M","k":null,"t":"Candidate keys from FDs"},
    {"y":2026,"n":18,"p":12,"m":1,"ty":"MCQ","tid":"db9","l":"E","k":null,"t":"Data cube: roll-up / drill-down choice"},
    {"y":2026,"n":19,"p":13,"m":1,"ty":"MCQ","tid":"ps2","l":"H","k":"prob_classic","t":"Random subset: product of elements is even"},
    {"y":2026,"n":20,"p":13,"m":1,"ty":"MCQ","tid":"ps1","l":"M","k":"cnt_stars","t":"Integer solutions: probability all positive"},
    {"y":2026,"n":21,"p":14,"m":1,"ty":"MCQ","tid":"la1","l":"E","k":"la_mat","t":"Rotation matrix raised to a power"},
    {"y":2026,"n":22,"p":14,"m":1,"ty":"MCQ","tid":"la4","l":"M","k":"la_space","t":"Ball ∩ 2-D subspace: area"},
    {"y":2026,"n":23,"p":15,"m":1,"ty":"MSQ","tid":"ml1","l":"E","k":null,"t":"Match ML tasks to algorithms"},
    {"y":2026,"n":24,"p":16,"m":1,"ty":"MSQ","tid":"ai5","l":"E","k":null,"t":"Entailment equivalences"},
    {"y":2026,"n":25,"p":17,"m":1,"ty":"MSQ","tid":"pd5","l":"M","k":null,"t":"Tree from preorder + inorder"},
    {"y":2026,"n":26,"p":18,"m":1,"ty":"MSQ","tid":"db2","l":"M","k":null,"t":"Operations that never violate a foreign key"},
    {"y":2026,"n":27,"p":18,"m":1,"ty":"MSQ","tid":"co5","l":"M","k":null,"t":"Cubic on an interval: roots and extrema"},
    {"y":2026,"n":28,"p":19,"m":1,"ty":"MSQ","tid":"ps6","l":"M","k":"tchi","t":"Normal vs t₁ density and CDF"},
    {"y":2026,"n":29,"p":20,"m":1,"ty":"NAT","tid":"co6","l":"M","k":null,"t":"SGD update steps"},
    {"y":2026,"n":30,"p":20,"m":1,"ty":"NAT","tid":"ai4","l":"M","k":null,"t":"Minimax game tree value (figure, NAT)"},
    {"y":2026,"n":31,"p":20,"m":1,"ty":"NAT","tid":"pd7","l":"M","k":null,"t":"Recursive binary search: comparisons"},
    {"y":2026,"n":32,"p":21,"m":1,"ty":"NAT","tid":"db7","l":"M","k":null,"t":"B+ tree order from block size"},
    {"y":2026,"n":33,"p":21,"m":1,"ty":"NAT","tid":"ps1","l":"M","k":"cnt_arr","t":"Involutions on 4 elements"},
    {"y":2026,"n":34,"p":21,"m":1,"ty":"NAT","tid":"ps6","l":"E","k":"expo","t":"Exponential memoryless"},
    {"y":2026,"n":35,"p":21,"m":1,"ty":"NAT","tid":"co1","l":"E","k":null,"t":"Double geometric series sum"},
    {"y":2026,"n":36,"p":22,"m":2,"ty":"MCQ","tid":"ml14","l":"M","k":null,"t":"Agglomerative clustering with Manhattan distance"},
    {"y":2026,"n":37,"p":23,"m":2,"ty":"MCQ","tid":"ml4","l":"E","k":null,"t":"Purpose of the ridge regulariser"},
    {"y":2026,"n":38,"p":23,"m":2,"ty":"MCQ","tid":"ai5","l":"M","k":null,"t":"Encode a statement in propositional logic"},
    {"y":2026,"n":39,"p":24,"m":2,"ty":"MCQ","tid":"pd2","l":"M","k":null,"t":"Recursive calls and stack depth (Python)"},
    {"y":2026,"n":40,"p":25,"m":2,"ty":"MCQ","tid":"pd11","l":"M","k":null,"t":"Reverse graph properties"},
    {"y":2026,"n":41,"p":26,"m":2,"ty":"MCQ","tid":"db7","l":"M","k":null,"t":"B+ tree after insertion (figure)"},
    {"y":2026,"n":42,"p":27,"m":2,"ty":"MCQ","tid":"db3","l":"M","k":null,"t":"Relational algebra on three tables"},
    {"y":2026,"n":43,"p":28,"m":2,"ty":"MCQ","tid":"db9","l":"M","k":null,"t":"Number of cuboids with concept hierarchies (figure)"},
    {"y":2026,"n":44,"p":29,"m":2,"ty":"MCQ","tid":"ps4","l":"M","k":"exp_var","t":"Var((2X − 1)Y) for independent X, Y"},
    {"y":2026,"n":45,"p":29,"m":2,"ty":"MCQ","tid":"ps8","l":"H","k":"clt","t":"Limit of Poisson CDF at its mean (CLT)"},
    {"y":2026,"n":46,"p":30,"m":2,"ty":"MCQ","tid":"la5","l":"M","k":"la_eig","t":"Eigenvalues of a rotation block: trace condition"},
    {"y":2026,"n":47,"p":31,"m":2,"ty":"MSQ","tid":"ml1","l":"E","k":null,"t":"Confusion matrix: precision / recall"},
    {"y":2026,"n":48,"p":31,"m":2,"ty":"MSQ","tid":"ai6","l":"E","k":null,"t":"Validity of quantified statements"},
    {"y":2026,"n":49,"p":32,"m":2,"ty":"MSQ","tid":"pd8","l":"M","k":null,"t":"Bubble vs insertion sort comparisons"},
    {"y":2026,"n":50,"p":33,"m":2,"ty":"MSQ","tid":"pd1","l":"M","k":null,"t":"Python closures: printed output"},
    {"y":2026,"n":51,"p":34,"m":2,"ty":"MSQ","tid":"db5","l":"M","k":null,"t":"SQL constraint on Employee / Team"},
    {"y":2026,"n":52,"p":35,"m":2,"ty":"MSQ","tid":"la1","l":"M","k":"la_proj","t":"Centering matrix: symmetric, idempotent"},
    {"y":2026,"n":53,"p":35,"m":2,"ty":"MSQ","tid":"ps8","l":"M","k":"tchi","t":"Sampling distributions: χ² and mean"},
    {"y":2026,"n":54,"p":36,"m":2,"ty":"MSQ","tid":"ps4","l":"E","k":"cdf","t":"Properties of a discrete CDF"},
    {"y":2026,"n":55,"p":36,"m":2,"ty":"NAT","tid":"ml4","l":"M","k":null,"t":"Ridge regression loss computation"},
    {"y":2026,"n":56,"p":37,"m":2,"ty":"NAT","tid":"ml13","l":"E","k":null,"t":"MLP parameter count"},
    {"y":2026,"n":57,"p":37,"m":2,"ty":"NAT","tid":"ps3","l":"E","k":"bayes","t":"Disease test: Bayes"},
    {"y":2026,"n":58,"p":37,"m":2,"ty":"NAT","tid":"pd1","l":"M","k":null,"t":"Python recursive bubble pass: swap count"},
    {"y":2026,"n":59,"p":38,"m":2,"ty":"NAT","tid":"db4","l":"M","k":null,"t":"Tuple relational calculus output"},
    {"y":2026,"n":60,"p":38,"m":2,"ty":"NAT","tid":"db5","l":"M","k":null,"t":"Correlated subquery output"},
    {"y":2026,"n":61,"p":39,"m":2,"ty":"NAT","tid":"db1","l":"M","k":null,"t":"ER to tables: minimum count"},
    {"y":2026,"n":62,"p":39,"m":2,"ty":"NAT","tid":"ps4","l":"M","k":"desc","t":"Sample variance from pairwise differences"},
    {"y":2026,"n":63,"p":39,"m":2,"ty":"NAT","tid":"ps7","l":"M","k":"cov","t":"Correlation when Y | X ~ Uniform(x² ± 0.1)"},
    {"y":2026,"n":64,"p":39,"m":2,"ty":"NAT","tid":"ps5","l":"M","k":"binom","t":"Bernoulli matrix: row and column sums"},
    {"y":2026,"n":65,"p":39,"m":2,"ty":"NAT","tid":"la7","l":"M","k":"la_pd","t":"Max of xᵀAx on the unit sphere"}
  ]
};
